### ISSUE TITLE
Wiki minor fix

### ISSUE THREAD

**Issue by AnthonyTruchet** [combust/mleap#107]
I'm playing https://github.com/combust/mleap/wiki/Serializing-a-Spark-ML-Pipeline-and-Scoring-with-MLeap#serialize-the-ml-data-pipeline-and-rf-model-to-bundleml and I struggled to realize that one should read **featureModel** instead of _featurePipeline_ in
```
val pipeline = SparkUtil.createPipelineModel(uid = "pipeline", Array(featurePipeline, rf))
```

I could'nt find another way to contribute to the wiki (like PR) - feel free to tell me how you wish to receive such contribs.

**Comment by seme0021** [comment]
@AnthonyTruchet 

Unfortunately github doesn't support pull requests for the wiki repository, so for now, creating an issue, emailing us, or pinging us on gitter (we'll check that more frequently) is the best way.

I updated the wiki - thank you for the find!

**Comment by AnthonyTruchet** [comment]
Thanks for quick answer :-) I tried gitter but I'm not familliar with it ans its good practices, so tell me in case I'm not using the right (TM) channels ;-) Is there any developer list or other way to share interest and development on the project ? We (Criteo) see a huge interest to it and could be ready to contribute significantly depending on the ongoing evaluation. Feel free to discuss this directly though  "a (dot) <my family name> (at) criteo.com.
