### ISSUE TITLE
deserialize the bundle model and got Bundle[Nothing]

### ISSUE THREAD

**Issue by thetuxedo** [combust/mleap#110]
When I deserialize the bundle model (a simple Random Forest Model) from jar zip file,  like
     val bundle = BundleFile("jar:file:/home//userA/rf.zip").load().get
I got a bundle of type ml.combust.bundle.dsl.Bundle[Nothing],

and then when I access root, I got following exceptions:
java.lang.ClassCastException: ml.combust.mleap.runtime.transformer.Pipeline cannot be cast to scala.runtime.Nothing$

Thanks for help in advance!

**Comment by hollinwilkins** [comment]
Hey there,

You are trying to use the raw load function, that requires additional steps to configure properly. Instead, try this:

```
import ml.combust.mleap.runtime.MleapSupport._
BundleFile("jar:file:/home//userA/rf.zip").loadMleapBundle().get
```

**Comment by thetuxedo** [comment]
Thanks for the prompt reply. It works now.
