### ISSUE TITLE
ConfigException$Missing on SparkBundleContext initialization

### ISSUE THREAD

**Issue by thetuxedo** [combust/mleap#113]
Dear sir or Madam,
When I try to save the model using:
val sbc = SparkBundleContext().withDataset(pipeline.transform(df))
there is following exception:
com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'ml'

I am using iheart/ficus for configuration setting, which is built on top of the typesafe.config library.
So in the beginning of my program, i have code like:
val conf = ConfigFactory.load()
val settings = new Settings(conf)
which will read configuration from reference.conf and application.conf.

When I test the code in spark-shell, without using typesafe.config library, the code works.

How can I continue to use typesafe.config on my own without breaking MLeap?

Thanks.

**Comment by hollinwilkins** [comment]
Hey,

If you are manually loading the typesafe config, you could try this:

```
SparkBundleContext(dataset = None,
    bundleRegistry = BundleRegistry("ml.combust.mleap.spark.registry.default", Some(typesafeConfig), None))
```

typesafeConfig is a Typesafe Config object you have loaded, and must contain the desired Spark registry specified by the first string argument to BundleRegistry.

**Comment by thetuxedo** [comment]
Hi,
Thanks for prompt reply.
Could you please explain a bit more on:
"must contain the desired Spark registry specified by the first string argument to BundleRegistry."
where can I find an example?
Thanks.

**Comment by hollinwilkins** [comment]
Take a look at the bottom of our default reference.conf file, where we set the default Spark registry to v20 (Spark 2.0 registry):

https://github.com/combust/mleap/blob/master/mleap-spark/src/main/resources/reference.conf

The registry is responsible for defining all of the ops that MLeap knows how to serialize/deserialize. So you will want to copy and paste most of the reference.conf file if you don't have access to it.

**Comment by hollinwilkins** [comment]
I am curious as to why you don't have access to our reference.conf file that is packaged with mleap-spark though. Are you generating an assembly file and it is perhaps being lost in the packaging process?

**Comment by thetuxedo** [comment]
Yes, I am generating a uber jar for deployment. In my build.sbt, I add following dependency, 
"ml.combust.mleap"      %% "mleap-spark"      % "0.5.0"

is that enough?

**Comment by thetuxedo** [comment]
After I put all mleap related conf into my reference.conf, the problem is gone.

It is a bit messy through as my reference.conf contains all these irrelevant information. But it works.
Uber jar is the common way to deploy spark program. What's the best way to do it to integrate with MLeap?

I will close this issue soon.

**Comment by hollinwilkins** [comment]
Hey,

Which plugin are you using to generate the uber jar? We have used sbt-assembly to successfully deploy jobs including MLeap before. I would look into the documentation for whichever tool you are using and make sure that the reference.conf file is being merged properly with the MLeap reference.conf files.

**Comment by thetuxedo** [comment]
I am using sbt-assembly.
I create an assembly.sbt under project folder, and it contains
addSbtPlugin("com.eed3si9n" % "sbt-assembly" % "0.14.3")

I am using spark-2.0.2
scala 2.11.8

my build.sbt is like:
scalaVersion := "2.11.8"

val sparkVersion = "2.0.2"

resolvers ++= Seq(
  "All Spark Repository -> bintray-spark-packages" at "https://dl.bintray.com/spark-packages/maven/"
)

libraryDependencies ++= Seq(
  "org.apache.spark"      %% "spark-core"       % sparkVersion % "provided" exclude("jline", "2.12"),
  "org.apache.spark"      %% "spark-sql"        % sparkVersion % "provided" excludeAll(ExclusionRule(organization = "jline"),ExclusionRule("name","2.12")),
  "org.apache.spark"      %% "spark-mllib"      % sparkVersion % "provided",
  "org.apache.spark"      %% "spark-hive"       % sparkVersion % "provided",
  "org.apache.spark"      %% "spark-yarn"       % sparkVersion % "provided",
  "org.apache.spark"      %% "spark-graphx"     % sparkVersion % "provided",
  "org.apache.spark"      %% "spark-catalyst"   % sparkVersion % "provided",
  "org.apache.spark"      %% "spark-streaming"  % sparkVersion % "provided",
  "com.typesafe"          % "config"            % "1.3.1",
  "com.iheart"            %% "ficus"            % "1.4.0",
  "ml.combust.mleap"      %% "mleap-spark"      % "0.5.0"
)

**Comment by thetuxedo** [comment]
Sorry, miss last part of my build.sbt

assemblyOption in assembly := (assemblyOption in assembly).value.copy(includeScala = false)

assemblyMergeStrategy in assembly := {
  case PathList("META-INF", xs @ _*) => MergeStrategy.discard
  case x => MergeStrategy.first
}

**Comment by hollinwilkins** [comment]
@thetuxedo The missing MLeap reference.conf data is most likely due to the sbt-assembly configuration. Make sure you are merging reference.conf files together instead of just merging the first in.

**Comment by thetuxedo** [comment]
i've changed my build.sbt to concat reference.conf, it works fine, without polluting my own reference.conf.

thanks a lot for your kind and prompt reply!
