### ISSUE TITLE
Nice Java Interface

### ISSUE THREAD

**Issue by hollinwilkins** [combust/mleap#117]
Currently working with MLeap from Java can be a pain. Let's make the interface nicer.

**Comment by hollinwilkins** [comment]
This will most likely be implemented as a combination of the following:

1. Making sure case classes have constructors that are compatible with Java
2. Builders that are Java-friendly
3. Java-friendly wrapper classes when all else fails

**Comment by bipptech** [comment]
`val bundle = (for (bundleFile <- managed(BundleFile("jar:file:/tmp/mleap-model.zip"))) yield {
      bundleFile.loadMleapBundle().get
    }).opt.get

    val schema = StructType(StructField("id", IntegerType()),
      StructField("description", StringType()), StructField("label", StringType())).get
    val data = LocalDataset(Row(1, "random text"))
    val frame = LeapFrame(schema, data)

    val mleapPipeline = bundle.root
    val frame2 = mleapPipeline.transform(frame).get
    frame2.printSchema()
    frame2.show()`

I am writing an evaluator/predictor in java which will be deployed on tomcat. Could you help me convert above  scala code in java?

**Comment by hollinwilkins** [comment]
@bipptech Executing Scala code from Java can be difficult for a variety of reasons. MLeap's biggest hurdle is all of the implicits it depends on. Let me flip this question on you. How would you like to see that code written in Java? We can work from there to design the Java interface to MLeap.

**Comment by bipptech** [comment]
First of all, i would like to thank you for your great service to ML community. Earlier I used to use spark in client mode for predictions and now I use MLeap. Its performance is beyond comparison. 

I wrote a scala object 
```
object MLeapPredictor {
  private val bundle = (for (bundleFile <- managed(BundleFile("jar:file:/tmp/mleap-model.zip"))) yield {
    bundleFile.loadMleapBundle().get
  }).opt.get

  private val schema = StructType(StructField("id", IntegerType()),
    StructField("description", StringType())).get

  def predict(description: String) = {
    val data = LocalDataset(Row(1, description))
    val frame = LeapFrame(schema, data)
    val mleapPipeline = bundle.root
    val frame2 = mleapPipeline.transform(frame).get.select("predictedLabel").get
    val data2 = frame2.dataset
    data2(0).getString(0)
  }
} 
```
and called  ``` MLeapPredictor.predict("<description>") ```  from a java class. Both these classes (scala and java ones) are bundled in a war and deployed in tomcat. It works perfectly fine.

However, it would be nice to have a java interface so that a Java developer also gets benefited from this wonderful tool.    

I would propose:

1) Load the bundle as a model
``` Model model = MLeap.loadModel("<file-path>") ;```
2) Initialize LeapFrame with schema and data
```  LeapFrame frame = new LeapFrame(<schema>, <data>) ;```
3) Transform the data
```  LeapFrame frame2 = model.transform(frame); ```

**Comment by hollinwilkins** [comment]
@bipptech This is a great start. Some of the items I think we will need to account for in the interface are this:

1. Building a schema, perhaps with a builder class?
2. Building the dataset. We want to expose Java data structures and have them converted to Scala data structures. So we will need to build a map from Java to Scala types and work with that.
3. For loading/serializing models, we want to account for passing in a BundleContext manually or using the default. We can encapsulate this functionality in a Java class
4. We need to account for manually creating a BundleContext from Java.

I am thinking right now that all "Try" return types in MLeap can just be unwrapped and the exception thrown for Java to catch. This seems like a more canonical Java way to handle exceptions.

**Comment by hollinwilkins** [comment]
@bipptech Just introduces a PR for a simple Java interface that should handle most basic needs of MLeap runtime. Let me know if we need anything more to get you guys up and running with Java.

https://github.com/combust/mleap/pull/188

**Comment by bipptech** [comment]
I get a compile-time error when i try to invoke select() method on DefaultLeapFrame. 

error:
```
error: incompatible types: String cannot be converted to Seq
               frame2.select("predictedLabel");
```

code:


```
                LeapFrameBuilder builder = new LeapFrameBuilder();
		List<StructField> fields = new ArrayList<StructField>();
		fields.add(builder.createField("id", builder.createInt()));
		fields.add(builder.createField("description", builder.createString()));
		fields.add(builder.createField("label", builder.createString()));
		StructType schema = builder.createSchema(fields);
		
		
		List<Row> rows = new ArrayList<Row>();
		rows.add(builder.createRow(1, "some random text", "1"));
		LocalDataset data = builder.createDataset(rows);
		
		
		DefaultLeapFrame frame = builder.createFrame(schema, data);
		
		
		
		MleapContext mleapContext = new ContextBuilder().createMleapContext();
		BundleBuilder bundleBuilder = new BundleBuilder();
		Transformer mleapPipeline = bundleBuilder.load(new File("/tmp/mleap-model.zip"), mleapContext).root();
		DefaultLeapFrame frame2 = mleapPipeline.transform(frame).get();
		
		frame2.select("predictedLabel");
 ```

**Comment by hollinwilkins** [comment]
@bipptech I think this is because Scala variable-length arguments are handled differently than Java, and it is expecting a Seq[String].

**Comment by bipptech** [comment]
I see an overloaded method which expects String* arguments when i press ctr+space in eclipse, but somehow it's not available at compile-time. 

Would this require a fix or is there something I need to do differently?

**Comment by hollinwilkins** [comment]
@bipptech I think this would require a fix if it's a compile time issue. Perhaps create a Java interface that LeapFrame inherits from would work well.

**Comment by siyouhe666** [comment]
> 
> 
> I get a compile-time error when i try to invoke select() method on DefaultLeapFrame.
> 
> error:
> 
> ```
> error: incompatible types: String cannot be converted to Seq
>                frame2.select("predictedLabel");
> ```
> 
> code:
> 
> ```
>                 LeapFrameBuilder builder = new LeapFrameBuilder();
> 		List<StructField> fields = new ArrayList<StructField>();
> 		fields.add(builder.createField("id", builder.createInt()));
> 		fields.add(builder.createField("description", builder.createString()));
> 		fields.add(builder.createField("label", builder.createString()));
> 		StructType schema = builder.createSchema(fields);
> 		
> 		
> 		List<Row> rows = new ArrayList<Row>();
> 		rows.add(builder.createRow(1, "some random text", "1"));
> 		LocalDataset data = builder.createDataset(rows);
> 		
> 		
> 		DefaultLeapFrame frame = builder.createFrame(schema, data);
> 		
> 		
> 		
> 		MleapContext mleapContext = new ContextBuilder().createMleapContext();
> 		BundleBuilder bundleBuilder = new BundleBuilder();
> 		Transformer mleapPipeline = bundleBuilder.load(new File("/tmp/mleap-model.zip"), mleapContext).root();
> 		DefaultLeapFrame frame2 = mleapPipeline.transform(frame).get();
> 		
> 		frame2.select("predictedLabel");
> ```

Hello, my leapframe type is an 80 dimension tensor, how can i define my input data like your "rows.add(builder.createRow(1, "some random text", "1"));"?
thanks

**Comment by ancasarb** [comment]
You can take a look at https://github.com/combust/mleap/blob/master/mleap-runtime/src/test/scala/ml/combust/mleap/runtime/javadsl/JavaDSLSpec.java#L38 where it's possible to pass in dense or sparse vectors that will be converted to tensors by mleap.

**Comment by marvinxu-free** [comment]
> You can take a look at https://github.com/combust/mleap/blob/master/mleap-runtime/src/test/scala/ml/combust/mleap/runtime/javadsl/JavaDSLSpec.java#L38 where it's possible to pass in dense or sparse vectors that will be converted to tensors by mleap.

hot to get tensor value in java with index?
