### ISSUE TITLE
Change release so that scala version is in jar name

### ISSUE THREAD

**Issue by anshbansal** [combust/mleap#118]
Like other scala based projects the release jar should have scala version in jar name or at least in the documentation.

**Comment by hollinwilkins** [comment]
Hey Aseem,

We already do this, take a look at maven central:
https://search.maven.org/#search%7Cga%7C1%7Cmleap

We cross-compile for Scala 2.10 and 2.11.

**Comment by anshbansal** [comment]
Sorry. I should go to sleep.
