### ISSUE TITLE
Add requirements in Getting started

### ISSUE THREAD

**Issue by anshbansal** [combust/mleap#119]
Requires JDK 8
Requires Scala 2.11

So that people can evaluate things faster to see whether this works with their tech stack or not.

**Comment by hollinwilkins** [comment]
Sure thing. We cross-compile for 2.10 and 2.11, so it should work with either Java 7 or Java 8 and Scala 2.10 or Scala 2.11

**Comment by anshbansal** [comment]
It does not work with Java 7. There is dependency on typesafe config which is Java 8 only.

**Comment by hollinwilkins** [comment]
Added requirements section to the README.md, thank you for pointing out Typesafe Config requires Java 8.
