### ISSUE TITLE
Improve error messages for ClassCastingException

### ISSUE THREAD

**Issue by anshbansal** [combust/mleap#120]
Using mleap 0.5 with Java 8 I was trying to create a DenseTensor and I got this error

> Failure(java.lang.ClassCastException: [Ljava.lang.Double; cannot be cast to [D)

I know that `[Ljava.lang.Double;` is the toString of a double array which I am supplying but `[D` is completely unknown. As there is no stacktrace it becomes difficult to debug this. Please improve error message

**Comment by anshbansal** [comment]
I should add that I found out that `[D` is a `double[]` but the error message is not helpful.

**Comment by hollinwilkins** [comment]
This would only be an issue when trying to call MLeap code from Java. We have another ticket for making a nice Java interface that will deal with this type conversion: https://github.com/combust/mleap/issues/117

Closing this issue as it will be handled by 117
