### ISSUE TITLE
Custom Feature Transformer Wiki

### ISSUE THREAD

**Issue by MeiSign** [combust/mleap#125]
I think the first code block in this documentation is wrong:

https://github.com/combust/mleap/wiki/Adding-an-MLeap-Spark-Transformer#4-implement-bundleml-serializer-for-the-spark-transformer

It is supposed to show the OpNode for Spark with a SparkBundleContext but shows code with a MLeapContext.

Is there a way to create pullrequests to the wiki? I could not find it...

**Comment by hollinwilkins** [comment]
Hey,

We have moved most of our documentation here:
http://mleap-docs.combust.ml/

Custom Transformer docs here:
http://mleap-docs.combust.ml/mleap-runtime/custom-transformer.html

I will take the existing Wiki page down or reroute people to the new docs.

Thanks for the catch

**Comment by hollinwilkins** [comment]
Added a notification to our Wiki that documentation has moved and also added a website link to the top of our Github page. Closing this issue.
