### ISSUE TITLE
Add methods to store Mleap bundles to and load from streams

### ISSUE THREAD

**Issue by anshbansal** [combust/mleap#128]
This can be helpful as this will let people load and save to multiple data sources. Mleap will not have to handle multiple stores like S3, hadoop just the streams. This will bring mleap somewhat on par with spark as it allows storing to multiple datastores transparently

Workaround is to download from datastore to a temporary file which is then loaded using local file system

**Comment by hollinwilkins** [comment]
@anshbansal 

We currently support storing to any Java NIO FileSystem. The reason we don't support streams is that MLeap Bundles are directory based and are more than one file. Spark works in the same way, except a Spark FileSystem is required in place of an NIO FileSystem.

Your method of saving locally to a temporary file then loading is a good one.

- Hollin

**Comment by hollinwilkins** [comment]
Closing this for now, will reopen if it comes up again.

**Comment by reddyjbaddam** [comment]
How do we load the Zipfile from the  stream  into MLeap library , Is there any overloaded method is available for load the stream into Bundle
