### ISSUE TITLE
Add getAsOption support to Row class

### ISSUE THREAD

**Issue by MeiSign** [combust/mleap#129]
I would like to have a get method on Rows that is kind of failsafe. Something like getOption(i) where I can get Some(value) at index i if it is available and None if it is not.
This would make working with the results of runtime apps much more comfortable. 

Row has an optionAs method for extracting options from rows but this method throws casting exceptions when you try to get a field from a row that is not an Option already.

I can support you with the implementation in case you want to add this feature.

**Example without getAsOption**

    val prediction: Option[Double] = for {
      dataset ← model.transform(messageDf).toOption
      predictionColumn ← dataset.select("prediction").toOption
      firstRow ← predictionColumn.dataset.headOption
      prediction ← firstRow.toSeq.headOption
    } yield prediction.asInstanceOf[Double] // could bang here

**Example with getAsOption**

    val prediction: Option[Double] = for {
      dataset ← model.transform(messageDf).toOption
      predictionColumn ← dataset.select("prediction").toOption
      firstRow ← predictionColumn.dataset.headOption
      prediction ← firstRow.getAsOption[Double](0)
    } yield prediction

    def getAsOption[T](index: Int): Option[T] = ???

**Comment by hollinwilkins** [comment]
@MeiSign Hey,

The current implementation of "nullable" values in MLeap works as follows:

1. Every DataType has an isNullable flag
2. When isNullable is set to false, this is assumed to mean that this value will NEVER be null in the LeapFrame
3. When isNullable is set to true, this is assumed to mean that values will be stored in the LeapFrame as an Option monad containing the data

When using nullable data, use the "option*" methods, when using non-nullable data use the regular getters. The reason for implementing it this way is that all of these ML algorithms do not accept null data, there are only a few feature transformers that allow nulls, and these we implemented as extensions to Spark such as Imputer and Coalesce.

**Comment by hollinwilkins** [comment]
@MeiSign Do these semantics meet your use case? Or do you still need the getAsOption method?

**Comment by MeiSign** [comment]
I am not sure if these semantics help with my exact usecase. But I think that the getAsOption method is probably kind of obsolete then. The only advantage is that it handles out of index and casting exceptions but this can also be handled in the code that calls the usual getter. So its probably overengineered. Thx for your explanation. :)

**Comment by hollinwilkins** [comment]
Sure thing, I am going to close this for now, but please reopen if you would like to add this method in. I think it has some use as well, especially for the out of bounds handling.
