### ISSUE TITLE
ImportError when using pyspark shell

### ISSUE THREAD

**Issue by manugarri** [combust/mleap#130]
I am not sure if this is because I am not using Toree (since I am not planning on using notebooks), but when I run the PySpark shell like:

`pyspark --packages ml.combust.mleap:mleap-spark_2.11:0.5.0`

`Mleap` is not recognized, throwing the usual error `ImportError: No module named 'mleap'` when importing.

Is there something I am missing? The package seems to exist in Mvn.

**Comment by hollinwilkins** [comment]
Which version of Spark or you using?

**Comment by manugarri** [comment]
Oh right, I apologize, I gave no info about my instance.

I have spark 2.0.1 and scala 2.11 .

**Comment by manugarri** [comment]
Oh right, I apologize, I gave no info about my instance.

I have spark 2.0.1 and scala 2.11 .

importing `import org.apache.spark.ml.mleap.SparkUtil` works in scala shell if that matters

**Comment by manugarri** [comment]
Any updates? maybe the reason is that mleap is not prepared for pySpark?

**Comment by hollinwilkins** [comment]
Hey,

Please take a look at the instructions here. You need to include MLeap on your Python path with PySpark, which requires cloning the repo right now as we don't have MLeap on PIP yet.

http://mleap-docs.combust.ml/getting-started/py-spark.html

**Comment by manugarri** [comment]
I think the issue is, im running spark on yarn, and appending to the path as per the docs does not seem to work under that condition.  Is there any way mleap can be packaged (e.g, a deployable egg or zipfile)?

**Comment by manugarri** [comment]
BTW, the link you sent me links to http://mleap-docs.combust.ml/integration/jupyter-notebooks.md which does not work.

**Comment by hollinwilkins** [comment]
Hey, sorry the link didn't copy right, check it out here: http://mleap-docs.combust.ml/getting-started/py-spark.html

Currently there is no way that MLeap for Python is packaged. MLeap for Scala can be packaged using SBT publishLocal, or snapshots can be used from OSS Sonatype.

**Comment by manugarri** [comment]
oh gotcha, ill try with scala then. Thanks!
