### ISSUE TITLE
[Question] Is there any guide on how to build the mleap-serving module?

### ISSUE THREAD

**Issue by manugarri** [combust/mleap#134]
I have followed http://mleap-docs.combust.ml/getting-started/building.html , but found that when doing `sbt compile` and `sbt package` no jars are created.

Is there any doc showing how one can build and run the serving part of Mleap? Thanks!

**Comment by hollinwilkins** [comment]
Hey,

MLeap serving isn't aggregated by the root SBT project, so you will have to do this:
```
sbt serving/package
```

Also, we create docker builds of it on our Travis CI server: http://mleap-docs.combust.ml/mleap-serving/

**Comment by manugarri** [comment]
yeah, i wish we could use docker, that is off the table unfortunately.

I built the serving layer by doing ` sbt mleap-serving/package` . That creates a jar in `mleap/mleap-serving/target/scala-2.11/mleap-serving_2.11-0.6.0-SNAPSHOT.jar `

My question is, how should I run it? running it with `java -jar ./mleap-serving/target/scala-2.11/mleap-serving_2.11-0.6.0-SNAPSHOT.jar`

Throws the following exception:

```Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: scala/Function0
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: scala.Function0
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
```

Which I believe is related with the jar not having all the required scala classes.

**Comment by hollinwilkins** [comment]
You either have to make a fat jar or I would recommend building a universal tarball:
http://www.scala-sbt.org/sbt-native-packager/formats/universal.html

**Comment by manugarri** [comment]
Is there any tutorial or guideline on how to build this? I am deciding between openscoring or mleap for a project and would love to give your project a try.  I am more of a python guy, so sbt falls out of my expertise unfortunately.

Alternatively maybe you could share your DockerFile so we could replicate whats in the container without having to use docker in production.

**Comment by hollinwilkins** [comment]
@manugarri There is no guide presently. But I will add it to the documentation with the 0.6.0 release.

Here is the short of it:
1. Install SBT
2. clone mleap and go into the root project folder
3. `sbt mleap-serving/universal:packageZipTarball`

The tarball will be built in `mleap-serving/target/universal`

You can then deploy this tarball anywhere by unzipping it. Once it's unzipped, you can then use the bin/mleap-serving script to start the server just as you would with docker commands.

**Comment by hollinwilkins** [comment]
It may be worth our while to figure out somewhere that we can deploy this artifact to in addition to docker images. If anyone has suggestions for how to do this, please share them here.

Thank you!

**Comment by hollinwilkins** [comment]
@manugarri I would also like to say that we are in the beginning stages of implementing MLeap outside of the JVM in a systems-level language which we plan to build Python bindings for as well as native serving libraries. This is a ways off, but perhaps is worth considering when you make your decision between open scoring and MLeap.

**Comment by manugarri** [comment]
thanks @hollinwilkins !  That seems to work. I am still exploring options. Ideally I would like to use mleap (since openscoring is quite limiting in the number of models it can deploy when compared to spark). It seems that as of now the only option is to use scala api from the spark side, which is fine. Do you have any deadlines on when to release the python bindings?

**Comment by hollinwilkins** [comment]
Hey there,

You can use our PySpark bindings right now, they just aren't released on PyPi, so you can't PIP install them. With our next release (0.7.0) we will be making a major push for Python features like scikit-learn integration and easier PySpark integration, including deploying these artifacts to PyPi.

**Comment by manugarri** [comment]
Great! Is there any ETA on when 0.7 will be released? I have been modifying openscoring to suit our needs, but coding in java makes me sad.

**Comment by manugarri** [comment]
Also, FYI, the build instructions commented in this thread (doing `sbt mleap-serving/universal:packageZipTarball`) fails with the following error stacktrace:

```
[info] Loading project definition from /storage/mleap/project
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[info] Set current project to mleap (in build file:/storage/workspace/mleap/)
[info] Compiling 34 Scala sources to /storage/mleap/bundle-ml/target/scala-2.11/classes...
[error] /storage/mleap/bundle-ml/src/main/scala/ml/combust/bundle/json/JsonSupport.scala:8: object bundle is not a member of package ml
[error] import ml.bundle.DataType.DataType
[error]           ^
[error] /storage/mleap/bundle-ml/src/main/scala/ml/combust/bundle/json/JsonSupport.scala:95: not found: type DataType
[error]   implicit val bundleDataTypeFormat: JsonFormat[DataType] = new JsonFormat[DataType] {
...
```
Which seems to point out that bundle is not a member of the package ml

My java version is `openjdk version "1.8.0_121"` and my scala version is `2.11.6`.

**Comment by hollinwilkins** [comment]
Make sure to do this first:

```
git submodule init
git submodule update
```

It is needed for the protobuf files that MLeap relies on.

**Comment by manugarri** [comment]
yaaay, that was the missing part! Thanks so much for your help! I think this should definitely be included in [the docs](http://mleap-docs.combust.ml/mleap-serving/)

**Comment by yeikel** [comment]
I followed the instructions , but when I lunch it , I get the following exception : 

```
[yeikel@scripts]$ ./mleap-spring-boot
Error: Could not find or load main class ml.combust.mleap.springboot.Starter
```

Any idea?
