### ISSUE TITLE
Update mleap-serving docker command documentation slightly to expose the model server locally

### ISSUE THREAD

**Issue by ancasarb** [combust/mleap#136]
I believe the documentation for mleap-serving could be updated ever so slightly to make it clear how to expose the model server locally.

`docker run -p 65327:65327 -v /tmp/models:/models combustml/mleap-serving:0.6.0-SNAPSHOT`

**Comment by hollinwilkins** [comment]
Great, we will update this documentation with the 0.6.0 release. Thank you for the suggestion!

**Comment by ancasarb** [comment]
Updated the documentation, will close this.
