### ISSUE TITLE
Investigate issue with storing large logistic regression coefficients > 1000

### ISSUE THREAD

**Issue by hollinwilkins** [combust/mleap#146]
1000 is the cutoff for storing tensors in a protobuf file for mixed mode serialization in mixed/protobuf serialization mode. There seems to be an issue with MLeap version:
a99dff6
0.5.0

Figure out if this issue is still a problem in MLeap 0.6.0 and fix it if it is.

Link to original discussion: https://github.com/combust/mleap/issues/135

**Comment by hollinwilkins** [comment]
@kaixinyan What version of scalapb is being included in your assembly? Our test cases cover storing large tensors as protobuf and there is no issue. That method value is defined here in scalapb runtime: https://github.com/scalapb/ScalaPB/blob/master/scalapb-runtime/shared/src/main/scala/com/trueaccord/scalapb/GeneratedMessageCompanion.scala

My suspicion at this point is that it is a dependency problem, but I am somewhat grasping at straws. I don't think it is an issue with MLeap directly, but I'm not sure.

**Comment by hollinwilkins** [comment]
I am going to close this for now. Let me know if you solved it or have more information!

**Comment by fifar** [comment]
@hollinwilkins Is 1000 still the cutoff for storing tensors in a protobuf file?

I use `Interaction` with two vectors of length 50 , the length (2500) of result vector exceeds the cutoff. And I got the same error, `java.lang.NoSuchMethodError: ml.bundle.BasicType.BasicType.value()I`. Is the cutoff cause of the error?
