### ISSUE TITLE
Some Spark transformers not supported

### ISSUE THREAD

**Issue by joyceqli** [combust/mleap#155]
When I try to serialize a org.apache.spark.ml.feature.Interaction to MLeap bundle, I got this error

Name: java.util.NoSuchElementException
Message: key not found: org.apache.spark.ml.feature.Interaction
StackTrace:   at scala.collection.MapLike$class.default(MapLike.scala:228)
  at scala.collection.AbstractMap.default(Map.scala:59)
  at scala.collection.MapLike$class.apply(MapLike.scala:141)
  at scala.collection.AbstractMap.apply(Map.scala:59)
  at ml.combust.bundle.BundleRegistry.opForObj(BundleRegistry.scala:100)

Same issue for CrossValidator, RFormula, SQLTransformer and RegexTokenizer. CrossValidator (LogisticRegressionCV) and Interaction are listed on [wiki](https://github.com/combust/mleap/wiki) while the other 3 are not listed.

**Comment by petro-rudenko** [comment]
`SQLTransformer` could be quite hard to implement for single row transformation. Thinking about it as well, how efficiently to do this.

**Comment by hollinwilkins** [comment]
@joyceqli 

I think the transformers there that we would support are:
1. RegexTokenizer
2. Interaction
3. CrossValidator
4. RFormula provided this doesn't require any large library dependencies

As for SQLTransformer, it is not row-based and as @petro-rudenko said, it would be quite difficult to implement in MLeap. In general we do not have planned support for transformers like this that operate on entire data frames.

I will break this ticket up into separate tickets for each of the transformers listed here. Thank you for the findings!

**Comment by joyceqli** [comment]
one more: TrainValidationSplitModel

**Comment by hollinwilkins** [comment]
Broke this issue into five separate tickets:
1. RegexTokenizer: https://github.com/combust/mleap/issues/189
2. Interaction: https://github.com/combust/mleap/issues/190
3. RFormula: https://github.com/combust/mleap/issues/191
4. CrossValidationModel: https://github.com/combust/mleap/issues/192
5. TrainValidationSplitModel: https://github.com/combust/mleap/issues/193

I am unsure if we really want to implement the last two, as they are primarily meant as a tool during training to tune hyper parameters.
