### ISSUE TITLE
Revisit MLeap serialization before releasing 1.0.0

### ISSUE THREAD

**Issue by hollinwilkins** [combust/mleap#160]
# Bundle ML Serialization Format

Bundle ML is the common serialization format used by MLeap to
export/import models with Spark, Scikit-learn, Tensorflow and of course
the MLeap runtime. It has been successful at making ML pipelines
portable by using only commonly-available data structures in the format.
The dependencies of Bundle ML are quite simple: ZIP files, JSON,
Protobuf 3. However, there are several issues with Bundle ML that are
holding it back:

1. Lack of formalized specification
2. Inconsistency by allowing models to store data outside of
   well-defined data structures
3. Oddities with serializing tensors
4. Arrays (arrays of arrays and nomenclature)
5. Mixed mode serialization is a good idea, but implementation is
   awkward
6. Custom types
7. Other minor restructuring

I wish to explain these issues and propose a set of changes to be made
before the 1.0.0 release of MLeap, when we want to start guaranteeing
backwards compatibility as much as possible.

## Lack of Formalized Specification

Currently the only way to know how to serialize/deserialize Bundle ML is
to look at the Scala implementation and the Protobuf files. There is no
formal document outlining the data structures used and how files are
structured. This lack of a specification is even worse because we allow
models to store any data they wish to in addition to the predefined
model and node data.

A formalized specification for Bundle ML needs to define a strict set of
possibilities and get rid of the current ability to produce arbitrary
serialization code by the implementor. The specification should include
directories/files as well as Protobuf/JSON object specifications and how
they are structured. In addition, it should specify the minimum set of
file systems that are required for a "complete" implementation of the
spec. Specifications for all of the core transformers are needed,
including the necessary attributes for the model and socket ports for
the node.

The specification should include a way to uniquely identify nodes,
models and attributes within a Bundle using URIs.

This formalized specification should also include serializing LeapFrames to JSON and a Protobuf-based serialization format.

## Inconsistent (Custom) Model Data

Decision trees are the big offender here, as they
store their tree nodes in a separate file from the `model` file in a
format completely outside of the standard data structures meant to be
used by Bundle ML. A more canonical way to store this data would be
perhaps as a ByteString of serialized data in the model, so that an
additional file would not be necessary.

If we want to allow arbitrary files like this to store data, we should
do so in a consistent manner. For instance, we could make it so that
attributes can be offloaded to a separate file when they are too large
to store comfortably in JSON. The key thing here is that the new file
containing the attribute should contain a well-defined data type, like a
byte string in the case of decision trees, not some arbitrary file data
that the model has to custom save/load. This is very important, as right
now we require passing the BundleContext when saving/loading model data
just so the model can process there arbitrary files.

Other offenders in this same space are models like OneVsRest and
RandomForest, which themselves contain a set of models that they
execute. Because there is no way to store another model inside of a
model, custom file processing is required in the OpModel implementation
that uses the BundleContext for file handling.

In order to solve this issue, we should make sure that ALL data is
stored in a `Model` object. In order to facilitate models that contain
other models, we should introduce a new attribute type for storing a
`Model`. This attribute could always be offloaded to a separate file for
clarity, the point is that the implementor of the serialization code
doesn't have to worry about this detail, they just have to return the
`Model` object.

## Serializing Tensors

My only qualm with serializing Tensors right now is the strange format
of the data type, which is an artifact from when we used to store the
dimensions along with the base type. Currently Tensors are stored as an
attribute like this:

Linear Regression Coefficients Tensor
```
{
  "op": "linear_regression",
  "attributes": {
    "coefficients": {
      "type": {
        "type": "tensor",
        "tensor": {
          "base": "double"
        }
      },
      "value": {
        "values": [...],
        "dimensions": [27]
      }
    },
    "intercept": {
      "type": "double",
      "value": -93.4700528667358
    }
  }
}
```

Instead, it would be more concise to store it like this:

Proposed Format
```
{
  "op": "linear_regression",
  "attributes": {
    "coefficients": {
      "type": "tensor",
      "base": "double"
      "value": {
        "values": [...],
        "dimensions": [27]
      }
    },
    "intercept": {
      "type": "double",
      "value": -93.4700528667358
    }
  }
}

```

## Arrays

Arrays of data can be referred to in the MLeap codebase as `Array`,
`List` or `Seq` at times. We should decide on one and stick to it. I
propose sticking to one name: `Array`. `List` implies a linked list and
`Seq` is fairly unique to Scala. Array is universally understood and
reflects the actual underlying storage of the data.

The current Scala implementation allows for Arrays of Arrays of Arrays
of... We should get rid of this capability, as it is unecessary (we have
n-dimensional tensors) and difficult to implement in statically-types
languages.

The type serialization for arrays is also somewhat strange, and should be changed
to fit inline with the proposed tensor format change.

Current Array Format
```
{
  "op": "string_indexer",
  "attributes": {
    "labels": {
      "type": {
        "type": "list",
        "base": "string"
      },
      "value": ["hey", "there"]
    }
  }
}
```

Proposed Array Format
```
{
  "op": "string_indexer",
  "attributes": {
    "labels": {
      "type": "list",
      "base": "string"
      "value": ["hey", "there"]
    }
  }
}
```

## Mixed Mode Serialization

Mixed mode serialization should be taken away. It gets in the way of
being able to produce predictable, simple rules for serialization. It
also gets in the way of being able to easily produce a URI specification
for accessing Bundle ML elements.

## Other

All of the protobuf messages used by Bundle ML are in separate files,
which makes code generation awkward and accessing the generated objects
more difficult than it should be. We should place all of the messages in
one file that is easy to compile and use.

**Comment by hollinwilkins** [comment]
# Bundle ML Serialization Format

Bundle ML is the common serialization format used by MLeap to
export/import models with Spark, Scikit-learn, Tensorflow and of course
the MLeap runtime. It has been successful at making ML pipelines
portable by using only commonly-available data structures in the format.
The dependencies of Bundle ML are quite simple: ZIP files, JSON,
Protobuf 3. However, there are several issues with Bundle ML that are
holding it back:

1. Lack of formalized specification
2. Inconsistency by allowing models to store data outside of
   well-defined data structures
3. Oddities with serializing tensors
4. Arrays (arrays of arrays and nomenclature)
5. Mixed mode serialization is a good idea, but implementation is
   awkward
6. Custom types
7. Other minor restructuring

I wish to explain these issues and propose a set of changes to be made
before the 1.0.0 release of MLeap, when we want to start guaranteeing
backwards compatibility as much as possible.

## Lack of Formalized Specification

Currently the only way to know how to serialize/deserialize Bundle ML is
to look at the Scala implementation and the Protobuf files. There is no
formal document outlining the data structures used and how files are
structured. This lack of a specification is even worse because we allow
models to store any data they wish to in addition to the predefined
model and node data.

A formalized specification for Bundle ML needs to define a strict set of
possibilities and get rid of the current ability to produce arbitrary
serialization code by the implementor. The specification should include
directories/files as well as Protobuf/JSON object specifications and how
they are structured. In addition, it should specify the minimum set of
file systems that are required for a "complete" implementation of the
spec. Specifications for all of the core transformers are needed,
including the necessary attributes for the model and socket ports for
the node.

The specification should include a way to uniquely identify nodes,
models and attributes within a Bundle using URIs.

## Inconsistent (Custom) Model Data

Decision trees are the big offender here, as they
store their tree nodes in a separate file from the `model` file in a
format completely outside of the standard data structures meant to be
used by Bundle ML. A more canonical way to store this data would be
perhaps as a ByteString of serialized data in the model, so that an
additional file would not be necessary.

If we want to allow arbitrary files like this to store data, we should
do so in a consistent manner. For instance, we could make it so that
attributes can be offloaded to a separate file when they are too large
to store comfortably in JSON. The key thing here is that the new file
containing the attribute should contain a well-defined data type, like a
byte string in the case of decision trees, not some arbitrary file data
that the model has to custom save/load. This is very important, as right
now we require passing the BundleContext when saving/loading model data
just so the model can process there arbitrary files.

Other offenders in this same space are models like OneVsRest and
RandomForest, which themselves contain a set of models that they
execute. Because there is no way to store another model inside of a
model, custom file processing is required in the OpModel implementation
that uses the BundleContext for file handling.

In order to solve this issue, we should make sure that ALL data is
stored in a `Model` object. In order to facilitate models that contain
other models, we should introduce a new attribute type for storing a
`Model`. This attribute could always be offloaded to a separate file for
clarity, the point is that the implementor of the serialization code
doesn't have to worry about this detail, they just have to return the
`Model` object.

## Serializing Tensors

My only qualm with serializing Tensors right now is the strange format
of the data type, which is an artifact from when we used to store the
dimensions along with the base type. Currently Tensors are stored as an
attribute like this:

Linear Regression Coefficients Tensor
```
{
  "op": "linear_regression",
  "attributes": {
    "coefficients": {
      "type": {
        "type": "tensor",
        "tensor": {
          "base": "double"
        }
      },
      "value": {
        "values": [...],
        "dimensions": [27]
      }
    },
    "intercept": {
      "type": "double",
      "value": -93.4700528667358
    }
  }
}
```

Instead, it would be more concise to store it like this:

Proposed Format
```
{
  "op": "linear_regression",
  "attributes": {
    "coefficients": {
      "type": "tensor",
      "base": "double"
      "value": {
        "values": [...],
        "dimensions": [27]
      }
    },
    "intercept": {
      "type": "double",
      "value": -93.4700528667358
    }
  }
}

```

## Arrays

Arrays of data can be referred to in the MLeap codebase as `Array`,
`List` or `Seq` at times. We should decide on one and stick to it. I
propose sticking to one name: `Array`. `List` implies a linked list and
`Seq` is fairly unique to Scala. Array is universally understood and
reflects the actual underlying storage of the data.

The current Scala implementation allows for Arrays of Arrays of Arrays
of... We should get rid of this capability, as it is unecessary (we have
n-dimensional tensors) and difficult to implement in statically-types
languages.

The type serialization for arrays is also somewhat strange, and should be changed
to fit inline with the proposed tensor format change.

Current Array Format
```
{
  "op": "string_indexer",
  "attributes": {
    "labels": {
      "type": {
        "type": "list",
        "base": "string"
      },
      "value": ["hey", "there"]
    }
  }
}
```

Proposed Array Format
```
{
  "op": "string_indexer",
  "attributes": {
    "labels": {
      "type": "list",
      "base": "string"
      "value": ["hey", "there"]
    }
  }
}
```

## Mixed Mode Serialization

Mixed mode serialization should be taken away. It gets in the way of
being able to produce predictable, simple rules for serialization. It
also gets in the way of being able to easily produce a URI specification
for accessing Bundle ML elements.

## Other

All of the protobuf messages used by Bundle ML are in separate files,
which makes code generation awkward and accessing the generated objects
more difficult than it should be. We should place all of the messages in
one file that is easy to compile and use.

**Comment by ghisvail** [comment]
Could standardization efforts like [ONNX](http://onnx.ai/) or [NNEF](https://www.khronos.org/nnef) be something of interest here?

**Comment by hollinwilkins** [comment]
@ghisvail Absolutely. Currently the only deep learning support we have is through Tensorflow. Would be great to allow all of these frameworks to execute with MLeap.

**Comment by hollinwilkins** [comment]
Closing this issue as the serialization format has been stable since 0.8.0
