### ISSUE TITLE
Class not found error when using spark-submit from command line

### ISSUE THREAD

**Issue by EvanzzzZ** [combust/mleap#163]
Writing a simple example Spark program, turn a ML pipeline into a Bundle file.
Using sbt for project management, adding dependencies in the build.sbt file.

After successfully build the package by `sbt package`, when I run the spark program using `spark-submit`, it run into the error as this:
`Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/spark/ml/mleap/SparkUtil$`.

Doing the exact same thing in IntelliJ (create a sbt IntelliJ project using the same files)don't have this problem.

Any idea about why this happen?

**Comment by hollinwilkins** [comment]
How are you running spark submit? Do you make an assembly jar first then submit or include the MLeap dependencies some other way?

**Comment by EvanzzzZ** [comment]
I run `sbt package` first to generate the jar file, which should include all the dependencies. And then submit the jar file to spark by` spark-submit`. The program runs well on the dependency on spark.mlib.

**Comment by hollinwilkins** [comment]
@EvanzzzZ You need to generate an assembly using this plugin: https://github.com/sbt/sbt-assembly

Or include all your dependencies as Spark packages.

`sbt package` by default will only place the code you write code into the jar it generates.

**Comment by EvanzzzZ** [comment]
I see, thanks for helping this.

**Comment by hollinwilkins** [comment]
@EvanzzzZ I am closing this issue for now. Let me know if the above did not solve this for you.
