### ISSUE TITLE
setNames(...) does not take effect for Spark VectorSlicer

### ISSUE THREAD

**Issue by joyceqli** [combust/mleap#166]
Tested with this Spark example code for VectorSlicer:
```
    val data = Arrays.asList(
      Row(Vectors.sparse(3, Seq((0, -2.0), (1, 2.3)))),
      Row(Vectors.dense(-2.0, 2.3, 0.0))
    )

    val defaultAttr = NumericAttribute.defaultAttr
    val attrs = Array("f1", "f2", "f3").map(defaultAttr.withName)
    val attrGroup = new AttributeGroup("userFeatures", attrs.asInstanceOf[Array[Attribute]])

    val dataset = spark.createDataFrame(data, StructType(Array(attrGroup.toStructField())))

    val slicer = new VectorSlicer().setInputCol("userFeatures").setOutputCol("features")
slicer.setIndices(Array(1)).setNames(Array("f3"))
```
Mleap transform result only has [2.0], while it should  be [2.0, 1.0] where 1.0 is for column f3.

Cause is that in VectorSlicerOp, only obj.indices are persisted/loaded but not obj.names. Also the names are not handled in MLeap VectorSlicerModel.

**Comment by hollinwilkins** [comment]
Looks like we will be requiring metadata about the dataframe if someone wants to use names. The MLeap model will store just the indices, when serializing the model, if the user sets the names field, MLeap will check with the dataframe meta data to determine the index of the element.

**Comment by hollinwilkins** [comment]
An issue with this is that we need to know the column name of the VectorSlicer in order to create the model, but the model is supposed to be independent of the transformer itself. Let's come back to this one.
