### ISSUE TITLE
[Question] How to convert a Spark Dataframe into a LeapFrame?

### ISSUE THREAD

**Issue by manugarri** [combust/mleap#170]
In order to use mleap server, I need to know the structure of the leapframes in json format. To do so, I think the safest way would be to load a sample Spark DataFrame (with a predefined schema), then convert it into a LeapFrame. 

I cant seem to find how to do this in the docs, is it a possibility? If not I guess the alternative is to handcraft the schema in the json leapframe?

Thanks!

**Comment by hollinwilkins** [comment]
@manugarri Hey, there is currently no way to convert a Spark DataFrame to a LeapFrame, though building this mechanism should be fairly straightforward. We already have the DataType converters between Spark and MLeap.

**Comment by manugarri** [comment]
oh i see. How could one perform such conversion? The reason I need it is because I dont know the schema syntax of the json leapframe (the example you show in the docs is very simple, and my datasets have a much more complex spark schema).

**Comment by hollinwilkins** [comment]
@manugarri I'll include a sample from our JSON test output here that gets a little more advanced. What is in your data frame that makes it complex?

```
{
  "schema": {
    "fields": [{
      "name": "features",
      "type": {
        "type": "tensor",
        "base": "double"
      }
    }, {
      "name": "name",
      "type": "string"
    }, {
      "name": "list_data",
      "type": {
        "type": "list",
        "base": "string"
      }
    }, {
      "name": "nullable_double",
      "type": {
        "type": "basic",
        "base": "double",
        "isNullable": true
      }
    }, {
      "name": "float",
      "type": "float"
    }, {
      "name": "byte_tensor",
      "type": {
        "type": "tensor",
        "base": "byte"
      }
    }, {
      "name": "short_list",
      "type": {
        "type": "list",
        "base": "short"
      }
    }, {
      "name": "byte_string",
      "type": "byte_string"
    }, {
      "name": "nullable_string",
      "type": {
        "type": "basic",
        "base": "string",
        "isNullable": true
      }
    }, {
      "name": "custom_object",
      "type": {
        "type": "custom",
        "custom": "my_custom_object"
      }
    }]
  },
  "rows": [[{
    "values": [20.0, 10.0, 5.0],
    "dimensions": [3]
  }, "hello", ["hello", "there"], 56.7, 32.400001525878906, {
    "values": [1, 2, 3, 4],
    "dimensions": [4]
  }, [99, 12, 45], "IAQ3Qw==", null, {
    "name": "hello"
  }]]
}
```

**Comment by manugarri** [comment]
@hollinwilkins that is neat. I mean my schema is complex because is a very nested json schema. That example you provided is definitely better to figure out how to implement mine, but afaik, there is no documentation on the specific dsl required to define the leapframes schema (for example, what does `base: byte` or `type: tensor` mean?). 

Thats why I wanted to create a leapframe from a dataframe (i assume it involves lots of reflection) and print the leapframe schema and save it as a template.

**Comment by hollinwilkins** [comment]
@manugarri It shouldn't involve reflection. A Spark DataFrame has concrete objects that inherit DataType that define the data. Likewise, LeapFrames has objects that inherit from the MLeap DataType. You would need to convert Schema/Data from Spark to MLeap, which will (mostly) be straightforward. Tensors/Arrays will be slightly tricky.

We already have a converter from MLeap to Spark: https://github.com/combust/mleap/blob/master/mleap-spark-base/src/main/scala/org/apache/spark/sql/mleap/TypeConverters.scala

We don't yet have a converter from Spark to MLeap, but I imagine it would look very similar to the above function. In addition to this, we would have to convert from Spark Vectors/Matrices to MLeap Tensors, and Spark ArrayWrappers to Seqs for Array data.

Not all Spark data representations are supported in MLeap, I am specifically talking about StructType, which is not supported by MLeap.

If you are looking for a more general definition of LeapFrames, there is nothing official, though I would like to formalize it eventually. You can look at the code to get a good idea of how it works for now: https://github.com/combust/mleap/blob/master/mleap-runtime/src/main/scala/ml/combust/mleap/json/JsonSupport.scala
and
https://github.com/combust/mleap/blob/master/mleap-runtime/src/main/scala/ml/combust/mleap/json/DatasetFormat.scala

**Comment by manugarri** [comment]
I see. Do you know where I could see all the available options in terms of schemas? I think that is not documented, but maybe you can point me to the specific code that does the parsing of the schema string.

 BTW, If you dont support StructType in Spark, does that mean that regular hash maps /dicts are not supported in the leapframe?

**Comment by ancasarb** [comment]
@hollinwilkins @manugarri 

not entirely sure if this would help, but could another option be creating a case class (product class) that describes the spark dataframe and using the .toLeapFrame() implicit converter to create the mleap frame from that?

 https://github.com/combust/mleap/blob/c522a9dd6d701d44871c85562371eda3e0dfda19/mleap-runtime/src/main/scala/ml/combust/mleap/runtime/MleapSupport.scala#L28

an example in the spec test here

https://github.com/combust/mleap/blob/c522a9dd6d701d44871c85562371eda3e0dfda19/mleap-runtime/src/test/scala/ml/combust/mleap/runtime/converter/LeapFrameConverterSpec.scala#L33

**Comment by manugarri** [comment]
@ancasarb not sure how it would work (once again i am not knowledgeable by all means regarding the repo), but wouldnt that mean having to create a class (like [here](https://github.com/combust/mleap/blob/c522a9dd6d701d44871c85562371eda3e0dfda19/mleap-runtime/src/test/scala/ml/combust/mleap/runtime/converter/LeapFrameConverterSpec.scala#L52) for every different dataframe schema?).

I would just like to see how i can translate a spark schema (which on its json representation, looks awfully similar to leapframe json schema) to a leapframe json schema.


So for example, if my schema in spark looks like:

```
{"fields":[
    {"metadata":{},"name":"opp_id","nullable":false,"type":"string"},
    {"metadata":{},"name":"id","nullable":true,"type":"string"},
    {"metadata":{},"name":"date","nullable":true,"type":"long"},
    {"metadata":{},"name":"app","nullable":true,"type":{"keyType":"string","type":"map","valueContainsNull":true,"valueType":"string"}},
    {"metadata": {},"name": "device",
     "nullable": true,
     "type": {"fields": [
       {"metadata": {},
         "name": "geo",
         "nullable": true,
         "type": {"keyType": "string",
         "type": "map",
         "valueContainsNull": true,
         "valueType": "string"}},
       {"metadata": {}, "name": "ip", "nullable": true, "type": "string"},
       {"metadata": {}, "name": "os", "nullable": true, "type": "string"},
       {"metadata": {}, "name": "osv", "nullable": true, "type": "string"},
       {"metadata": {}, "name": "make", "nullable": true, "type": "string"},
       {"metadata": {}, "name": "model", "nullable": true, "type": "string"},
       {"metadata": {}, "name": "carrier", "nullable": true, "type": "string"},
...
}
```

How would one translate that into something like 
```
"schema": {
    "fields": [{
      "name": "features",
      "type": {
        "type": "tensor",
        "base": "double"
      }
    }, {
      "name": "name",
      "type": "string"
    }, {
      "name": "list_data",
      "type": {
        "type": "list",
        "base": "string"
      }
    }, {
      "name": "nullable_double",
      "type": {
        "type": "basic",
        "base": "double",
        "isNullable": true
      }
    }, {
      "name": "float",
      "type": "float"
    }, {
      "name": "byte_tensor",
      "type": {
        "type": "tensor",
        "base": "byte"
      }
    }, {
      "name": "short_list",
      "type": {
        "type": "list",
        "base": "short"
      }
    }, {
      "name": "byte_string",
      "type": "byte_string"
    }, {
      "name": "nullable_string",
      "type": {
        "type": "basic",
        "base": "string",
        "isNullable": true
      }
    }, {
      "name": "custom_object",
      "type": {
        "type": "custom",
        "custom": "my_custom_object"
      }
    }]
  }
```

which is what @hollinwilkins shared? It does not have to be automatic, but we would need to know how the leapframe equivalent terms are.

**Comment by hollinwilkins** [comment]
@manugarri Hey, MLeap doesn't support a Map[K, V] type being stored in the LeapFrame. This is because we haven't found any transformers in Spark that require this so far. Are you writing custom transformers that use a map?

If you really want to add a map and be able to serialize it, you will have to make a custom type for it.

**Comment by manugarri** [comment]
@hollinwilkins that is true, the spark pipelines dont support maps. I was just sharing the example of the original dataframe prior to the pipeline transform call. The point I was trying to make is, i have no idea how those string, double, nullable, array, etcetera are defined in the leapframe schema definition dsl.

**Comment by hollinwilkins** [comment]
@manugarri I see. Yeah, we don't have a good "written" spec right now. It's just in code unfortunately. I'm going to add this as a task to another ticket: https://github.com/combust/mleap/issues/160

In that ticket there is a section on formalizing the MLeap serialization format. It originally included only the model serialization, but I added a note that we should formalize the LeapFrame serialization as well. What I mean by formalize is to create a set of JSON schemas for the JSON serialization along with a document to describe the JSON serialization. In addition, I want to formalize the LeapFrame binary serialization with a document as well.

**Comment by hollinwilkins** [comment]
@manugarri Also let me know if you would like help investigating this further. I've pointed to the code resources and everything, but there is still a lot that is unclear probably.

**Comment by ancasarb** [comment]
@manugarri I see what you mean. yes, you're right, you'd still need the case class so this idea won't be of much help, sorry about that!

**Comment by manugarri** [comment]
@hollinwilkins i would like to, maybe you can point me to the specific files where the available datatypes are defined? I assume somewhere there is a map from the json to the mleap structures.

**Comment by hollinwilkins** [comment]
Hey @manugarri All of the JSON support stuff is in these two files for serializing LeapFrames:

https://github.com/combust/mleap/blob/master/mleap-runtime/src/main/scala/ml/combust/mleap/json/JsonSupport.scala
and
https://github.com/combust/mleap/blob/master/mleap-runtime/src/main/scala/ml/combust/mleap/json/DatasetFormat.scala

**Comment by manugarri** [comment]
Oh nice! Thanks so much. Ideally this would be implemented in the future, but I think i can reverse engineer the schema as of now. Ill close the issue.

**Comment by MeiSign** [comment]
I think it is worth to note that there are helper methods now to convert from Spark Dataframe to Mleap StructType. This is a common usecase for testing purposes and this issue is one of the first hits by google if you search for spark to mleap dataframe conversion. 

https://github.com/combust/mleap/blob/master/mleap-spark-base/src/main/scala/org/apache/spark/sql/mleap/TypeConverters.scala#L86

**Comment by PowerToThePeople111** [comment]
I tried to convert a dataframe created in spark to one that can be used in Mleap and persist it. Using `TypeConverters.sparkSchemaToMleapSchema()` does not work tho. 

An example:
```

import ml.combust.mleap.tensor.{ByteString, Tensor}
import ml.combust.mleap.core.types._

case class Test(aList: Seq[Int])
val data = Seq(Test(Seq(1, 2)), Test(Seq(3)))
val sparkDF = sqlc.createDataset(data).toDF
val mleapSchema = org.apache.spark.sql.mleap.TypeConverters.sparkSchemaToMleapSchema(sparkDF)
//val mleapSchema = StructType(StructField("aList", TensorType(BasicType.Int))).get

val mleapRows = sparkDF.rdd.collect.map{ x => 
  ml.combust.mleap.runtime.frame.Row(
            //seq
            Tensor.denseVector(Array[Int](x.getAs[Seq[Int]](0): _*)) 
          )
}.toSeq

val mleapFrame = DefaultLeapFrame(mleapSchema, mleapRows)

//store it
val bos = new BufferedOutputStream(new FileOutputStream("/tmp/mleap-schema.json"))
val data = mleapFrame.writer("ml.combust.mleap.json").toBytes().get
bos.write(data)
bos.close()
```

Leads to:
```
java.lang.ClassCastException: ml.combust.mleap.tensor.DenseTensor cannot be cast to scala.collection.Iterable
  at spray.json.CollectionFormats$$anon$4.write(CollectionFormats.scala:86)
  at spray.json.PimpedAny.toJson(package.scala:39)
  at spray.json.StandardFormats$OptionFormat.write(StandardFormats.scala:34)
  at spray.json.StandardFormats$OptionFormat.write(StandardFormats.scala:32)
  at ml.combust.mleap.json.RowFormat$$anonfun$3.apply(RowFormat.scala:78)
```

Ersetze ich die Schemadefinition allerdings durch:
`val mleapSchema = StructType(StructField("aList", TensorType(BasicType.Int))).get`

... dann funktioniert alles. Vielleicht benutze ich es ja auch nicht richtig. Wenn doch, ists wohl ein Bug.

**Comment by PowerToThePeople111** [comment]
As an addition to MeiSign's post: this code snippet converts a special kind of dataframe (containing List types). 
```
val loadedData = sqlc.read.json("s3a://emr-datascience-adjoe-sandbox/age-prediction/feature-generation/additional_app_info_to_join")
    //create mleap frame
    val schema = org.apache.spark.sql.mleap.TypeConverters.sparkSchemaToMleapSchema(loadedData)

  val transformedData = loadedData
    .collect
    .map { sparkRow: org.apache.spark.sql.Row =>
      ml.combust.mleap.runtime.frame.Row(
        sparkRow.getString(0), sparkRow.getString(1), sparkRow.getString(2), Seq[String](sparkRow.getAs[Seq[String]](3): _*), sparkRow.getString(4) , sparkRow.getLong(5)
      )
    }

    val mleapFrame = DefaultLeapFrame(schema, transformedData)
```


If you only use basic data, you can actually just do: 
```
val loadedData = sqlc.read.json("s3a://emr-datascience-adjoe-sandbox/age-prediction/feature-generation/additional_app_info_to_join")
    //create mleap frame
    val schema = org.apache.spark.sql.mleap.TypeConverters.sparkSchemaToMleapSchema(loadedData)

  val transformedData = loadedData
    .collect
    .map { sparkRow: org.apache.spark.sql.Row =>
      ml.combust.mleap.runtime.frame.Row(org.apache.spark.sql.Row.unapplySeq(sparkRow).get)
    }

    val mleapFrame = DefaultLeapFrame(schema, transformedData)
```
