### ISSUE TITLE
Using mleap-benchmark and got strange error of JSON parsing

### ISSUE THREAD

**Issue by yijiezz** [combust/mleap#179]
The model and the JSON file works well when I setup the server and send the request.
I tried to use leap-benchmark with the same model and JSON input to see the performance but got errors.

Here is the error:
`Unexpected character 'a' at input index 32346 (line 1, position 32347), expected end-of-input`
This position is the end of the JSON file, where there is not an 'a' in my file.  But somehow the parser require there should be an EOI at the end of file.

Any idea about what might happen here?

**Comment by EvanzzzZ** [comment]
Using Spray to directly parse my JSON file and work well. The problem may lie in something Mleap did over the JSON file.

**Comment by hollinwilkins** [comment]
@EvanzzzZ Were you able to figure anything more out? I am not seeing any errors when running this using the following command:

```
sbt "mleap-benchmark/run mleap-transform --model-path ./mleap-benchmark/src/main/resources/models/airbnb.model.rf.zip --frame-path ./mleap-benchmark/src/main/resources/leap_frame/frame.airbnb.json"
```

**Comment by EvanzzzZ** [comment]
Yes, using the given JSON file is totally fine. It's just the JSON file that I used. The JSON file can use for scoring as input to the server, so I assume it's in correct format. Or you can try the MNIST file provided in your tutorial.

**Comment by hollinwilkins** [comment]
@EvanzzzZ Do you mind sharing the file with us via email? hollin at combust.ml

**Comment by EvanzzzZ** [comment]
You can try the mnist.json file provided in your tutorial. That's what I am using.

**Comment by hollinwilkins** [comment]
@EvanzzzZ Sorry I haven't had a chance to look at this further. Will be taking a look at it today.

**Comment by lgongms** [comment]
Any finding for this issue?  I ran into the same problem.  The json file that I used is attached.  Thanks!
[adult_census_leapframe.txt](https://github.com/combust/mleap/files/2010805/adult_census_leapframe.txt)

**Comment by ancasarb** [comment]
@lgongms @yijiezz @hollinwilkins this issue should be fixed by https://github.com/combust/mleap/pull/524.

**Comment by ancasarb** [comment]
Closing, PR has been merged.
