### ISSUE TITLE
Transformation on larger Leapframe

### ISSUE THREAD

**Issue by EvanzzzZ** [combust/mleap#204]
Does Mleap automatically parallelize a transformation on a leapframe that contains multiple row ?
Or it went through the rows in the leapframe one by one ?

**Comment by hollinwilkins** [comment]
@EvanzzzZ Currently MLeap does nothing to parallelize computations on large leap frames. This could provide a performance boost in a few scenarios:

1. Relatively few rows to transform with a long-running pipeline
2. A large number of rows with a short-running pipeline
3. A large number of rows with a long-running pipeline

Out of curiosity, what size leap frames are you trying to use? How long does your pipeline take to run? So far we have been leaving this task up to the application to parallelize as necessary.

**Comment by EvanzzzZ** [comment]
Does the pipeline itself provide some level of parallelism ? 

I am doing it with a 4 stage pipeline for 100 row and 10,000 row dataset.

Performance for 10,000 rows is almost linear.

**Comment by hollinwilkins** [comment]
@EvanzzzZ There is no parallelism inherent to pipelines. I think for your task, the best way to see what kind of performance gains there are to have would be to create multiple LeapFrames instead of one and offload them to worker threads to be executed.

**Comment by hollinwilkins** [comment]
Closing this issue in favor of row-based transformation and having the application developers provide a multithreaded execution framework for the row-base transformer for optimal throughput.
