### ISSUE TITLE
improve docs: creating custom mleap transformer

### ISSUE THREAD

**Issue by smaxwellstewart** [combust/mleap#218]
Hi Guys,

First off big thanks to such an amazing open source project!

Ok so I am trying to serialize a feature pipeline, as part of that feature pipeline I have some custom functionality (user agent parsing) that I need to be a part of the feature extraction pipeline.

I am trying to follow the docs on how to create a custom transformer but getting a little lost at the end when it comes to registering with the runtime etc.  Please be aware I am trying to make all this run from Databricks (hope you are familiar with this) and am relative beginner when it comes to all things Java ecosystems.

https://github.com/combust/mleap/wiki/Adding-an-MLeap-Spark-Transformer

Questions I have:

- Steps number 3 and 4 are unclear, this is where I stop understanding the docs. Do I need to do both these things? I think I maybe not understand something important?
- For step 5, how do I edit this reference.conf? Do I edit the [file](https://github.com/combust/mleap/blob/master/mleap-spark-extension/src/main/resources/reference.conf) in this repo and the repackage it as my own version of this lbrary and upload it as a jar and put it back on Databricks?

This is a simplified version of my feature pipeline. To be clear about my environment I am running this from Databricks.

```scala
import ml.combust.bundle.BundleFile
import ml.combust.bundle.serializer.SerializationFormat
import org.apache.spark.ml.feature.{StringIndexerModel, VectorAssembler}
import org.apache.spark.ml.UnaryTransformer
import org.apache.spark.ml.util.Identifiable
import org.apache.spark.ml.mleap.SparkUtil
import ml.combust.mleap.spark.SparkSupport._
import org.apache.spark.sql.types._
import resource._

// EXAMPLE OF MY CORE MODEL
case class UpperCaserModel() extends Serializable {

  def apply(str: String): String = {
    val strString = str.toString

    if(str != strString) {
      throw new IllegalArgumentException(s"invalid value: $str, must be a string")
    }

    str.toUpperCase
  }
}

// NEED HELP IMPLEMENTING ABOVE AS TRANSFORMER TO BE USED BELOW

// Create a sample pipeline that we will serialize
// And then deserialize using various formats
val stringIndexer = new StringIndexerModel(labels = Array("Hello, MLeap!", "Another row")).
  setInputCol("a_string").
  setOutputCol("a_string_index")

val upperCaser = new Upper()
  .setInputCol("a_string")
  .setOutputCol("a_string_upper")

val featureAssembler = new VectorAssembler().setInputCols(Array("a_string_index")).
  setOutputCol("features")

// create pipeline that will transform data
val pipeline = SparkUtil.createPipelineModel(Array(stringIndexer, upperCaser, featureAssembler))

// write to tmp storage
(for(bundle <- managed(BundleFile("jar:file:/tmp/simple-json.zip"))) yield {
  pipeline.writeBundle.format(SerializationFormat.Json).save(bundle).get
}).tried.get
```

The idea is I then ship this model which i then load into my docker container...

```bash
$ docker run -v /tmp/models:/models -p46971:65327 combustml/mleap-serving:0.7.0-SNAPSHOT
$ curl -XPUT -H "content-type: application/json" -d '{"path":"/models/model.zip"}' http://localhost:46971/model

# READY TO START GETTING PREDICTIONS!
```

**Comment by smaxwellstewart** [comment]
These are the classes I have (successfully?) implemented so far:

```scala
package custom

case class UpperCaserModel() extends Serializable {

  def apply(str: String): String = {
    val strString = str.toString

    if(str != strString) {
      throw new IllegalArgumentException(s"invalid value: $str, must be a string")
    }

    str.toUpperCase
  }
}
```

```scala
package custom.feature

import custom.UpperCaserModel
import ml.combust.mleap.runtime.function.UserDefinedFunction
import ml.combust.mleap.runtime.transformer.{FeatureTransformer, Transformer}

import scala.util.Try

case class UpperCaser(override val uid: String = Transformer.uniqueName("upper_caser"),
                         override val inputCol: String,
                         override val outputCol: String,
                         model: UpperCaserModel) extends FeatureTransformer {
  override val exec: UserDefinedFunction = (value: String) => model(value)
}
```

```scala
package custom.ops

import ml.combust.bundle.BundleContext
import ml.combust.bundle.dsl._
import ml.combust.bundle.op.{OpModel, OpNode}

import ml.combust.mleap.runtime.MleapContext
import ml.combust.mleap.runtime.transformer.feature.OneHotEncoder

import custom.UpperCaserModel
import custom.feature.UpperCaser


class UpperCaserOp extends OpNode[MleapContext, UpperCaser, UpperCaserModel] {
  override val Model: OpModel[MleapContext, UpperCaserModel] = new OpModel[MleapContext, UpperCaserModel] {
    override val klazz: Class[UpperCaserModel] = classOf[UpperCaserModel]

    override def opName: String = "upper_caser"

    override def store(model: Model, obj: UpperCaserModel)
                      (implicit context: BundleContext[MleapContext]): Model = model

    override def load(model: Model)
                     (implicit context: BundleContext[MleapContext]): UpperCaserModel = {
      UpperCaserModel()
    }
  }

  override val klazz: Class[UpperCaser] = classOf[UpperCaser]

  override def name(node: UpperCaser): String = node.uid

  override def model(node: UpperCaser): UpperCaserModel = node.model

  override def load(node: Node, model: UpperCaserModel)
                   (implicit context: BundleContext[MleapContext]): UpperCaser = {
    UpperCaser(uid = node.name,
      inputCol = node.shape.standardInput.name,
      outputCol = node.shape.standardOutput.name,
      model = model)
  }

  override def shape(node: UpperCaser): Shape = Shape().withStandardIO(node.inputCol, node.outputCol)
}
```

**Comment by smaxwellstewart** [comment]
Ok so I think the main thing I was missing is that, that doc is designed to show collaborators how they can add other transformers into the core MLeap repo. Right? So i essentially need to add support for my custom transformation? Just to note, this is a little misleading from what the mleap docs say.  It seem like custom spark transformations are supported as-is by the library... http://mleap-docs.combust.ml/spark/

**Comment by hollinwilkins** [comment]
@smaxwellstewart Hey, sorry you feel misled! Making custom transformers is the same process as we use for builtin transformers, but you are right. There are a few more steps in there that need to be taken to deploy them, namely we now have another 2 jars we need to deal with!

1. A jar with your custom mleap transformer
2. A jar with your custom Spark transformer

Right now there is now easy way to include these in mleap-serving. If I were to go about doing it, I would look at creating a new docker image based on the existing one and add my jar to the library path. This is something we will be looking into making easier shortly, as we will be needing it ourselves soon. In the meantime, I am happy to keep the discussion going here.

Best,
Hollin

**Comment by hollinwilkins** [comment]
@smaxwellstewart By the way, your implementations look very good so far. All I see left to do is this:

1. Implement the spark transformer and spark op
2. Figure out a way to package the different jars for your training jobs and production API service

I will be happy to help with either step, also, https://gitter.im/combust/mleap is a great place to have realtime discussions too :)
