### ISSUE TITLE
Save MLeap models on S3/HDFS

### ISSUE THREAD

**Issue by fifar** [combust/mleap#223]
All demos of MLeap save PipelineModels locally. When running spark jobs in cluster mode, it's hard to get the MLeap model. How to save MLeap models on S3/HDFS? Any suggestions will be greatly appreciated.

```
for(modelFile <- managed(BundleFile("jar:file:/tmp/simple-spark-pipeline.zip"))) {
 pipeline.writeBundle.
   // save our pipeline to a zip file
   // we can save a file to any supported java.nio.FileSystem
   save(modelFile)
}
```

**Comment by hollinwilkins** [comment]
@fifar We handle this usually by saving locally then uploading to S3/HDFS instead of trying to save directly there.

**Comment by psc0606** [comment]
Why close this isuee

**Comment by Alucardmini** [comment]
I meet this problem,too.
