### ISSUE TITLE
TensorflowTransformer doesn't comply to mleap.runtime.transformer.Transformer trait

### ISSUE THREAD

**Issue by jacobfoard** [combust/mleap#232]
The TensorflowTransformer doesn't have the getFields method implemented. 

Here's an initial take at an implementation, but I'm not too familiar with the code for Tensorflow.

```scala
override def getFields(): Try[Seq[StructField]] = {
    val inputFields: Seq[StructField] = inputs.indices.map(index => StructField(inputCols(index), AnyType()))
    val outputFields: Seq[StructField] = outputs.indices.map(index => StructField(outputCols(index), AnyType()))
    Success(inputFields ++ outputFields)
  }
```

**Comment by hollinwilkins** [comment]
@jacobfoard We store the input/output types on the TensorflowModel, you could use that to generate this response as well.

**Comment by hollinwilkins** [comment]
Fix is coming with this PR: https://github.com/combust/mleap/pull/267

**Comment by hollinwilkins** [comment]
This is now fixed, closing this issue.
