### ISSUE TITLE
libtensorflow version is out of date

### ISSUE THREAD

**Issue by jacobfoard** [combust/mleap#233]
The latest version of libtensorflow is `1.1.0` and `0.12.head` is no longer in maven. 

Once #232 is resolved this should be a simple fix.

**Comment by hollinwilkins** [comment]
Great, this will be a welcome improvement.

**Comment by hollinwilkins** [comment]
Closing this issue. MLeap is functional and tested with Tensorflow version 1.3 as of MLeap version 0.8.0.
