### ISSUE TITLE
Enhance GBTClassificationModel

### ISSUE THREAD

**Issue by mutyonok** [combust/mleap#234]
Spark 2.2 evolves GBT classification by allowing two new output columns: `raw prediction` and `probability`.
Per Spark docs: 
- raw predictions - confidence for each class (type - Vector)
- probability - probability of each class (type - Vector).

git diff is: `git diff branch-2.1..branch-2.2 mllib/src/main/scala/org/apache/spark/ml/classification/GBTClassifier.scala`

the plan is to adapt spark 2.2 changes to MLeap by:
- making GBTClassifierModel extend ProbabilisticClassificationModel
- introducing Loss functions with the only loss type `logistic`
- changing model (de-) serialization to accept new params: thresholds, rawPredictionCol, probailityCol.

Q:
1. since `GBTClassifier` will become much like `RandomForestClassifier` in terms of transformation and schema it may be good to introduce ProbabilisticClassifier (spark has it for example) 
2. why GBT classification model is named `GBTClassifierModel`? Should we use word `Classification` instead of `Classifier`? 

@hollinwilkins you can assign me to this issue since we have already started to work on that.

**Comment by xhook** [comment]
Link to the change in Spark 2.2: https://github.com/apache/spark/commit/fe409f31d966d99fcf57137581d1fb682c1c072a#diff-a4454c0bd7a6db1167b5e20e44a534ba

**Comment by hollinwilkins** [comment]
@mutyonok Hey, this would be a welcome change. We have a probabilitstic classification model that random forest classifiers and logistic regression currently inherit from.

Take a look here: https://github.com/combust/mleap/blob/master/mleap-core/src/main/scala/ml/combust/mleap/core/classification/ClassificationModel.scala#L45

As you make this change, try to keep backwards compatibility with Spark 2.0 and Spark 2.1. We have an example for how we do this with Logistic regression between 2.0 and 2.1 where Spark introduces multinomial logistic regression. What we did is create two versions of the op, one for 2.0 and one for 2.1, then we have two versions of the bundle registry as well. Here are the relevant files:

1. https://github.com/combust/mleap/blob/master/mleap-spark/src/main/scala/org/apache/spark/ml/bundle/ops/classification/LogisticRegressionOpV20.scala
2. https://github.com/combust/mleap/blob/master/mleap-spark/src/main/scala/org/apache/spark/ml/bundle/ops/classification/LogisticRegressionOpV21.scala
3. https://github.com/combust/mleap/blob/master/mleap-spark/src/main/resources/reference.conf#L11-L23

**Comment by mutyonok** [comment]
good news is:
1. GBT in spark 2.0 and 2.1 is identical
2. GBT in spark 2.2 works the same as in 2.1 when no thresholds are provided. So GBT is automatically backward compatible with prev versions of model (since there is no `thresholds` param)

**Comment by mutyonok** [comment]
@hollinwilkins tried to run MLeap on Spark 2.2.0-SNAPSHOT and run into a problem with updated breeze lib (it's a transitive dependency from Spark). 
breeze renamed `dist.Gaussian#icdf` method to `inverseCdf` (https://github.com/scalanlp/breeze/commit/9bfb318db658537b09fdcc9eb5ef5c7cb0aecc72)
 and `GeneralizedLinearRegressionModel` can't be compiled.

how do you suggest to fix the problem? shall we just replicate icdf function inside of that regression model?

**Comment by mutyonok** [comment]
https://github.com/combust/mleap/pull/236

**Comment by hollinwilkins** [comment]
@mutyonok I think ideally the MLeap runtime should be able to develop separately from the Spark integration, which may mean depending on Breeze directly instead of depending on MLlib local. This would allow us to keep mleap-spark in lockstep with Spark and develop the MLeap runtime separately. We'll have to get to this point eventually, otherwise problems like this will keep coming up.

**Comment by hollinwilkins** [comment]
@mutyonok I think for now, replicating the functionality may be a good stop gap, but let's consider moving away from mllib-local and depending directly on breeze after that. What are your thoughts on this?

**Comment by hollinwilkins** [comment]
The PR for this fix was merged in, closing!
