### ISSUE TITLE
MLeap should support skipping rows with StringIndexer

### ISSUE THREAD

**Issue by smaxwellstewart** [combust/mleap#240]
I am getting a 'key not found' error when serving using the docker 0.7 mleap serving image (would use newer version but the libraries needed for serializing are only available on Maven up to 0.7). Does MLeap ignore the `setHandleInvalid("skip")`?

Using Scala 2.11 and Spark 2.1.

Part of my pipeline:

```scala
...
 stages = stages :+ new StringIndexer()
                    .setInputCol(c)
                    .setOutputCol(c+"Index")
                    .setHandleInvalid("skip")`

...

 stages = stages :+ new OneHotEncoder() // Using the MLeap OneHotEncoder
                    .setInputCol(c)
                    .setOutputCol(c+"Vec")
```

Error when using string that isn't part of the training set.

`[ERROR] [07/14/2017 15:52:39.358] [MleapServing-akka.actor.default-dispatcher-15] [akka.actor.ActorSystemImpl(MleapServing)] Error during processing of request: 'key not found: blob.com'. Completing with 500 Internal Server Error response.`

**Comment by hollinwilkins** [comment]
@smaxwellstewart Hey,

The skip option in Spark will cause it to filter any null or invalid values out of the data frame. In the context of MLeap, because it is meant for real time predictions and operates on individual rows, a transformer can't filter out rows in a Leap Frame. This is why skip does not work like it does in Spark.

**Comment by smaxwellstewart** [comment]
huh! ok so what happens if someone sends a value that was not present during the training of the pipeline? I kinda just want it to set the value to 'NA' or something, but definitely not to error out.

**Comment by smaxwellstewart** [comment]
@hollinwilkins any idea how to make MLeap not error if it sees a key it hasnt seen before?

**Comment by hollinwilkins** [comment]
@smaxwellstewart I am not sure what else it should do. What would you expect it to do? Filter the row out?

**Comment by smaxwellstewart** [comment]
@hollinwilkins sorry i wan't clear before. yes i think filtering out that row would work nicely, just like in spark.

**Comment by calinrc** [comment]
I apologize to interfere in this defect but I consider that would be nice to have a filtering mechanism on MLeap. I have a similar problem with the one described by @smaxwellstewart and I was not able to find any way to filter records at transformer / model level that does not meet some specific criteria. 
In TransformBuilder would be nice to have a record filtering way. Also I suggest if is possible to have a mechanism to filter out intermediate columns. This might help on cleaning up some output data.

E.g. In a pipeline like inputColumns(A,B,C) StringIndexer(in:A)(out:D) -> VectorAssembler(in:B,C,D)(out:E)  -> StandardScaler(in:E)(out:F) maybe user wants to output only final result (F in our case) and not pollute the output with intermediate results. 

Currently I was not able to find a way to perform this.Is any?

**Comment by kjacques** [comment]
+1

**Comment by hollinwilkins** [comment]
@smaxwellstewart @calinrc @kjacques Hey,

I hear the need for filtering. I think this would be great as well. Currently MLeap works on individual rows, moving forward I would eventually like it to operate on entire LeapFrames so stuff like this is easier. In the meantime, adding a filter method to TransformBuilder would work well. We can reuse UDFs that return a BooleanType. Is there anyone that would like to work on this?

**Comment by smaxwellstewart** [comment]
Can give it a pop, bit newer to scala, but gotta get my hands dirty contributing sooner or later ;).

Will take a look at source code and let you know how manageable it looks.

**Comment by hollinwilkins** [comment]
@smaxwellstewart https://github.com/combust/mleap/pull/286

This issue paves the way for allowing MLeap to skip with StringIndexer. Once this PR gets merged in, I am going to quickly turn around a fix for the issue outlined here.

**Comment by hollinwilkins** [comment]
@smaxwellstewart https://github.com/combust/mleap/pull/289

Should be skipping rows shortly :)

**Comment by hollinwilkins** [comment]
Merge PR 289, closing this issue.

**Comment by rnandire** [comment]
@smaxwellstewart Which version has this fix ? Can we have this version available in maven repository ?

**Comment by hollinwilkins** [comment]
@rnandire It's available in Maven right now as a snapshot, version 0.9.0-SNAPSHOT

**Comment by rnandire** [comment]
@smaxwellstewart May I know when 0.9.0 will be released ?

**Comment by rnandire** [comment]
@smaxwellstewart  I am looking forward for this fix. Can you let us know likely release date for 0.9.0 ?
