### ISSUE TITLE
sklearn pipeline serializer uses wrong name for steps

### ISSUE THREAD

**Issue by tucak** [combust/mleap#241]
Consider the following example:
```
pipe = sklearn.pipeline.Pipeline([('foo', feature_extractor)])
````
In the model.json of this pipline the name of the feature extractor is `foo`, but the directory containing it will be `vector_assembler_UUID.node`. This will cause loading the bundle to fail.

To reproduce run this:
```
import sklearn.preprocessing
import mleap.sklearn.pipeline
import mleap.sklearn.preprocessing.data

feature_extractor = mleap.sklearn.preprocessing.data.FeatureExtractor(
        ['a'], 'b', ['c'])
pipe = sklearn.pipeline.Pipeline([('name', feature_extractor)])
pipe.mlinit()
pipe.serialize_to_bundle('/tmp/', 'pipe', True)
```
And then try to load it from somewhere or just manually inspect the directory structure and the content of `root/model.json`.

**Comment by hollinwilkins** [comment]
@seme0021 Has this issue been resolved?

**Comment by ancasarb** [comment]
@hollinwilkins yep, it's been merged to master.

**Comment by hollinwilkins** [comment]
Closing this issue!
