### ISSUE TITLE
Load Multiple Model and Execution simultaneously

### ISSUE THREAD

**Issue by Bond-OO7** [combust/mleap#245]
I have 2 queries :  
1) Is there any way to load multiple models and transform mleap frame over multiple models. Because right now, I can load any one model and transform a mleap frame over that model at a given moment.

Scenario would be: 
Loading two models :
 `curl -XPUT -H "content-type: application/json"   -d '{"path":"/models/airbnb.model.lr-0.6.0-SNAPSHOT.zip"}'   http://172.17.0.1:65327/model`
 `curl -XPUT -H "content-type: application/json"   -d '{"path":"/models/airbnb.model.rf-0.6.0-SNAPSHOT.zip"}'   http://172.17.0.1:65327/model`

Now try to transform leap frame over any model :
```
curl -v -XPOST -H "accept: application/json" \
  -H "content-type: application/json" \
  -d @/models/frame.airbnb.json \
  http://172.17.0.1:65327/transform
```
But i couldnt give any parameter while transforming mleap frame to select model.
Is there any provision to do so?

2) Can I transform the whole bunch of mleap frames (Eg. 100) in a single request?

Looking forward for your reply.

**Comment by ssimeonov** [comment]
I'm curious: do you need this for ensemble models?

**Comment by hollinwilkins** [comment]
@Bond-OO7 Sorry, I missed this comment. We are about to release 0.8.0 and for 0.9.0 we want to make major improvements to the model servers, including:

1. a gRPC interface
2. Loading multiple models at a time

We don't have plans to add in parallel execution into the core MLeap engine itself, but loading multiple models into the server should let your application do this.

**Comment by dvaldivia** [comment]
@hollinwilkins were the multiple models supports implemented? I don't see a reference to it.
 
Wouldn't just instanciating multiple bundles be enough to support multiple models?

**Comment by hollinwilkins** [comment]
@dvaldivia Absolutely, this is in reference to our model server though, which only supports one model at a time right now. Currently working on remedying this.

**Comment by ganeshkrishnan1** [comment]
Do we support loading multiple models now? Or is the easiest way loading multiple docker containers each with it's own model?

**Comment by ancasarb** [comment]
We've released the new model serving services with MLeap 0.13 earlier in the year, please let us know if you have any questions regarding that.
