### ISSUE TITLE
Get Predictions from Mleap transform

### ISSUE THREAD

**Issue by fatihtekin** [combust/mleap#247]
I would like to be able to get the prediction when I use classifier. How can I achieve this? Currently frameLr does not contain the probability but only the result.

    for(frame <- FrameReader("ml.combust.mleap.json").fromBytes(bytes);
        frameLr <- mleapTransformerGBT.transform(frame);
        frameLrSelect <- frameLr.select("result")) {
          println("Price LR: " + frameLrSelect.dataset(0).getDouble(0))
    }

**Comment by hollinwilkins** [comment]
@fatihtekin Until Spark 2.2.0, GBT did not support outputting the probabilities. With Spark 2.2.0, GBT is a probabilistic classifier and includes these outputs. MLeap 0.8.0 will bring Spark 2.2.0 support, so you should be able to get these shortly.

**Comment by fatihtekin** [comment]
is there any related ticket so that I can compile 0.8.0-SNAPSHOT myself?

**Comment by hollinwilkins** [comment]
@fatihtekin You should be able to access it form maven central. Will be releasing it shortly after the 2 outstanding PRs get merged in also.

**Comment by hollinwilkins** [comment]
@fatihtekin All of the changes required for this are in mleap 0.8.0 currently, closing this issue!
