### ISSUE TITLE
TfidfVectorizer Support

### ISSUE THREAD

**Issue by mslipper** [combust/mleap#258]
Hi all,

First: thanks for open-sourcing this project. Spectrum Labs has been using MLeap in production for several months now and thus far it's been a great experience.

I did notice that there's currently no support for scikit's TfidfVectorizer in MLeap. This makes it difficult for us to directly export our experimental scikit models into MLeap bundles. If it's simply a matter of needing someone to implement the transformer, I'd be happy to have take a crack at it. Would anyone here object to me doing that?

**Comment by seme0021** [comment]
@mslipper If you can give it a shot, that would be great.

Tagging @ancasarb here since she's done a lot of scikit work recently.

**Comment by mslipper** [comment]
Perfect. Will get started this weekend. Was thinking I'd build it by having the TfidfVectorizer's serializer output a `SimplekSerializer` structure similar to the one in `mleap/feature_union.py`. That structure would contain the TF and IDF stages since Spark (and the MLeap runtime as far as I know) separate the two. Does this sound reasonable? Let me know if you have other ideas or pointers.

**Comment by hollinwilkins** [comment]
@mslipper Checking in to see if you've been able to make progress here. Let us know how it's going!

**Comment by mslipper** [comment]
@hollinwilkins I'm working on it! Should have something by early next week. It's been a pretty hectic month for me.

**Comment by ancasarb** [comment]
This would be great to have!

**Comment by mslipper** [comment]
Alrighty, I opened a PR with my initial pass at this. Please let me know if there's anything you want changed - it's been a long time since I've worked on a production Python codebase so I'm sure that I missed some things.
