### ISSUE TITLE
How to serialize and deserialize transformers in java8

### ISSUE THREAD

**Issue by sheikirfan** [combust/mleap#266]
I am looking for java implementation of the below code with all the necessary imports:

## Serialization
```
val pipeline = SparkUtil.createPipelineModel(uid = "pipeline", Array(featureModel, rfModel))

val sbc = SparkBundleContext()
for(bf <- managed(BundleFile("jar:file:/tmp/mnist.model.rf.zip"))) {
        pipeline.writeBundle.save(bf)(sbc).get
      }

val bundle = (for(bundleFile <- managed(BundleFile("jar:file:/tmp/simple-spark-pipeline.zip"))) yield {
  bundleFile.loadMleapBundle().get
}).opt.get
```

## Deserialization
```
val model = (for(bf <- managed(BundleFile("jar:file:/tmp/simple-spark-pipeline.zip"))) yield {
      bf.loadMleapBundle().get.root
    }).tried.get
```

**Comment by ancasarb** [comment]
@sheikirfan Have a look at https://github.com/combust/mleap/blob/master/mleap-runtime/src/test/scala/ml/combust/mleap/runtime/javadsl/JavaDSLSpec.scala#L81, it should help to get you started.

**Comment by hollinwilkins** [comment]
Closing this issue.

**Comment by SoloBean** [comment]
@ancasarb The URL is 404...sad

**Comment by ancasarb** [comment]
@SoloBean apologies, we've actually converted that scala class to a java one to make sure that the API works fine in Java.

here's the updated link: https://github.com/combust/mleap/blob/master/mleap-runtime/src/test/scala/ml/combust/mleap/runtime/javadsl/JavaDSLSpec.java
