### ISSUE TITLE
ScalarType nullability is lost in JSON serialization round-trip

### ISSUE THREAD

**Issue by pidge** [combust/mleap#269]
Ran into this while testing schema serialization/deserialization. Here's a minimal failing test case:

```
import ml.combust.mleap.core.types.{DataType, ScalarType}
import org.scalatest.Assertions._
import ml.combust.mleap.json.JsonSupport._
import spray.json._

val before = ScalarType.String.nonNullable
val after = before.toJson.compactPrint.parseJson.convertTo[DataType]
assert(!after.isNullable)
```

I think the fix is just adding a `.setNullable(false)` to this line - https://github.com/combust/mleap/blob/185cdf4d7ddc1efbefc43ac6d9b7ce358fbf7574/mleap-runtime/src/main/scala/ml/combust/mleap/json/JsonSupport.scala#L141

**Comment by hollinwilkins** [comment]
@pidge https://github.com/combust/mleap/pull/271

Fixed this issue as well as other nullability issues with serializing/deserializing. Thank you for the find! Will release a 0.8.1 version with this fix soon.

**Comment by hollinwilkins** [comment]
Merged the PR for this, closing.
