### ISSUE TITLE
MaxAbsScalerModel incorrect values when case SparseVector

### ISSUE THREAD

**Issue by smorring** [combust/mleap#272]
The MaxAbsScalerModel gives a SparseVector with different results than the equivalent model in Spark.

I think there are two problems:
line 40 of MaxAbsScalerModel.scala:
`vs(i) *= raw`

To make it emulate Spark the line would need to be:
`vs(i) = raw`

Also, line 38 of MaxAbsScalerModel.scala
`val raw = max(-1.0, min(1.0, values(i) / maxAbsUnzero(i)))`

To emulate Spark the line needs to be:
`val raw = max(-1.0, min(1.0, values(i) / maxAbsUnzero(indices(i))))`

I would've just made the code change for your review, but I've never used Git before.

**Comment by hollinwilkins** [comment]
PR here: https://github.com/combust/mleap/pull/273

Thanks for finding this bug!

**Comment by hollinwilkins** [comment]
@smorring Would you care to make a PR for review? Would be happy to help with any git knowledge you would need.

**Comment by smorring** [comment]
I'd certainly love to contribute in some way.


I come from a SVN background, so I'm not familiar with Git.  I assume a PR is a Pull Request?


I've clicked "Create Pull Request" from GitHub and am presented with the following choices:

  *   release/v0.8<https://github.com/combust/mleap/compare/master...release/v0.8>14 minutes ago
  *    feature/ensemble<https://github.com/combust/mleap/compare/master...feature/ensemble>3 days ago
  *    feature/async<https://github.com/combust/mleap/compare/master...feature/async>3 days ago
  *    feature/cors<https://github.com/combust/mleap/compare/master...feature/cors>on Jun 30
  *    master@{1day}...master<https://github.com/combust/mleap/compare/master@%7B1day%7D...master>


I'm suppose I should click "release/v0.8?


FYI.  I'm using Intellij and can get to a Clone Repository dialog that asks for a "Git Repository URL".


I'd love to contribute if you could help me get started the first time.


________________________________

**Comment by hollinwilkins** [comment]
1. First thing to do is to fork mleap. Click on the button in the upper right on this screen. This makes a copy of mleap for your user.

2. Next thing is to clone the fork.
`git clone --recursive git@github.smorring/mleap.git`
This makes a local copy on your computer.

3. Make a branch to work on `git branch feature/issue272 && git checkout feature/issue272`

4. Make your changes

5. Commit your changes `git add . && git commit -m "Fix issue with MaxAbsScaler"`

6. Push your changes to your fork `git push -u origin feature/issue272`

7. Create a pull request with combust/mleap

Let me know if you run into any trouble on the way!

**Comment by smorring** [comment]
I think I've completed all the steps you mentioned.


Please let me know if the changes I pushed aren't visible to you.


________________________________

**Comment by hollinwilkins** [comment]
Closing this issue along with merging the PR. Thanks for the catch!
