### ISSUE TITLE
Use MathBinary and MathUnary from python?

### ISSUE THREAD

**Issue by aufrank** [combust/mleap#294]
Is it possible to use `org.apache.spark.ml.mleap.feature.{MathBinary, MathUnary}` in a model built in pyspark?  If not, would you consider adding support for them to the `mleap` python module?

**Comment by hollinwilkins** [comment]
@aufrank Thanks for brining this up! Would you like to add support for them? You can use our OneHotEncoder integration as a template:

https://github.com/combust/mleap/blob/master/python/mleap/pyspark/feature.py#L51-L56

**Comment by ancasarb** [comment]
There are quite a few duplicates on this question, I am going to close this issue and keep https://github.com/combust/mleap/issues/495 open as a reference ticket.
