### ISSUE TITLE
Question re runtime

### ISSUE THREAD

**Issue by colingoldberg** [combust/mleap#299]
Hi,

This is a question - not an issue:

In your airbnb example on https://github.com/combust/mleap/tree/master/mleap-serving, the whole Leap Frame is sent in the request for a prediction. This includes the schema as well as the data.

eg.
{
  "schema": {
    "fields": [{
      "name": "state",
      "type": {
        "type": "basic",
        "base": "string",
        "isNullable": true
      }
    }, {
      "name": "bathrooms",
      "type": {
        "type": "basic",
        "base": "double",
        "isNullable": true
      }
    }, {
...
  },
  "rows": [["NY", 2.0, 1250.0, 3.0, 50.0, 30.0, 2.0, 56.0, 90.0, "Entire home/apt", "1.0", "strict", "1.0"]]
}

Is it currently possible (or is this on your roadmap) to send only the data - especially as the schema is already known by the server?

I am aware that the schema can be obtained (eg. by a curl -XGET ... http://localhost:65327/model), but it would be an improvement for the requestor not to have to get the schema, only to have to submit it (with the data).

Colin Goldberg

**Comment by colingoldberg** [comment]
As an addendum to the question above: Is there a format that can be used to submit sparse data in a request?

Colin Goldberg

**Comment by hollinwilkins** [comment]
@colingoldberg 

1. Currently sending in row data without schema is not supported by the API server, however, take a look at: https://github.com/combust/mleap/blob/master/mleap-runtime/src/main/scala/ml/combust/mleap/runtime/frame/RowTransformer.scala

Which does exactly what you are talking about, and we do plan to expose via the API server for version 1.0

2. Sparse tensors are supported, they are very similar to dense tensors, except they have a field for keys. I don't have the formatting off-hand

**Comment by colingoldberg** [comment]
As a newcomer to spark and scala, I don't know enough to be able to interpret the RowTransformer.scala script. However, as I see it from my perspective as developer of a generalized platform for - inter alia - training models for any data source and any ml algorithm, and getting realtime predictions, I would most likely store the known schema at training time to be used at prediction time.

I look forward to seeing details of submitting sparse data in the documentation.

Colin Goldberg

**Comment by ancasarb** [comment]
Closing this issue as an effort to clean up some older issues, please re-open if there are still unanswered questions, thank you!
