### ISSUE TITLE
aws lambda

### ISSUE THREAD

**Issue by polya20** [combust/mleap#302]
can mleap libraries be zipped to a 50MB AWS lambda binary size, so that model serving can be done using  aws lambda?

**Comment by ekinrf** [comment]
Same question here, have you found out more?

**Comment by polya20** [comment]
No not yet. I got the docker container working on AWS sagemaker though

**Comment by ekinrf** [comment]
Have you checked out PMML? I have read success stories about Lambda with PMML.

**Comment by hollinwilkins** [comment]
We don't have plans on supporting AWS Lambda. If you would like to pursue this, please provide necessary PRs to get it working. Closing this issue for now.
