### ISSUE TITLE
Load decision tree in scala from json generated by python

### ISSUE THREAD

**Issue by nb-ceffa** [combust/mleap#305]
I wanted to load decision tree classifier from JSON (generated by python) in my Scala application but it is not possible for now because scala loader requires field "num_classes" but python version add this field only if number of classes is greater than 1. :( I think that this is a bug. Isn't it?

Python:
https://github.com/combust/mleap/blob/v0.8.1/python/mleap/sklearn/tree/tree.py#L118

Scala:
https://github.com/combust/mleap/blob/v0.8.1/mleap-runtime/src/main/scala/ml/combust/mleap/bundle/ops/classification/DecisionTreeClassifierOp.scala#L36

**Comment by ancasarb** [comment]
@nb-ceffa Yes, I believe it is a bug - I think we were using n_classes_ to determine whether it is a classifier or regressor being serialized. Once https://github.com/combust/mleap/pull/309 gets merged, this issue should be fixed in 0.9.0.

**Comment by hollinwilkins** [comment]
Closing this issue as I believe it has been fixed.
