### ISSUE TITLE
Deserialization with custom ClassLoader

### ISSUE THREAD

**Issue by htdawoud** [combust/mleap#308]
Our custom transformers live outside of the main project's class path, particularly in database. How to deserialize using a custom ClassLoader?

The code below loads transformers using the default ClassLoader and assumes transformers live with the main project. Ideally we should be able to deserialize as below by providing a custom ClassLoader as a parameter. Is it possible using the current API?
```
// load the Spark pipeline we saved in the previous section
val bundle = (for(bundleFile <- managed(BundleFile("jar:file:/tmp/simple-spark-pipeline.zip"))) yield {
  bundleFile.loadMleapBundle().get
}).opt.get
```

**Comment by htdawoud** [comment]
This appears to work (doing more tests before closing the issue)
```
implicit lazy val context: MleapContext = MleapContext(Some(your-class-loader))
val bundle = (for(bundleFile <- managed(BundleFile("jar:file:/tmp/simple-spark-pipeline.zip"))) yield {
  bundleFile.loadMleapBundle()(context).get
}).opt.get
```

**Comment by hollinwilkins** [comment]
@htdawoud The classloader you provided may have `sun.misc.Launcher$AppClassLoader` as the parent class loader is the only thing I can think of. Let me know if you find something in MLeap itself that is causing it to fallback to the app class loader.

Closing for now.
