### ISSUE TITLE
Bad links on the http://mleap-docs.combust.ml/getting-started/py-spark.html  page

### ISSUE THREAD

**Issue by ibobak** [combust/mleap#310]
If you open the page http://mleap-docs.combust.ml/getting-started/py-spark.html  and click on the links "Jupyter", "Zeppelin" and "Databricks", they will fail

**Comment by ibobak** [comment]
Besides,  if we open the page http://mleap-docs.combust.ml/demos/  and click on "MNIST demo" at the end of the page, it also does not open.

**Comment by ancasarb** [comment]
@ibobak Good find, the links should be updated once https://github.com/combust/mleap-docs/pull/10 gets merged. Thank you!

**Comment by ancasarb** [comment]
PR merged, issue can be closed.
