### ISSUE TITLE
mleap demo notebooks need to updated to work with 0.8.1 

### ISSUE THREAD

**Issue by polya20** [combust/mleap#319]
mleap demo notebooks need to updated to work with 0.8.1. Right now they work fine with 0.5 but have not been updated to reflect the changes in the underlying mleap API.

**Comment by ancasarb** [comment]
@polya20 thanks for the note! I've raised a PR https://github.com/combust/mleap-demo/pull/12 to fix some issues with the demos, and once it gets merged, I was able to run the demos alright.

Please let me know if you find any issues, thanks again!

**Comment by hollinwilkins** [comment]
combust/mleap-demo#12 was merged, closing
