### ISSUE TITLE
java.net.URISyntaxException when use BundleFile with zip-file on Windows

### ISSUE THREAD

**Issue by xdemonx** [combust/mleap#320]
```
[info]   java.net.URISyntaxException: Illegal character in opaque part at index 11: jar:file:C:\Users\DPOBEG~1\AppData\Local\Temp\7027814362110989432\query.zip
[info]   at java.net.URI$Parser.fail(Unknown Source)
[info]   at java.net.URI$Parser.checkChars(Unknown Source)
[info]   at java.net.URI$Parser.parse(Unknown Source)
[info]   at java.net.URI.<init>(Unknown Source)
[info]   at ml.combust.bundle.BundleFile$.apply(BundleFile.scala:28)
```
Problem in [this line](https://github.com/combust/mleap/blob/master/bundle-ml/src/main/scala/ml/combust/bundle/BundleFile.scala#L28).
`new URI(s"jar:file:${file.getAbsolutePath}")` generate an incorrect URI `jar:file:C:\Users\...` (the correct one is `jar:file:/C:/Users/...`). 

The possible solution is to replace this line to 
```
new URI(s"jar:${file.toURI}")
```

**Comment by hollinwilkins** [comment]
@xdemonx Should be fixed with this PR: https://github.com/combust/mleap/pull/333
