### ISSUE TITLE
Understand the structure of tree.json

### ISSUE THREAD

**Issue by jashmahipal** [combust/mleap#324]
I am trying to understand the structure of each "tree.json" file saved by a RandomForestClassifier. The goal is to understand the structure of these files, in order to traverse a prediction through the forest in order to get feature contribution for each prediction from a Spark trained model, converted to MLeap by looking at the internal node value. 

However, the current structure for example looks like 
"
{"type":"internal","split":{"numCategories":35,"isLeft":false,"featureIndex":64,"categories":[0.0,34.0],"type":"categorical"}}
{"type":"internal","split":{"type":"continuous","featureIndex":24,"threshold":98.412698412698}}
{"type":"internal","split":{"type":"continuous","featureIndex":48,"threshold":2258510.0}}
{"type":"internal","split":{"numCategories":46,"isLeft":false,"featureIndex":59,"categories":[20.0,45.0],"type":"categorical"}}
{"type":"internal","split":{"numCategories":36,"isLeft":false,"featureIndex":85,"categories":[0.0,1.0,2.0,3.0,4.0,7.0,8.0,11.0,31.0,33.0,34.0,35.0],"type":"categorical"}}
{"type":"internal","split":{"type":"continuous","featureIndex":1,"threshold":44.0}}
{"type":"internal","split":{"type":"continuous","featureIndex":18,"threshold":2.91970802919708}}
{"type":"internal","split":{"numCategories":46,"isLeft":false,"featureIndex":68,"categories":[16.0,19.0,45.0],"type":"categorical"}}
{"type":"internal","split":{"type":"continuous","featureIndex":16,"threshold":3.2967032967033}}
{"type":"internal","split":{"type":"continuous","featureIndex":14,"threshold":3.0}}
{"type":"internal","split":{"type":"continuous","featureIndex":19,"threshold":0.0558620208086027}}
{"type":"internal","split":{"numCategories":4,"isLeft":true,"featureIndex":83,"categories":[0.0],"type":"categorical"}}
{"type":"leaf","values":[3641.0,0.0]}
{"type":"leaf","values":[3065.0,4.0]}
{"type":"internal","split":{"type":"continuous","featureIndex":27,"threshold":3111907.0}}
{"type":"leaf","values":[8538.0,0.0]}
{"type":"leaf","values":[103.0,1.0]}
{"type":"leaf","values":[12849.0,0.0]}
"

I am not sure how this can be traversed, as I do not know, which leaf value to look after a particular split node. Can someone help me understand this or point me to the code that MLeap would use when Load Model is called and how this tree.json files are parsed?

**Comment by hollinwilkins** [comment]
@jashmahipal Perhaps the best way to see the structure is the write/read function found here:
https://github.com/combust/mleap/blob/master/bundle-ml/src/main/scala/ml/combust/bundle/tree/decision/TreeSerializer.scala#L96-L104

and here:

https://github.com/combust/mleap/blob/master/bundle-ml/src/main/scala/ml/combust/bundle/tree/decision/TreeSerializer.scala#L116-L122

We write/read depth-first left-right all of the nodes in the tree.

**Comment by hollinwilkins** [comment]
Closing this issue. Feel free to reopen if you still have questions.
