### ISSUE TITLE
Allow user to set the listening port for mleap serving as command line argument

### ISSUE THREAD

**Issue by davidecoccia** [combust/mleap#325]
I would like to have the possibility to set the listening port from the starting command (as a parameter) so I will be able to launch multiple instances of mleap serving on the same machine without using docker

**Comment by polya20** [comment]
I just had to change mleap serving code  to run mleap serving on aws sagemaker

**Comment by hollinwilkins** [comment]
@davidecoccia We will be overhauling MLeap serving as part of 1.0. Putting together a roadmap soon and posting it in the README. Will close this issue and point you there when it is ready.

**Comment by cappaberra** [comment]
@davidecoccia, I opened pull request https://github.com/combust/mleap/pull/366 that consequently helps with this request. Hopefully we can get it reviewed / discussed / merged soon. :)

**Comment by hollinwilkins** [comment]
Merged #366
