### ISSUE TITLE
Error in cross validation estimator in Mleap pipeline

### ISSUE THREAD

**Issue by yashaswini87** [combust/mleap#340]
Random forest + cross validation code 
-----------------------------------------
val rf = new RandomForestClassifier().setLabelCol("labels").setFeaturesCol("features").setMaxBins(200).setSeed(100)

  // cross validation step

  val paramGrid = new ParamGridBuilder()
    .addGrid(rf.numTrees, Array(50, 100))
    .addGrid(rf.maxDepth, Array(20,30))
    .build()

  val cv = (new CrossValidator()
    .setEstimator(rf)
    .setEvaluator(new BinaryClassificationEvaluator().setLabelCol("labels"))
    .setNumFolds(3)
    .setEstimatorParamMaps(paramGrid))

 val sparkPipelineEstimatorRf = new Pipeline().setStages(Array(sparkFeaturePipelineModel, cv))

Error
-----------

key not found: org.apache.spark.ml.tuning.CrossValidatorModel
java.util.NoSuchElementException: key not found: org.apache.spark.ml.tuning.CrossValidatorModel

**Comment by rgeos** [comment]
I think the error is expected because the CrossValidator transformer is not supported ( see #192 )
The purpose of crossValidator is not model building, but model checking to make sure you are not (over/under)fitting.

**Comment by hollinwilkins** [comment]
@yashaswini87 We don't support cross validation models or other models that are used in just training. In order to export your model, select the best model trained by the cross validator and include that in your output pipeline.

Closing this issue
