### ISSUE TITLE
Why need argparse?

### ISSUE THREAD

**Issue by hjbj** [combust/mleap#341]
I notice that in `setup.py`, `argparse` module is required. 
The argparse module is maintained within the Python standard library for Python >= 2.7 and >=3.2. So I guess the `argparse` module in `setup.py` is  for users who still need to support Python < 2.7 or < 3.2, right?
However, there is no command-line interfaces, and if I use Python >=3.2, may I remove it from the `setup.py`？

**Comment by seme0021** [comment]
yeah, go ahead and submit a PR please!

**Comment by ancasarb** [comment]
PR to address this issue https://github.com/combust/mleap/pull/382

**Comment by ancasarb** [comment]
closing this as PR has been merged.
