### ISSUE TITLE
Is there a way to construct the LeapFrame and get predict omitting some columns?

### ISSUE THREAD

**Issue by dvaldivia** [combust/mleap#348]
Hi,

I'm trying a NaiveBayes model on Spark and serializing it and using it on Mleap successfully, however I'm running into an issue where if I build the `input` leapFrame without every training column I get an exception saying indexOf the missing column is invalid

```
SEVERE: Exception while executing runnable my.class@24d873c2
java.lang.IllegalArgumentException: invalid field: point_label
	at ml.combust.mleap.core.types.StructType.indexOf(StructType.scala:194)
```

Not only definining them, but I need to provide a valid value since they were using an indexer

While when working with spark I could omit these training columns (ie: point_label) and spark would work just around them.

Is there a way to have Mleap ignore the missing columns?

**Comment by dvaldivia** [comment]
If I pass an invalid value I get

```
java.util.NoSuchElementException: Unseen label: . To handle unseen labels, set handleInvalid to keep
```

**Comment by hollinwilkins** [comment]
@dvaldivia The solution to this problem is to not include the string indexer used to generate training labels in the output MLeap pipeline.

In addition, you could consider adding a reverse string indexer to the end of the pipeline so you can interpret your results better.
