### ISSUE TITLE
xgboost4j integration

### ISSUE THREAD

**Issue by geoHeil** [combust/mleap#35]
mleap seems to support `RandomForestClassifier`. What about `xgboost`, especially xgboost4j?
https://github.com/komiya-atsushi/xgboost-predictor-benchmark provides a great jvm based and very quick evaluator. Maybe this would be helpful for a xgboost-mleap integration.

**Comment by hollinwilkins** [comment]
Hey,

This could be an interesting extension library to MLeap, and is exactly the kind of thing that would help to make MLeap even better!

Please let me know if you would like help building this out.

**Comment by fatihtekin** [comment]
Could you please give us some guide to develope mleap xgboost?

**Comment by hollinwilkins** [comment]
@geoHeil Started work on this, if you are still interested keep track of the PR here:
https://github.com/combust/mleap/pull/259

**Comment by hollinwilkins** [comment]
Merged into master
