### ISSUE TITLE
Access a PipelineModel stages

### ISSUE THREAD

**Issue by dvaldivia** [combust/mleap#351]
I'm trying to figure out how to access the stages of a loaded model, I see that from the bundle there's a model propery of type `PipelineModel` and if I call print on it, I can see the list of stages, but  I cannot seem to be able to access them from code, any guidance would be appreaciated

**Comment by ancasarb** [comment]
could ``` bundle.root.asInstanceOf[Pipeline].model.stages ``` be what you're looking for?

**Comment by ancasarb** [comment]
Closing this, please feel free to re-open if if the suggestion above doesn't fix your issues.
