### ISSUE TITLE
Need support for spark 2.3 featurehasher 

### ISSUE THREAD

**Issue by caesarjuly** [combust/mleap#352]
In version 2.3, spark introduces a new transformer named featurehasher which is really simple and easy to use. Do we have any plan to support this transformer?
Related docs:
https://spark.apache.org/docs/latest/ml-features.html#featurehasher
https://databricks.com/session/feature-hashing-for-scalable-machine-learning

Btw, according to the document http://mleap-docs.combust.ml/core-concepts/transformers/support.html, there is no hashingTF transfomer support. But after reading some issues, it seems we have already supported this transformer. Do we?

**Comment by hollinwilkins** [comment]
@caesarjuly This would be a welcome feature, and would get us on Spark 2.3. Let us know if you need anything for this.

**Comment by caesarjuly** [comment]
@hollinwilkins Recently I try to build a online realtime scoring server using this awesome project. And some of my feature transformers depend on these new features. So this issue comes. While getting familiar with this project, I find that some docs are outdated and confusing. Can I do something? Maybe I can get do some coding and update docs. Where should I go first?

**Comment by hollinwilkins** [comment]
#364 merged
