### ISSUE TITLE
Extend MLeap Server to serve multiple models

### ISSUE THREAD

**Issue by schlichtanders** [combust/mleap#362]
MLeap seems to be one of the recommended replacements for PMML ([see e.g. here](https://medium.com/rv-data/mleap-providing-near-real-time-data-science-with-apache-spark-c34e7df093ca)). While for PMML [openscoring](https://github.com/openscoring/openscoring) already implements a quite flexible model server, MLeap does not seem to have such support yet.

What is there in MLeap:
- http://mleap-docs.combust.ml/mleap-serving/
- i.e. spawn one server for one model

Concretely what would be great to have:
- spawn one server for multiple models
- e.g. to be able to add new models to an already running model server

Is there already something like this? If not, is it planned or easily setup?

**Comment by kevinykuo** [comment]
Related https://github.com/combust/mleap/issues/245

**Comment by hollinwilkins** [comment]
@kevinykuo @schlichtanders Take a look at this branch, where a lot of work is being done to improve the model servers: https://github.com/combust/mleap/tree/feature/mleap-grpc

**Comment by kevinykuo** [comment]
Yep, definitely looking forward to that!

**Comment by ancasarb** [comment]
We've re-implemented the serving layer, using either grpc or http (spring boot).

https://github.com/combust/mleap/tree/master/mleap-serving
https://github.com/combust/mleap/tree/master/mleap-executor
https://github.com/combust/mleap/tree/master/mleap-spring-boot

Please let us know if there see any issues, thanks!
