### ISSUE TITLE
MLeap Scikit Example Broken

### ISSUE THREAD

**Issue by donigian** [combust/mleap#367]
Hi,
I tried to get the Scikit-learn [example](http://mleap-docs.combust.ml/getting-started/scikit-learn.html) from the documentation to work

```
# Initialize a FeatureExtractor, which subselects only the features we want
# to run the Standard Scaler against
input_features = ['a', 'c', 'd']
output_vector_name = 'unscaled_continuous_features' # Used only for serialization purposes
output_features = ["{}_scaled".format(x) for x in input_features]

feature_extractor_tf = FeatureExtractor(input_scalars=input_features,
                                        output_vector=output_vector_name,
                                        output_vector_items=output_features)


# Define the Standard Scaler as we normally would
standard_scaler_tf = StandardScaler(with_mean=True,
                                    with_std=True)

# Execute ML-Init to add the require attributes to the transformer object
# Op and Name will be initialized automatically
standard_scaler_tf.mlinit(prior_tf=feature_extractor_tf,
                          output_features='scaled_continuous_features')
```

 But ran into the following error:

```

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-3-a38e6a0355a2> in <module>()
     17 # Op and Name will be initialized automatically
     18 standard_scaler_tf.mlinit(prior_tf=feature_extractor_tf,
---> 19                           output_features='scaled_continuous_features')

/Users/avd/anaconda/envs/py35_auto_/lib/python3.5/site-packages/mleap/sklearn/preprocessing/data.py in mleap_init(self, prior_tf, output_features)
     88         output_feature_name = prior_tf.output_features
     89 
---> 90     class_name = "{}".format(self.__init__.im_class).split('.')[-1].replace('>','').replace("'",'')
     91 
     92     if output_features is not None:

AttributeError: 'function' object has no attribute 'im_class'
```

Any suggestions?

AirBnb price regression [example](https://github.com/combust/mleap-demo/blob/master/notebooks/airbnb-price-regression-scikit.ipynb) breaks due to the same error.

**Comment by MTDzi** [comment]
Same here.

**Comment by ksoucy** [comment]
I experienced the same issue, it looks related to changes made in #344 which were merged to master. 

If you change line 90 in your local /Users/avd/anaconda/envs/py35_auto_mrm/lib/python3.5/site-packages/mleap/sklearn/preprocessing/data.py  file, to match the master branch, the demo notebook works:

-    class_name = "{}".format(self.__init__.im_class).split('.')[-1].replace('>','').replace("'",'')
+    class_name = self.__class__.__name__

Alternatively, you could also rebuild from source from the current master branch.

**Comment by ancasarb** [comment]
@donigian @MTDzi Yes, @ksoucy is right, we merged https://github.com/combust/mleap/pull/344 in order to make mleap scikit-learn work with python 3. 

I'll try to get a new version of the package published to pypi so that you don't need to rebuild from source.

**Comment by andyliucoder** [comment]
Ran into this error, so I'm assuming a new version hasn't been published to pypi yet?

Just to be clear, line 90 of data.py needs to be changed to `class_name = self.__class__.__name__` (github formatting rendered the underscores in @ksoucy's answer.

**Comment by dat-vikash** [comment]
ran into this issue as well ... any updates on when this will be pypi?

**Comment by nsutcliffe** [comment]
Also just ran into the same issue 👎

**Comment by gyubaekkim** [comment]
I tested the workaround that @ksoucy and @andyliucoder suggested but it doesn't work.
Is there any other workaround to be applied before this issue is fixed?

Thanks.

**Comment by ericx10ng** [comment]
ran into the same error

**Comment by lalith1403** [comment]
works only with Python 2.7. Python3 gives the following error.

**Comment by ancasarb** [comment]
We added support for Python 3 as part of Mleap 0.15.0, you can see the tests running successfully against Python 2.7, 3.6 and 3.7 in the Travis CI https://travis-ci.org/combust/mleap. Closing this, please let me know and feel free to re-open if you still find issues in Python 3. Thank you!

**Comment by NastasiaSaby** [comment]
I am still facing this issue. Python 3, MLeap 0.16.0.
