### ISSUE TITLE
Python Mleap library in v0.10.1 release mantains 0.9.4 version

### ISSUE THREAD

**Issue by asoriano-stratio** [combust/mleap#372]
Versioning in Python Mleap library seems not be updated in v0.10.1 release:

File: mleap/python/mleap/version.py

__version__ = "0.9.4"

**Comment by ancasarb** [comment]
PR to address this issue https://github.com/combust/mleap/pull/382

**Comment by ancasarb** [comment]
closing this as PR has been merged.
