### ISSUE TITLE
Support Hadoop FileSystem in Spark model export

### ISSUE THREAD

**Issue by mengxr** [combust/mleap#379]
MLeap model export supports "jar:file:/..." type URI. Spark users might want to use Hadoop FileSystem to export models to a shared storage. This is currently not supported, and it would be nice to support it natively. Note that the implementation can be done by saving to local temp directory first and then copy over.

**Comment by hollinwilkins** [comment]
*** Notes on this ****

We would want to introduce a `BundleFileSystem` trait that wraps file systems like Hadoop and S3 under the hood and allows us to perform operations using those file systems. We would make a BundleFile constructible using this `BundleFileSystem` trait, and before actually loading/saving the bundle file we would move the files to a temporary local file or upload a local model to the abstracted file system while saving.

Would need to add module:
`bundle-ml-hdfs` - implements the `BundleFileSystem` trait for HDFS

**Comment by hollinwilkins** [comment]
PR open for this now: https://github.com/combust/mleap/pull/415
Just a few items left to complete

**Comment by CoderLee2014** [comment]
I have tried the code on bundle-hdfs [https://github.com/combust/mleap/tree/master/bundle-hdfs](url). But there was still the exception No configuration setting found for key 'ml.combust.mleap.spark'. Should we configure the reference.conf ourselves?

**Comment by CoderLee2014** [comment]
> I have tried the code on bundle-hdfs [https://github.com/combust/mleap/tree/master/bundle-hdfs](url). But there was still the exception No configuration setting found for key 'ml.combust.mleap.spark'. Should we configure the reference.conf ourselves?

@hollinwilkins

**Comment by ancasarb** [comment]
Closing this, this been available available in mleap for a while, please see readme notes here https://github.com/combust/mleap/blob/master/bundle-hdfs/README.md

and one other short complete example, in case it's needed.

```

import org.apache.spark.ml.{Pipeline, Transformer, PipelineModel}
import org.apache.spark.sql.{Row, DataFrame}
import org.apache.spark.sql.types.{StringType, DoubleType, StructType}

val names = Seq("Hello, MLeap!", "Another row", "test")
val numbers = Seq(56.7d, 23.4d)
val rows = spark.sparkContext.parallelize(Seq.tabulate(3) { i => Row(names(i)) })
val schema = new StructType().add("name", StringType, nullable = false)

val dataset: DataFrame = spark.sqlContext.createDataFrame(rows, schema)

import ml.combust.bundle.BundleFile
import ml.combust.bundle.serializer.SerializationFormat
import org.apache.spark.ml.feature.StringIndexer
import org.apache.spark.ml.mleap.SparkUtil
import ml.combust.mleap.spark.SparkSupport._
import resource._
import org.apache.spark.ml.bundle.SparkBundleContext

val stringIndexer = new StringIndexer().
  setInputCol("name").
  setOutputCol("index")

val pipelineEstimator = new Pipeline().setStages(Array(stringIndexer)).fit(dataset)

import java.net.URI
implicit val sbc = SparkBundleContext().withDataset(pipelineEstimator.transform(dataset))
pipelineEstimator.writeBundle.save(new URI("hdfs:///tmp/simple-spark-pipeline-hdfs-test.zip"))

val loadedPipeline = new URI("hdfs:///tmp/simple-spark-pipeline-hdfs-test.zip").loadMleapBundle().get.root

loadedPipeline.asInstanceOf[PipelineModel].stages
```

Thank you!
