### ISSUE TITLE
Add support for Spark's OneHotEncoderEstimator/Model

### ISSUE THREAD

**Issue by lbustelo** [combust/mleap#380]
At some point in Spark 2.3.x there was a re-write of the OneHotEncoder support to better fit the Pipeline model. MLeap currently does not support these new types.

Beware... the docs for Spark say that there will be another renaming of this transformer in Spark 3.0

**Comment by clocklear** [comment]
I'll take this issue.  It's pretty straightforward; sorry I overlooked this addition when I performed the upgrade to 2.3.

**Comment by ancasarb** [comment]
Closing this as support for this was added in the PR merged above.
