### ISSUE TITLE
Try to avoid calling `Dataframe.head` to infer Vector's size

### ISSUE THREAD

**Issue by huafengw** [combust/mleap#391]
Currently when translating a spark field to a mleap field, the first Row will be retrieved to infer the Vector size in a VectorUDT column. The problem is that it may be an expensive function call if the input Dataframe has lots of stages.

Sometimes the metadata of Vector column may contains the Vector size info so I think Mleap should first try to infer from that and make calling `Dataframe.head` as the last option.

**Comment by hollinwilkins** [comment]
Closing this with the merge of your PR
