### ISSUE TITLE
There should be an assembly JAR for use with Databricks ML Runtime

### ISSUE THREAD

**Issue by hollinwilkins** [combust/mleap#393]
# Overview

[Databricks ML Runtime](https://docs.azuredatabricks.net/user-guide/clusters/mlruntime.html) supports Spark ML, TensorFrames and XGboost for training. MLeap is capable of exporting these models to an MLeap bundle for later use. In order to make this work consistently and avoid issues, we would like to package the required libraries into an assembly (AKA fat) jar with shaded dependencies.

NOTE: Scikit-learn support will not be included in this ticket.
NOTE: Handled by PR: https://github.com/combust/mleap/pull/398

## Modules to Include

The following modules should be included in the assembly JAR.

- [x] mleap-base
- [x] bundle-ml
- [x] mleap-tensor
- [x] mleap-core
- [x] mleap-runtime
- [x] mleap-spark-base
- [x] mleap-spark
- [x] mleap-spark-extension
- [x] mleap-tensorflow
- [x] mleap-xgboost-spark

## Distribution via Maven

The assembly jar will be published to Maven Central along with all other MLeap jars and included in the automated build process. Snapshot versions will be distributed through OSS Sonatype Snapshots.

The name of the jar file will be `mleap-databricks-runtime`.

## Notes on TensorFlow and XGboost

TF and XGboost both rely on the JNI to call into shared libraries. These libraries are provided by the Databricks ML Runtime, so we will make sure to exclude any pre-packaged JNIs that TF or XGboost provide from the MLeap assembly.

## Exposed 3rd Party Classes

This list is meant to track any 3rd party-shaded classes that may be exposed by MLeap. Longer-term, we will want to remove these if they come up.

## Shaded Dependencies

This list is meant to track all dependencies that will be shaded, marked provided, or excluded from assembly jar for each module.

```
  ShadeRule.rename("spray.json.**" -> "ml.combust.mleap.shaded.@0").inAll,
  ShadeRule.rename("com.google.protobuf.**" -> "ml.combust.mleap.shaded.@0").inAll,
  ShadeRule.rename("com.trueaccord.**" -> "ml.combust.mleap.shaded.@0").inAll,
  ShadeRule.rename("au.com.**" -> "ml.combust.mleap.shaded.@0").inAll,
  ShadeRule.rename("com.github.**" -> "ml.combust.mleap.shaded.@0").inAll,
  ShadeRule.rename("com.typesafe.**" -> "ml.combust.mleap.shaded.@0").inAll,
  ShadeRule.rename("edu.emory.**" -> "ml.combust.mleap.shaded.@0").inAll,
  ShadeRule.rename("fastparse.**" -> "ml.combust.mleap.shaded.@0").inAll,
  ShadeRule.rename("google.protobuf.**" -> "ml.combust.mleap.shaded.@0").inAll,
  ShadeRule.rename("machinist.**" -> "ml.combust.mleap.shaded.@0").inAll,
  ShadeRule.rename("macrocompat.**" -> "ml.combust.mleap.shaded.@0").inAll,
  ShadeRule.rename("org.apache.commons.**" -> "ml.combust.mleap.shaded.@0").inAll,
  ShadeRule.rename("org.netlib.**" -> "ml.combust.mleap.shaded.@0").inAll,
  ShadeRule.rename("org.j_paine.**" -> "ml.combust.mleap.shaded.@0").inAll,
  ShadeRule.rename("resource.**" -> "ml.combust.mleap.shaded.@0").inAll,
  ShadeRule.rename("scalapb.**" -> "ml.combust.mleap.shaded.@0").inAll,
  ShadeRule.rename("scalaxy.**" -> "ml.combust.mleap.shaded.@0").inAll,
  ShadeRule.rename("shapeless.**" -> "ml.combust.mleap.shaded.@0").inAll,
  ShadeRule.rename("spire.**" -> "ml.combust.mleap.shaded.@0").inAll,
  ShadeRule.rename("sourcecode.**" -> "ml.combust.mleap.shaded.@0").inAll,
  ShadeRule.rename("buildinfo.**" -> "ml.combust.mleap.shaded.@0").inAll,

  ShadeRule.zap("org.slf4j.**").inAll
```

### mleap-tensorflow
NOTES: need to make sure MLeap's TF version is compatible with the JNI provided by Databricks

### mleap-xgboost-spark

NOTES: Need to determine exact version of XGboost to integrate with for the assembly jar

**Comment by ancasarb** [comment]
Closing this, as PR https://github.com/combust/mleap/pull/398 has been merged and released.
