### ISSUE TITLE
[Idea / Suggestion] Sharing the docker-file 

### ISSUE THREAD

**Issue by PowerToThePeople111** [combust/mleap#395]
Hi guys,

I was wondering, if you could share the docker file which is used to define the docker image containing Mleap-Serving.

This way, people who adapt the serving module to their needs can quickly build the corresponding convenient docker containers.

Apart from that, I love your project! Makes going to production way easier. :-) 

Best,
Björn

**Comment by PowerToThePeople111** [comment]
Ok. I did not realize that the whole Docker Image Creation is done via a plugin: https://www.scala-sbt.org/sbt-native-packager/formats/docker.html

Building it appropriately works as follows for all who are interested:

```
cd mleap
sbt
project mleap-serving
docker:stage
```

**Comment by RayTsui** [comment]
@PowerToThePeople111 
Hi, actually, I have the same concern as you, that whether or not we can have mleap-serving image. As you closed the issue, I suppose you have figured it out how to get it. 

Based on your above description, I still cannot know how to build image, can you please say a little more on it. Thanks a lot.

**Comment by PowerToThePeople111** [comment]
@RayTsui Hi, sorry for my late answer, but I have been on holidays and did not check mails. If you follow the instructions above, go to `mleap-serving/target/docker` and you will find what you are looking for.

**Comment by RayTsui** [comment]
Hi @PowerToThePeople111 , thanks for your response. Basically, I've figured it out via online sbt manual docs, although the doc is a little more to read.
