### ISSUE TITLE
Create custom transformers using pyspark

### ISSUE THREAD

**Issue by somya12** [combust/mleap#396]
Hi,

Is it possible to create custom transformers in pyspark using mleap?  This [doc](https://github.com/combust/mleap-docs/blob/master/faq.md) states that the pyspark support is yet to come. On the other hand, the [pyspark](https://github.com/combust/mleap-docs/blob/master/py-spark/index.md) documentation states that the support is already present. If custom transformers are support, can someone direct me to a few examples?

**Comment by femibyte** [comment]
Same issue here. Any word ?

**Comment by ancasarb** [comment]
There are quite a few duplicates on this question, I am going to close this issue and keep https://github.com/combust/mleap/issues/495 open as a reference ticket for this enhancement.
