### ISSUE TITLE
Save to MLEAP bundle is failing for Spark 2.3 model - Logistic Regiression

### ISSUE THREAD

**Issue by vegoutha** [combust/mleap#397]
Save to mleap bundle is failing for Spark model created in 2.3 with below error message.
```
No configuration setting found for key 'ml.combust.mleap.builtin-ops'
```

`MLEAP Version`: 0.10.0

`Spark version`: 2.3

Code Snippet:
```
val sbc = SparkBundleContext().withDataset(model.transform(df))
for (bf <- managed(BundleFile("file:" + filePathName))) {
     leapPipeline.writeBundle.save(bf)(sbc).get         ----> Save to MLEAP bundle is failing
}
```

I have tried to add the below configuration in application.conf and still see the same error message:
```
ml.combust.mleap.spark.registry.default = ${ml.combust.mleap.spark.registry.v23}
```

The same code and configuration was working for Spark 2.1 and 2.3 models.
Could you please let me know do I need to specify the configuration key - `ml.combust.mleap.builtin-ops` for Spark 2.3 ?

**Comment by hollinwilkins** [comment]
This issue is usually due to:
1. Class loader issues, make sure the reference.conf files from MLeap are in the classpath
2. The assembly JAR you are building is dropping content from the reference.conf files from MLeap

**Comment by vegoutha** [comment]
@hollinwilkins I am using other dependency using MLEAP 0.7.0 and it having conflict with MLEAP 0.10.0. Now issue is resolved. Thank you.
