### ISSUE TITLE
How to serialize model to HDFS?

### ISSUE THREAD

**Issue by wuxianxingkong** [combust/mleap#400]
In documentation, it seems mleap only support save model to local file system, is there any way save to HDFS?

**Comment by hollinwilkins** [comment]
@wuxianxingkong Currently the recommended way to accomplish this is to first save the file locally, then move it to hadoop as a separate step.

There is a ticket currently to handle support for doing this in one step: https://github.com/combust/mleap/issues/379

**Comment by ancasarb** [comment]
Closing this, please see more details in #379.
