### ISSUE TITLE
Compile error while using pipelinemodel.writebundle

### ISSUE THREAD

**Issue by rock626** [combust/mleap#410]
Hi,
i am trying to use mleap with spark and export the model.Followed the steps [https://github.com/combust/mleap/wiki/Serializing-a-Spark-ML-Pipeline-and-Scoring-with-MLeap](Mleap wiki).
Observed the following error 
```
Error:(105, 21) value writeBundle is not a member of org.apache.spark.ml.PipelineModel
      pipelinemodel.writeBundle.save(bf)(sbc).get
```

**Comment by rock626** [comment]
these are the versions i used in sbt file

`scalaVersion := "2.11.1"



libraryDependencies += "org.apache.spark" %% "spark-sql" % "2.3.1"
libraryDependencies += "ml.combust.mleap" %% "mleap-runtime" % "0.9.0"
libraryDependencies += "ml.combust.mleap" %% "mleap-spark" % "0.9.0"
libraryDependencies += "ml.combust.mleap" %% "mleap-spark-extension" % "0.9.0"
libraryDependencies += "org.apache.spark" %% "spark-mllib" % "2.3.1"`

**Comment by hollinwilkins** [comment]
Follow instructions here: http://mleap-docs.combust.ml/spark/
Make sure to:

```
import ml.combust.mleap.spark.SparkSupport._
```

**Comment by rock626** [comment]
thanks..adding import statement worked.

**Comment by rock626** [comment]
@hollinwilkins could you also provide reference links/wiki on how to serving this saved model in java?

**Comment by ancasarb** [comment]
We've re-implemented the serving layer, using either grpc or http (spring boot). You can take a look at the new serving layer, using the links below.

https://github.com/combust/mleap/tree/master/mleap-serving
https://github.com/combust/mleap/tree/master/mleap-executor
https://github.com/combust/mleap/tree/master/mleap-spring-boot

More examples in Java can also be found here: https://github.com/combust/mleap/blob/master/mleap-runtime/src/test/scala/ml/combust/mleap/runtime/javadsl/JavaDSLSpec.java.

Thank you!
