### ISSUE TITLE
In-memory conversion of Spark Transformer -> Bundle[Transformer]

### ISSUE THREAD

**Issue by tovbinm** [combust/mleap#413]
Howdy,

Is there a simple way having an instance of Spark `Transformer` convert it into `Bundle[ml.combust.mleap.runtime.frame.Transformer]` in memory without passing through files? Example:

```scala
val indexer: StringIndexerModel = new StringIndexer().fit(ds)
val bundle: Bundle[ml.combust.mleap.runtime.frame.Transformer] = ??? // how do we get the mleap transformer bundle?
```

**Comment by hollinwilkins** [comment]
@tovbinm This is an interesting use case. I think people have used in-memory nio FileSystem implementations to accomplish similar things in the past. The issue with this is that some data structures, such as decision trees, are serialized directly to a file to avoid large, duplicated in-memory structures.

What is the reason you want to do this in the first place? Would be interesting to know.

**Comment by tovbinm** [comment]
I am trying to use mleap runtime, but avoid redoing the serilization of models ;) Right now we leverage vanilla Spark json + parquet serialization.
So for serving I would like to load the Spark model, covert it into mleap format in memory and server scores.

**Comment by tovbinm** [comment]
I was able to workaround it using the [in-memory file system](https://github.com/marschall/memoryfilesystem) implementation. Here is the implementation if anyone is curious - https://github.com/salesforce/TransmogrifAI/blob/master/local/src/main/scala/com/salesforce/op/local/OpWorkflowModelLocal.scala#L154
