### ISSUE TITLE
Example where the target/label is *not* included in the pipeline to be exported 

### ISSUE THREAD

**Issue by iamontheinet** [combust/mleap#429]
Hi!

I am looking for a working example that shows how to exclude the target/label to be predicted from the pipeline being exported to the MLeap bundle.

Thanks in advance!
Dash

**Comment by PowerToThePeople111** [comment]
Hey Dash,

I guess you run into the problem of your final mleap pipeline expecting the label to be part of your dataframe which you want to classify. This can easily be avoided by creating the final label you use to train your classifier outside of the pipeline (before) that you export with Mleap. 

Best

**Comment by iamontheinet** [comment]
@PowerToThePeople111 Thanks for your response. Do you happen to know of any working examples that I can refer to? Cheers!

**Comment by PowerToThePeople111** [comment]
I have written my own and it works, but the code is not really suitable for a simple and good example - regardless of the data that they depend on. You can basically go with any of the following notebooks I guess: https://github.com/combust/mleap-demo

I hope that helps. :)

**Comment by ancasarb** [comment]
Closing this issue for now, please re-open if you are still having issues with this.
