### ISSUE TITLE
The request content was malformed: Expected String as JsString, but got 4.11

### ISSUE THREAD

**Issue by Ajaysingodia** [combust/mleap#432]
**curl -XPOST -H "accept: application/json" -H "content-type: application/json" -d @test.json http://localhost:65327/transform**
The request content was malformed:
Expected String as JsString, but got 4.11

**Comment by ancasarb** [comment]
We've re-implemented the serving layer, using either grpc or http (spring boot).

Could you please take a look at
https://github.com/combust/mleap/tree/master/mleap-serving 
https://github.com/combust/mleap/tree/master/mleap-executor
https://github.com/combust/mleap/tree/master/mleap-spring-boot (HTTP)

and let us know if there are any issues? Thanks!

Will close this issue for now, as it's related to the older serving layer, could you please reopen if you still see an issue? Thanks!
