### ISSUE TITLE
Compatibility with Scala 2.12

### ISSUE THREAD

**Issue by FredYao** [combust/mleap#445]
Spark has released a new version 2.4.0, which is compiled through Scala 2.12. I am wondering if there is any plan or roadmap for Mleap to support Scala 2.12 ? Thanks!

**Comment by ancasarb** [comment]
PR for supporting scala 2.12 https://github.com/combust/mleap/pull/496.

**Comment by FredYao** [comment]
Thanks to @ancasarb for creating a PR enhancing the scala version support. Waiting for the PR to be released! I am closing this ticket now.

**Comment by ancasarb** [comment]
@FredYao support for scala 2.12 has been released in mleap 0.14.0
