### ISSUE TITLE
General Questions about mleap API

### ISSUE THREAD

**Issue by RayTsui** [combust/mleap#451]
@hollinwilkins I just reviewed the docs of mleap, and I have few questions about the utilization of mleap api and roadmap as follows:
1) during storage of leap frame into json/arvo at the linked http://mleap-docs.combust.ml/mleap-runtime/storing.html, for the following code, 
val frame = DefaultLeapFrame(schema, dataset)
for(bytes <- frame.writer("ml.combust.mleap.json").toBytes();
    frame2 <- FrameReader("ml.combust.mleap.json").fromBytes(bytes)) {
  println(new String(bytes)) // print the JSON bytes
  assert(frame == frame2)
}
frame with type DefaultLeapFrame seems not to have `writer` method after I check the api of DefaultLeapFrame, and it does not work in IDE, please help to figure it out.

2) I saw the api at the link of https://www.javadoc.io/doc/ml.combust.mleap/mleap-runtime_2.11/0.12.0, ml.combust.leap has so many sub-brands like `mleap-core`,`mleap-runtime`, `mleap-spark` and `mleap-spark-extension`, at the same time, among them, the same ml models and transformers appear on among them, my questions is that is there any documents to tell the difference among them, or when to use them, or some kind of descriptions on them.

3) what is differences between ScalarType.String or ScalarType(BasicType.String)?

4) As described in doc, the goal of mleap is to satisfy the production-level deploy, and then I reproduce the deploy along with http://mleap-docs.combust.ml/mleap-serving/ using two toy models airbnb.model.rl.zip and airbnb.model.rf.zip, after I deploy both them with 
curl -XPUT -H "content-type: application/json" \
  -d '{"path":"/models/airbnb.model.rf.zip"}' \
  http://localhost:65327/model  
and 
curl -XPUT -H "content-type: application/json" \
  -d '{"path":"/models/airbnb.model.rf.zip"}' \
  http://localhost:65327/model

How should I point out which specific model I use, for example, I use the following request
curl -XPOST -H "accept: application/json" \
  -H "content-type: application/json" \
  -d @/tmp/frame.airbnb.json \
  http://localhost:65327/transform
to rf model or lr model. 

please help me to figure above questions out, so that I can understand mleap better. Thanks a lot.

**Comment by RayTsui** [comment]
Hi @ancasarb according to the #245 , is there any plan for serving multiple models right now, I mean if the 0.13.0 releases serving multiple models. Thanks a lot.

**Comment by ancasarb** [comment]
hey @RayTsui the new model serving services are available in 0.13, please let us know if you have any questions!

**Comment by RayTsui** [comment]
@RayTsui Hi @ancasarb I am always paying attention on mleap, once I have issues and good suggestions, I will post it here. Again, I am so appreciated for your update.
