### ISSUE TITLE
Latest pip version

### ISSUE THREAD

**Issue by jasleen1291** [combust/mleap#461]
Is there a plan to update mleap to the latest version on pypi- I can stil see 0.8 version over there?  https://pypi.org/project/mleap/#history

**Comment by a-p-o** [comment]
@ancasarb What is the recommended alternative if the PyPi project is not updated?

**Comment by a-p-o** [comment]
For anyone else having this issue, my work around is to clone the repo at the version I want:

```
git clone \
  # Specify the tag you want to check out
  --branch 'v0.15.0' \
  # Don't pull the whole repo, just the commits you need
  --depth 1 \
  git@github.com:combust/mleap.git
```

**Comment by ancasarb** [comment]
I've release the python mleap version 0.15.0 just today, fyi https://pypi.org/project/mleap/#history, please let me know if you see any issues.
