### ISSUE TITLE
xgboost runtime transform bad performance

### ISSUE THREAD

**Issue by holysoros** [combust/mleap#471]
In our news CTR prediction scenario, we use xgboost to predict leaves then feed LogisticRegression as feature. The batch size is 1000 news candidates.

But mleap xgboost transformer perform much slower than raw xgboost scala library(x10~20 slower). I think there are two reasons:

- mleap xgboost transformer transform row by row, raw xgboost library can predict 1000 candidates at once with DMatrix that can boost with multiple threads;
- mleap xgboost transformer perform all of `predictRaw/predictProbabilities/predict/predictLeaf/predictContrib` default, but I just need `predictLeaf`;

Is it right?

**Comment by marsbible** [comment]
you can refer to my mleap branch https://github.com/marsbible/mleap/tree/batch-predict, it adds batch prediction to xgboost runtime.
addtionally  your can refer to my xgboost branch https://github.com/marsbible/xgboost/tree/predict-multithreading, it remove some threads contention code for prediction.

**Comment by zengyaowu** [comment]
> you can refer to my mleap branch https://github.com/marsbible/mleap/tree/batch-predict, it adds batch prediction to xgboost runtime.
> addtionally your can refer to my xgboost branch https://github.com/marsbible/xgboost/tree/predict-multithreading, it remove some threads contention code for prediction.
---------------------------------------------------------------------------------------------------
How much faster after the modification?  I have the same problem，When predict, it will often rise from 20 milliseconds to hundreds of milliseconds by chance.

**Comment by CatTail** [comment]
Hey @ancasarb can you help to answer this question?

**Comment by psc0606** [comment]
mleap run on xgboost is really slow.

**Comment by Yodeser** [comment]
Hello @marsbible . Is there any example of how to use RowTransformer(batch predict) ?

**Comment by psc0606** [comment]
I have do some test. The bottleneck of the performance is XGBoostClassification call many times predictions by XGboost. In default, It will call `rawPrediction`, `probability`, `prediction`, `leafPrediction`,  `contribPrediction`.  That's the reason why xgboost runtime transform bad performance. So you should change the source code to comment it.

Another, the batch prediction only gain 10% improves.  I test @marsbible ' s code.

**Comment by lucagiovagnoli** [comment]
Hi @holysoros , we recently merged in this PR: https://github.com/combust/mleap/pull/645
which should make runtime predictions faster, if you use the PredictorOp.

If you try it out, let me know how it goes

**Comment by ancasarb** [comment]
Closing this for now in preparation of release 0.16.0, please reopen if PredictorOp doesn't improve things.
