### ISSUE TITLE
Is MLeap actually a serialization “format”?

### ISSUE THREAD

**Issue by dmitrievanthony** [combust/mleap#473]
Hi, I've already asked the [question on StackOverflow](https://stackoverflow.com/questions/54126259/is-mleap-actually-a-serialization-format), but let me duplicate it here.

I began to work with [MLeap][1] as a serialization tool that allows to save model in Spark or scikit-learn and load it for inference using [MLeap Runtime][2]. It works well. 

Now my purpose is to load a model saved using MLeap into my Java code, into my own structures, without MLeap Runtime. I investigated a bit and haven't found any "format definitions" of "schema", only examples that show how *some* serialized models look like. From that perspective it looks like MLeap is just a serialization/deserialization tool, not a "format" as it's declared on the main page of documentation.

**So, is MLeap a "format" or just a serialization tool? Can I found a format definition or schema somewhere?**

And again, my purpose is to understand if it's possible to write a custom serialization/deserialization tool for MLeap *format* or the only option is to use MLeap tools for that?

  [1]: http://mleap-docs.combust.ml/
  [2]: http://mleap-docs.combust.ml/core-concepts/mleap-runtime.html

**Comment by a-p-o** [comment]
@dmitrievanthony there is a repository with protobufs for how to serialize a bundle: https://github.com/combust/bundle-protobuf/ Is this what you're looking for?

**Comment by ancasarb** [comment]
Yes, the schema for the mleap format is located https://github.com/combust/bundle-protobuf/.

Closing this for now, please re-open if you have any additional questions.
