### ISSUE TITLE
Spark 2.4.0 Support

### ISSUE THREAD

**Issue by jwgwalton** [combust/mleap#480]
As stated in issue title. It would be great to support the latest version of spark.

**Comment by samikrc** [comment]
Are you using any Spark 2.4 specific feature? I have also updated to Spark 2.4.0, and although I am currently stuck with #479, I don't foresee any issue as long as features from older Spark versions are used.

**Comment by jwgwalton** [comment]
@samikrc i don't need any particular 2.4.0 functionality but i was getting an unsupported error for spark 2.4.0.

**Comment by RogPodge** [comment]
+1 On this initiative. This issue also needs to be addressed by this upgrade

https://github.com/combust/mleap/issues/484

**Comment by samikrc** [comment]
I have things working for most of the functionality, with Spark 2.4.0 components as dependency (#479  is now resolved). Are you doing things differently than the code I have here: [https://github.com/samikrc/try-mleap] ? Are you using through Scala or Python? At least with Scala, I have many pipelines working with Spark 2.4.0 and mleap 0.13, as shown at [https://github.com/samikrc/try-mleap/blob/master/src/test/scala/com/tfs/test/CommonModelsSpec.scala].

**Comment by ancasarb** [comment]
Raised https://github.com/combust/mleap/pull/493 for Spark 2.4 support.

**Comment by ancasarb** [comment]
@jwgwalton @samikrc @RogPodge support for spark 2.4 has been released in version 0.14.0.

**Comment by jwgwalton** [comment]
Cheers @ancasarb
