### ISSUE TITLE
serializeToBundle doesn't work on Spark2.4

### ISSUE THREAD

**Issue by RogPodge** [combust/mleap#484]
The serializeToBundle function doesn't work with Spark2.4 due to the underlying implementation uysing org.apache.spark.ml.feature.OneHotEncoder, which has now been [deprecated](https://spark.apache.org/docs/latest/api/java/org/apache/spark/ml/feature/OneHotEncoder.html)

Error message:
```
Traceback (most recent call last):
  File "/mleap/mleap_demo_pyspark.py", line 182, in <module>
    sparkPipelineLr.serializeToBundle("jar:file:{}".format(lrZip), sparkPipelineLr.transform(dataset_imputed))
  File "/usr/local/lib/python3.5/dist-packages/mleap/pyspark/spark_support.py", line 25, in serializeToBundle
    serializer.serializeToBundle(self, path, dataset=dataset)
  File "/usr/local/lib/python3.5/dist-packages/mleap/pyspark/spark_support.py", line 42, in serializeToBundle
    self._java_obj.serializeToBundle(transformer._to_java(), path, dataset._jdf)
  File "/spark/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py", line 1257, in __call__
  File "/spark/python/lib/pyspark.zip/pyspark/sql/utils.py", line 63, in deco
  File "/spark/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py", line 328, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o1043.serializeToBundle.
: java.util.NoSuchElementException: key not found: org.apache.spark.ml.feature.OneHotEncoder
```

Here is a link to the relevant [Mleap code](https://github.com/combust/mleap/blob/master/python/mleap/pyspark/spark_support.py)

**Comment by ancasarb** [comment]
Hey, even with Spark 2.3 MLeap 0.13 only supports OneHotEncoderEstimator (the not-deprecated one hot encoder) and not the deprecated OneHotEncoder.

**Comment by RogPodge** [comment]
If mleap 0.13 still doesn't use the OneHotEncoder, then where do you think the error message is coming from? 

This was the command I used to run my mleap code: 

/spark/bin/spark-submit --packages org.apache.spark:spark-avro_2.11:2.4.0,ml.combust.mleap:mleap-spark_2.11:0.13.0 --master yarn --deploy-mode client /mleap/mleap_demo_pyspark.py

**Comment by RogPodge** [comment]
I figured out the issue. We were still using the OneHotEncoder Transformer and mistakenly thought that the issue was on the MLeap side of things
