### ISSUE TITLE
the version of the mleap Python package does not match the version of the mleap jars.

### ISSUE THREAD

**Issue by lgongmsft** [combust/mleap#485]
I noticed that the version of the mleap Python package does not match the version of the mleap jars

https://github.com/combust/mleap/blob/30c1ce2c7e5ca81492514e1eadd79a8ec1b10a7a/python/mleap/version.py#L19
https://github.com/combust/mleap/blob/30c1ce2c7e5ca81492514e1eadd79a8ec1b10a7a/version.sbt#L1

Is this intentional?  Would it be easier for user to deal with those two separate pieces if their versions match?

**Comment by ancasarb** [comment]
@lgongmsft I am planning on releasing a new version of the scikit-learn package, once I do that, I will update the versions to match.

**Comment by ancasarb** [comment]
I've release the python mleap version 0.15.0 just today, fyi https://pypi.org/project/mleap/#history, please let me know if you see any issues.
