### ISSUE TITLE
Type casting between raw input and mleap-serialized models

### ISSUE THREAD

**Issue by FredYao** [combust/mleap#486]
I trained a pipeline in Spark and successfully serialized it through MLeap. When I tried to use the serialized MLeap pipeline at runtime, some strange type casting error occurs. Then I checked the raw input schema and MLeap-pipeline schema, found some discrepancy:
`
Input schema of raw input data:
root
 |-- C1: string (nullable = true)
 |-- C2: string (nullable = true)
 |-- C3: double (nullable = true)
 |-- **C4: float** (nullable = true)
 |-- C5: string (nullable = true)
 |-- **C6: float** (nullable = true)

Input schema of mleap-pipeline
root
 |-- C1: scalar(base=string,nullable=true)
 |-- C2: scalar(base=string,nullable=true)
 |-- C3: scalar(base=double,nullable=true)
 |-- **C4: scalar(base=double**,nullable=true)
 |-- C5: scalar(base=string,nullable=true)
 |-- **C6: scalar(base=double**,nullable=true)
`

Two columns of raw input were supposed to be FLOAT type (in Spark dataframe), however, when I printed the serialized MLeap pipeline's input schema, the corresponding two columns were DOUBLE type. Does anybody know why the implicit type casting happened?

**Comment by ancasarb** [comment]
Hey @FredYao which transformer is using these  C4 & C6 columns?

**Comment by FredYao** [comment]
@ancasarb, only VectorAssembler was called to assemble all C1 to C6 columns. There was no other particular transformer applied on C4 & C6.

**Comment by ancasarb** [comment]
What you're actually seeing is the schema of the pipeline, in your case just the VectorAssembler, which in this case its input schema is defined as a series of double inputs https://github.com/combust/mleap/blob/d276c1c800277a1edcf30dda6e8559c7413b21f8/mleap-core/src/main/scala/ml/combust/mleap/core/feature/VectorAssemblerModel.scala#L93. Each of the models has an input/outputs schema. 

If there's any casting required, MLeap handles it here https://github.com/combust/mleap/blob/15e8dd3bfa47c957f7773eb020f2f776dbd1ddad/mleap-core/src/main/scala/ml/combust/mleap/core/types/Casting.scala. 

Hope this helps!

**Comment by ancasarb** [comment]
Closing this, please feel free to re-open if you still have additional questions. Thank you!
