### ISSUE TITLE
Where are the mleap jar files installed when using pip install mleap?

### ISSUE THREAD

**Issue by jeffsaremi** [combust/mleap#487]
It looks like some jar files are missing because I get this error on serialization:
```
  File "C:\Users\jesaremi\AppData\Local\Continuum\anaconda3\envs\py3.6\lib\site-packages\mleap\pyspark\spark_support.py", line 39, in __init__
    self._java_obj = _jvm().ml.combust.mleap.spark.SimpleSparkSerializer()
TypeError: 'JavaPackage' object is not callable
```
I searched under site_packages in my environment and I can see mleap and its python files however can't find any jar files so I can add them to the library path.

Are these available as a separate download?

**Comment by jeffsaremi** [comment]
Just adding some version numbers:
python: 3.6
pyspark: 2.3.2
mleap: 0.18.1

**Comment by ancasarb** [comment]
The jars can be downloaded from Maven: https://mvnrepository.com/artifact/ml.combust.mleap. You're likely going to be interested in the mleap-spark, mleap-spark-extension or mleap-runtime dependencies. 

In maven, if you include mleap-spark-extension dependency, it will transitively bring in the others.

**Comment by ancasarb** [comment]
Closing this, please re-open if you have any additional questions.
