### ISSUE TITLE
Difference between docker images

### ISSUE THREAD

**Issue by jwgwalton** [combust/mleap#494]
There are 2 docker images 
combustml/mleap-serving
combustml/mleap-spring-boot

from what i can tell these now share the same API in the latest versions (0.13.1-SNAPSHOT). Could someone clarify if there are any differences. It would be simpler for people looking to get started if the difference are documented.

Also the documentation for mleap-serving is out of date in http://mleap-docs.combust.ml/mleap-serving/. This works for the 0.9.0 tag of mleap-serving  but not the latest. 

i've tested the documentation https://github.com/combust/mleap/tree/master/mleap-spring-boot, it is correct for both images and i would recommend it being put into the main documentation.

**Comment by ancasarb** [comment]
Hey @jwgwalton,

combustml/mleap-serving starts both the gRPC server and HTTP server, using a single MLeap executor whereas combustml/mleap-spring-boot starts only the HTTP server. Indeed, the HTTP API in both cases is the same. 

We have https://github.com/combust/mleap-docs/pull/17 raised to update the main documentation, in the meantime, you can take a look at the documentation in the sub projects, that should already be up to date.

**Comment by jwgwalton** [comment]
Cheers @ancasarb
