### ISSUE TITLE
How to make mleap spark extension usable in pyspark or make customized transformer available in pyspark?

### ISSUE THREAD

**Issue by xmzhu002552** [combust/mleap#495]
Is there anyway to make customized transformer available in pyspark? Currently, examples provided for customized transformers (like StringMap, MathBinary etc) can only be used in scala, not in pyspark? I wonder whether it is possible to create customized transformer to be used in pyspark? 
thanks

**Comment by xmzhu002552** [comment]
Thanks for the reply but only answer attached in issue 294 seems dead. Do you have any update link for that? thanks

**Comment by xmzhu002552** [comment]
I tried to follow the example OneHotEncoder provided in the link. It seems the difficulties of making MathBinary available for pyspark is to use py4j to create a MathBinary object, which is a wrapper of MathBinaryModel. In order to create MathBinaryModel, we need BinaryOperation object, I wonder how this embedded class can be created through py4j. Any suggestion is greatly appreciated? Thanks

**Comment by xmzhu002552** [comment]
I finally found out a way to create customized transformer in Mleap and can be used in pyspark. It takes quite a bit work but it works. The path is: a, create a customized spark transformer without using any 'embedded' mleap transformer. This transform can be used in pyspark.  How? Just follow any transformer implementation in spark.  b, create a related mleap transformer. c, modify the registry.  Just like mleap creates its own Binarizer transformer while there is an implementation in spark. 

The StringMap example provided by the doc (http://mleap-docs.combust.ml/mleap-runtime/custom-transformer.html) is surely not for using in pyspark but it provides a way about how to build a customized transformer in Mleap. As mentioned above, it is nearly impossible for MathBinary to be used in pyspark because it employs the 'embedded Mleap class' pattern (guess this way saves some logic re-implementation). In order to make transformer usable in pyspark, 'embedded Mleap class' pattern is not recommended.

**Comment by yairdata** [comment]
@xmzhu002552 - can you share more detailed solution for pyspark custom transformer support in mleap ?
an example will be highly appreciated.

**Comment by mtsol** [comment]
@xmzhu002552 can you please share further details about this?

**Comment by juhoautio** [comment]
I ended up writing this pyspark wrapper for mleap's StringMap transformer:

https://github.com/juhoautio/NotebookTest/blob/89ca52048297f09cfdff8008f20465d9d01ddad5/mleap_stringmap_python_wrapper.ipynb

**Comment by ancasarb** [comment]
@xmzhu002552 @yairdata As we're starting to add support for spark-extensions transformers in Pyspark, I've created https://github.com/combust/mleap/issues/570 to track this development, could you please follow that issue and add comments or questions to it regarding custom transformers in Pyspark? Thank you!
