### ISSUE TITLE
Is there a general rule for creating customized mleap transformers?

### ISSUE THREAD

**Issue by FredYao** [combust/mleap#503]
Mleap supports all standard spark machine learning models. There could be use cases that a user train a model though his own implemented machine learning algorithm. Wondering if there is a general rule to follow for creating a mleap transformer for that own-implemented machine learning algorithm? Basically, I want to know what classes need to be created or modified?

**Comment by marsbible** [comment]
read the doc, refer to xgboost module

**Comment by ancasarb** [comment]
Hey @FredYao http://mleap-docs.combust.ml/mleap-runtime/custom-transformer.html describes what is required for custom transformers, it would be the same classes required regardless whether the transformer has some ml algorithm or is doing some feature processing.
 
Hope that helps,
Anca

**Comment by ancasarb** [comment]
Closing this, please re-open if you still have any questions.
