### ISSUE TITLE
SparkNodeWrapper issue in setting prediction value in Leaf Node

### ISSUE THREAD

**Issue by siddhant0509** [combust/mleap#506]
In SparkNodeWrapper class leaf node is set like this 
`new tree.LeafNode(prediction = node.values.indexOf(node.values.max),
      impurity = 0.0,
      impurityStats = calc)`

`node.values.indexOf(node.values.max)` is just going to find the index of the max value but not set it.

**Comment by ancasarb** [comment]
@siddhant0509 Thanks for raising this, indeed that line should say ````new tree.LeafNode(prediction = node.values.max, impurity = 0.0, impurityStats = calc)```. We will try to merge the fix as part of https://github.com/combust/mleap/pull/522 which addresses a few other spark deserialization issues. 

Thanks again for raising this issue.

**Comment by ancasarb** [comment]
Fixed as part of https://github.com/combust/mleap/pull/522, will be released with the new version of mleap.
