### ISSUE TITLE
load Model via http uri 

### ISSUE THREAD

**Issue by salimngit** [combust/mleap#513]
I'm able to successfully load model (HTTP 202) when I HTTP POST the below body

{"modelName":"testmodel","uri":"http://{DATABRICKS_INSTANCE}/files/{MODEL_EXPORT_PATH}?o={DATABRICKS_ORG}","config":{"memoryTimeout":900000,"diskTimeout":900000},"force":true}

however when I query the model's availability i.e. 

GET /models/testmodel/meta

I receive HTTP 404 and the below exception in the shell

ml.combust.mleap.executor.error.NotFoundException: no model with name testmodel

**Comment by salimngit** [comment]
After further investigating model download via wget, I saw that downloading model directly from databrick's Filestore responds with HTTP 303 redirect before the bundle .zip file is downloaded. Does anyone have a workaround how to enable follow redirect URI load via Mleap?

**Comment by 0xbliang** [comment]
the [doc](https://github.com/combust/mleap/tree/master/mleap-spring-boot#available-endpoints) suggests you need to specify the following header, even for GET:
Content-Type: application/json

**Comment by salimngit** [comment]
I specify Content-Type: application/json during model query (i.e. GET /models/{model_name}/meta. however the issue is unrelated to model query but rather model load. the initial model load via HttpRepository doesn't cater for URL redirects which databricks responds back with when you're loading models from dbfs Filestore in my case http://{DATABRICKS_INSTANCE}/files/{MODEL_EXPORT_PATH}?o={DATABRICKS_ORG}.

**Comment by a-p-o** [comment]
@salimngit, based on my experience, the 202 response code is a lie. There is an error which is not logged. You can print this log by applying this change: https://github.com/a-p-o/mleap/commit/ee2817719b5488a776ab614c9467aaa711c6a8d4

**Comment by ancasarb** [comment]
@a-p-o I think this is a slightly different issue, will take a look at the HttpRepository separately. 

Please note the difference between 202 (Accepted) and 200 (OK). When loading a model, the response you get is 202, accepted, meaning that the server will try to load a model, but it doesn't necessarily mean that it has loaded successfully. You can do a further get to get the model to check whether model's loaded alright. 

Regarding the logging changes, we can definitely improve what gets logged, if you want to raise a PR for that, will be happy to take a look!

Hope this helps,
Anca

**Comment by m-niharika** [comment]
Facing the same issue.
Post Request return the status (HTTP 202),

But GET /models/{modelname}/meta returns the status as (HTTP 404) 
Error : ml.combust.mleap.executor.error.NotFoundException: no model with name {modelname}

**Comment by ancasarb** [comment]
@m-niharika apologies for the delayed response, is still still an issue? have you checked that the logs don't show any errors/exceptions?

**Comment by preet3loq** [comment]
Facing the similar issue.
ml.combust.mleap.executor.error.NotFoundException: no model with name rf

**Comment by eng56** [comment]
Also facing the similar issue

**Comment by a-p-o** [comment]
@preet3loq, @eng56, it works. If you need help, then you need to provide a way to reproduce. I can say from personal experience that loading a model works.

**Comment by ancasarb** [comment]
Closing for now, as it doesn't seem to pose an issue anymore, please reopen / open another one if you are still encountering issues.
