### ISSUE TITLE
mleap-serving: max value for memoryTimeout is too restricted

### ISSUE THREAD

**Issue by 0xbliang** [combust/mleap#516]
I found that if you don't specify a memoryTimeout, the model will be evicted/unloaded after idling for 15 minutes. Then you can't use the model anymore.

So, I tried to set it to as large as I can:
```bash
curl -v -XPOST -H "content-type: application/json" -d '{"modelName":"foo","uri":"file:/my-model/bundle.zip","config":{"memoryTimeout":9223372036854,"diskTimeout":9223372036854}}' http://localhost:8080/models
```
But when I made the transform/scoring request, the server side console log said:
```
[ERROR] [04/19/2019 00:35:32.287] [MleapGrpc-akka.actor.default-dispatcher-4] [akka.actor.ActorSystemImpl(MleapGrpc)] Uncaught error from thread [MleapGrpc-akka.actor.default-dispatcher-4]
java.lang.IllegalArgumentException: Task scheduled with [9223372036] seconds delay, which is too far in future, maximum delay is [21474835] seconds
```
21474835 seconds ~= 8 months. That's very limiting. Can we specify a very large timeout, or is there a way to tell it not to unload/evict the model?

**Comment by ancasarb** [comment]
Hey @0xbliang, the timeout will be triggered if the model is idle (i.e. no requests, for e.g. transform requests) for around 8 months, what would be a use case to keep a model loaded in memory for that long without any requests going to it?

**Comment by 0xbliang** [comment]
You are right, in that case, it's sufficient. Closing issue. Sorry for the delayed response.
