### ISSUE TITLE
Change the dependency type of the 'nose-exclude' package

### ISSUE THREAD

**Issue by AlirezaAlizadeh** [combust/mleap#519]
Currently, in the mleap python package, the `nose-exclude` package is listed as a required package for installation. Since `nose-exclude` is required for the tests, it should be added to the `tests_require` package to reduce the irrelevant packages for the installation and production.

Moreover, this can eliminate the extra licensing concerns to use the mleap python distribution.

**Comment by ancasarb** [comment]
Thanks for fixing this, I've merged the PR :)

**Comment by AlirezaAlizadeh** [comment]
Thanks for accepting the fix @ancasarb. Would you please let me know when would be the next release? That would relay help us in integrating the mleap within our platform. 
Overall, I would appreciate if you make a patch release in case the next release will take a long time.
