### ISSUE TITLE
handleInvalid param not retained across serialization/deserialization of Spark Bucketizer

### ISSUE THREAD

**Issue by mikejonesyjones** [combust/mleap#521]
[BucketizerModel](https://github.com/combust/mleap/blob/master/mleap-core/src/main/scala/ml/combust/mleap/core/feature/BucketizerModel.scala) does not support handleInvalid (this makes sense since the SparkCode annotation says that the code is based on Spark 2.0.0 and the handleInvalid param was not added until v2.1.0).

I can see a similar ticket from when support for handleInvalid was added to StringIndexerModel: https://github.com/combust/mleap/issues/180

**Comment by ancasarb** [comment]
Hey @mikejonesyjones, thanks for creating the issue. There's some work being done currently to fix de-serialization of some of the transformers back into Spark, once that's completed, I'll take a look at adding the handleInvalid for Bucketizer and actually VectorIndexer needs it too. Thanks again!

**Comment by ancasarb** [comment]
PR merged to add the fix, closing this.
