### ISSUE TITLE
Support for custom transformer having only input columns:

### ISSUE THREAD

**Issue by MUdhay** [combust/mleap#523]
We have been planning to use a custom transformer that performs inplace transformation, and this basically doesn't involve creation of a new column by the transformer. All the examples which are provided in the custom transformer section in mleap have considerd transformers that have an input and an output column. As a result, all the classes which have been used for serailizing the spark transformers uses those inbuilt traits which expect the output column to be present. If I want to have my own custom traits, then that involves a lot of file addition in my code base. Is there any better way of doing this? Thanks for any input

**Comment by ancasarb** [comment]
Just wanted to double check, what would be the benefit for not creating the output column? Thank you!

**Comment by ancasarb** [comment]
closing this, please re-open if you have further thoughts on this.
