### ISSUE TITLE
mleap-spring-boot: Load model(s) when process starts

### ISSUE THREAD

**Issue by danielpoonwj** [combust/mleap#525]
We've been working on productionizing some models with `mleap-spring-boot`, and a pain point we've been facing is in regards to easily loading models during deployment.

On a EC2 based AWS infrastructure with a load balancer and autoscaling, we aren't able to reliably send external HTTP requests to load models for every instance due to load balancing, and instances may be added/removed at any time due to autoscaling. The workaround we adopted was to periodically scan for models on disk (mounted from S3 with `s3fs`) and send a localhost curl request within each instance. This works when autoscaling spins up new instances, or if the spring boot process restarts with `systemd`, but isn't ideal and quite brittle (eg. if the load model request fails on some instances resulting in inconsistencies).

We've been exploring a `docker` based workflow which has one model per container, rebuilding the image whenever the model is updated. The issue of loading the model when the container starts is all the more important as we're not keen on running an additional background process within the container to load models after the spring boot process has started.

Are there any features in the pipeline that may support watching/hot reloading models from a directory, or explicitly specifying models to load when starting the spring boot process?

**Comment by ancasarb** [comment]
Hey @danielpoonwj, thanks for raising this issue, all valid points. I think it shouldn't be too complicated to add this functionality, we could, for example, have a Spring @Component that has a @PostConstruct method that loops through files in a specified local directory and loads the models in? What do you think? Happy to work with you if you're interested in contributing to add this in mleap-spring-boot.

**Comment by danielpoonwj** [comment]
Thanks for your reply @ancasarb! I'll definitely like to contribute, but I may need some help advising and reviewing along the way as I've got limited experience with this framework. I'll look into the `@PostConstruct` approach and raise any issues if I encounter any.

**Comment by ancasarb** [comment]
PR merged, will be included in the new release

**Comment by cappaberra** [comment]
@ancasarb, do you anticipate writing accompanying documentation for this feature?  It sounds interesting for sure.  We currently use a complimentary tool that helps manage the state of MLeap (kind of wraps around MLeap in a way), so we always know what models are running.  That said, it looks like this functionality could be useful, too, in a more native way!

**Comment by ancasarb** [comment]
hey @cappaberra, I've updated the doc in this PR https://github.com/combust/mleap/pull/589. thanks!
