### ISSUE TITLE
Is it possible to store some meta-info about features?

### ISSUE THREAD

**Issue by FredYao** [combust/mleap#527]
I realized that bundle has a meta-info object. Is there a way to store some meta-info about each feature (i.e., features used for training ML models)? 

In Spark. StructField has a 4th argument Metadata. But I am not sure MLeap has such a thing? Or any equivalence? 

Thanks!

**Comment by ancasarb** [comment]
I don't think there's a metadata field for fields in MLeap, what type of information were you thinking of being to store for features?

**Comment by FredYao** [comment]
@ancasarb , thanks for your response. I found Spark's StructField provides a flexibility to store some meta-info about acolumn/feature. So I tried to see if MLeap has a similar functionality or not.

I have a use case: deploy a MLeap model into a online serving environment which serves requests in a very low latency manner. The data used for training is not quite consistent with the data used for online serving. For example, feature names or data types used in offline training could be different from those used in online serving. I am seeking a way to store each feature's info somewhere and let online environment parse it, then online environment will be able to know what feature to extract for a certain offline feature and what data type to use for a certain offline feature.

**Comment by ancasarb** [comment]
@FredYao Upon closer inspection, it is indeed possible to set some meta information about the bundle, for e.g.

```
      val f = new File(s"/tmp/model.zip")
      val bundle: Bundle[Transformer] = (for (bf <- managed(BundleFile(f))) yield {
        bf.loadMleapBundle().get
      }).tried.get
      
      bundle.info.meta
```

You can see [here](https://github.com/combust/bundle-protobuf/blob/master/bundle/bundle.proto#L130) about the format, I believe this supports your use-case.

**Comment by ancasarb** [comment]
Closing this in preparation of release 0.16.0, hopefully the classification above makes sense, please reopen if you have further questions. Thank you!
