### ISSUE TITLE
String transformation options?

### ISSUE THREAD

**Issue by zjost** [combust/mleap#529]
I am wondering if there's a simple way to apply user defined, Map-like operations (which don't require "fitting").  For instance, if I have a column of strings and want to lowercase, do I need to build a Custom Transformer with all the associated overhead, or is there some simple way to e.g. serialize trivial scala code?

**Comment by ancasarb** [comment]
The other bits of code are required for serialization/deserialization, for example, to track what are the inputs/outputs for the transformers. 

We have created a few traits that hopefully reduces the boilerplate code somewhat. For transformers, we have the traits BaseTransformer, SimpleTransformer or MultiTransformer. For Ops, we have MleapOp or SimpleSparkOp. 

Hope this helps!

**Comment by ancasarb** [comment]
Closing this in preparation of release 0.16.0, hopefully the clarification above makes sense, please reopen the issue if you still have further questions. Thank you!
