### ISSUE TITLE
Help writing custom transformer in mLeap

### ISSUE THREAD

**Issue by femibyte** [combust/mleap#542]
I am working with mLeap and need to write a custom transformer to serialize
a Spark ML pipeline that makes use of SQLTransformer.

I have written the Custom Transformer and its transform function looks like this:

  
 ```
class MyCustomSQLTransformer(override val uid: String)
      extends Transformer {
      ...
      override def transform(dataset: Dataset[_]):DataFrame 
      = {
         val transformed Schema = 
              transformSchema(dataset.schema)
         val df = dataset.toDF()
         val df1 = df.withColumn("statePop_tmp",
                         when($"state"==="CA", $"CA_Pop")
                         when($"state"==="NY", $"NY_Pop")
                         when($"state"==="TX", $"TX_Pop")
                         when($"state"==="FL", $"FL_Pop")
                         when($"state"==="PA", $"PA_Pop")
                       )
         val df2 = df1.withColumn("statePop",
                       when("statePop_tmp".isNull, 
                             $"Default_Pop")
                        .otherwise("$statePop_tmp"))
         val resDF=df2.drop("statePop_tmp").toDF()
         resDF

            ...
          }

         }

```
I'm wondering how to write an Mleap core model for the above.
Specifically, what should the `apply()` function of the case class look like ?

Based on the docs here the core logic is the logic needed to transform
the data. Hence should the apply function mimic the ` transform()` function above?
The transform function above takes in a Dataset and returns a DataFrame.
What should be the input and output for the ` apply()` function ?
Any help you can provide will be greatly appreciated.

**Comment by ancasarb** [comment]
Hey @femibyte, how about breaking it down into two transformers:

1. You could have a more straightforward custom transformer

```
// knownStates = "CA", "NY", "TX", "FL", "PA"
case class StateModel(knownStates: List[String]) extends Model {

  def apply(state: String): String =
    if (knownStates.contains(state)) state else "DEFAULT"

  override def inputSchema: StructType = StructType("input" -> ScalarType.String.nonNullable).get

  override def outputSchema: StructType = StructType("output" -> ScalarType.String.nonNullable).get
}
```

that basically just replaces all other states except "known states" with a "DEFAULT" string.

2. As a second transformer, I think you can use string map model / transformer https://github.com/combust/mleap/blob/master/mleap-core/src/main/scala/ml/combust/mleap/core/feature/StringMapModel.scala that mleap already has? 

You could configure it with something like this 
```
new StringMapModel(Map("CA" -> 23321312, "NY" -> 54353, "TX" -> 543534, "FL" -> 54534, "PA" -> 23534534)
```

replacing the values with the accurate population counts. 

Let me know what you think!

**Comment by femibyte** [comment]
So I will then have 2 model classes (StateModel and StringMapModel) that I can reference in the Mleap Transformer, Mleap Serialization and Spark Serialization classes as documented here ?

https://github.com/combust/mleap-docs/blob/master/mleap-runtime/custom-transformer.md

**Comment by ancasarb** [comment]
Yep, the first one (StateModel) you'll need to build the transformers + serialization as described in that guide, the second one (StringMap + StringMapModel) is already built so you can just use it.

**Comment by femibyte** [comment]
So how many Mleap Transformer, Mleap Serialization and Spark Serialization classes do I need to write, 2 of each ? And what about the Bundle registries ?

**Comment by femibyte** [comment]
I guess a larger question for me is how the Spark Transformer which takes a Dataset and returns a Dataframe is supposed to map to the Mleap model class. That isn't really clear to me based on the available examples & documentation. If I understood that, things would be a lot clearer.

**Comment by ancasarb** [comment]
you'll need to write:
1. model class (the one I shared above)
2. Mleap transformer
3. Spark transformer
4. Mleap op - mainly used to deserialize into mleap (but can also serialize)
5. Spark op - mainly used to serialize from Spark (can also deserialize)
6a. update mleap registry, i.e. reference.conf (used at scoring time)
6b. update spark registry

Mleap (and custom transformers implicitly) operate on a row by row basis, so it's not possible at the moment to do column-based operations, which is why you won't be able to have as input a whole dataframe.

**Comment by femibyte** [comment]
Ok, so assuming I wrote the StateModel class, where/how does the StringMapModel class get used ?
Which class gets referenced in the Mleap op and Spark op classes for example - StateModel or StringMapModel ?

**Comment by femibyte** [comment]
Also, the SQL transformer checks the value of the state column and based on that value, specifies which column of the dataframe to return i.e. CA_Pop, NY_Pop, TX_Pop etc. Is that captured adequately by the StateModel class ? It maps a string to a string and the StringMapModel maps a String to an Integer constant. But the Spark SQL Transformer maps a column to another column. How does the translation happen ?

**Comment by ancasarb** [comment]
You could have a pipeline that looks like this

```
 val pipeline: Transformer = new Pipeline().setStages(Array(
new StateTransformer( model = new StateModel(List("CA", "NY", "TX", "FL", "PA"))).setInputCol("state").setOutputCol("transformed_state")),
    new StringMap(model = new StringMapModel(
      Map("CA" -> 23321312, "NY" -> 54353, "TX" -> 543534, "FL" -> 54534, "PA" -> 23534534, "DEFAULT" -> 2343243)
    )).setInputCol("transformed_state").setOutputCol("population"))).fit(dataset)
```

I think this would work based on the assumption the population for California is the same regardless whether that state "CA" is in row 4 or row 9 for e.g. right?

**Comment by femibyte** [comment]
So would the Mleap Transformer look like this ?
```
import ml.combust.mleap.core.feature.StringMapModel
import ml.combust.mleap.core.types.NodeShape
import ml.combust.mleap.runtime.function.UserDefinedFunction
import ml.combust.mleap.runtime.transformer.{SimpleTransformer, Transformer}
import my.package.StateModel

case class StateMap(override val uid: String = Transformer.uniqueName("string_map"),
                     override val shape: NodeShape,
                     override val smapModel: StringMapModel,
		     override val stateModel: StateModel) extends SimpleTransformer {
  override val exec: UserDefinedFunction = (state: String) => smapModel(stateModel(state))
```

**Comment by femibyte** [comment]
> You could have a pipeline that looks like this
> 
> ```
>  val pipeline: Transformer = new Pipeline().setStages(Array(
> new StateTransformer( model = new StateModel(List("CA", "NY", "TX", "FL", "PA"))).setInputCol("state").setOutputCol("transformed_state")),
> new StringMap(model = new StringMapModel(
>       Map("CA" -> 23321312, "NY" -> 54353, "TX" -> 543534, "FL" -> 54534, "PA" -> 23534534, "DEFAULT" -> 2343243)
>     )).setInputCol("transformed_state").setOutputCol("population"))).fit(dataset)
> ```
> 
> I think this would work based on the assumption the population for California is the same regardless whether that state "CA" is in row 4 or row 9 for e.g. is that right?

Yes, each row would represent the CA population for a separate metric e.g. population of cars for 1 row, population of persons, amount of emissions etc.

**Comment by femibyte** [comment]
Can I just combine them into 1 transformer in the Model file if I did something like:
```
case class StateModel(knownStates: List[String]) extends Model {
def apply(state: String): String =
    if (knownStates.contains(state)) StringMapModel.apply(state) else "DEFAULT"
```

**Comment by ancasarb** [comment]
I guess you could do that, though not sure there's a lot of improvement from doing both transformations in one go.

**Comment by femibyte** [comment]
@ancasarb  I've now written all the required classes and I'm trying to build using sbt.
However I get this error:

`[info] Compiling 8 Scala sources to 
~/mleap_custom_sql_transformer/target/scala-2.11/classes...
[error] /home/hadoop/femi/mleap_custom_sql_transformer/src/main/scala/MerchAggSelectionMleapOp.scala:21: value state_mod is not a member of object ml.combust.bundle.dsl.Bundle.BuiltinOps.feature
[error]     override def opName: String = Bundle.BuiltinOps.feature.state_mod`

Can you advise ? The line above is in the examples:

    ```// a unique name for our op: "string_map"
    // this should be the same as for the MLeap transformer serialization
    override def opName: String = Bundle.BuiltinOps.feature.string_map```

**Comment by ancasarb** [comment]
You can just do ```override def opName: String = "state_mod"```

**Comment by femibyte** [comment]
I realized that I had to add this line

`var state_mod = "state_mod"`

in 

_bundle-ml/src/main/scala/ml/combust/bundle/dsl/Bundle.scala_

and then rebuild the jar

**Comment by ancasarb** [comment]
@femibyte glad you got it working, is it ok to close this issue?

**Comment by ancasarb** [comment]
Closing this issue for now, please re-open if you're still having problems.
