### ISSUE TITLE
Question: Proper way to get schema for row transformer?

### ISSUE THREAD

**Issue by rickbassham** [combust/mleap#548]
Note that all of my code to do what I'm doing is located at https://gist.github.com/rickbassham/0b8a76b9e2dfd83d2279d0ccb8f897e3 using the `airbnb.model.rf.zip` located at https://raw.githubusercontent.com/combust/mleap/master/mleap-benchmark/src/main/resources/models/airbnb.model.rf.zip.

My question is, what is the proper way to get the schema of a row returned by a RowTransformer? I've started by loading the model and getting the root `Transformer`. Then I create a `RowTransformer` from that root `Transformer`, passing in the `inputSchema` from the root `Transformer`. When I transform that row with the `RowTransformer`, the resulting row has 22 fields, which does not match the `outputSchema` from the root `Transformer` (that has 9 fields). Doing some more digging, the root `Transformer` has a `schema` function that does return 22 fields. However, the order of the fields does not match the order of the fields in the row that is returned by the `RowTransformer`. In the output of the linked gist, the value at index 20 of the row returned is of type `DenseTensor([D@5261ec9,List(13))`, but the data type of index 20 in the full schema is `ScalarType(double,false)`.

I found a way around this by first executing the model with a full frame, and getting the schema from that frame. Is there a better way of doing this?

**Comment by ancasarb** [comment]
I believe that what you're looking for is:

```       
List<StructField> rowTransformerFields = JavaConversions.seqAsJavaList(rt.schema().fields());
```

And then you should update the printing to:

```
        for (int i = 0; i < result.size(); i++) {
            Object val = result.getRaw(i);

            if (val == null) {
                System.out.println(String.format("%s | %s", rowTransformerFields.get(i), null));
            } else {
                System.out.println(String.format("%s | %s", rowTransformerFields.get(i), val.toString()));
            }
        }
```

The issue was that you were trying to use the schema of the deserialized transformer when iterating over the row resulting from the row transformer transformation. 

Let me know if you have further questions!

**Comment by ancasarb** [comment]
Closing this, please re-open if you have additional questions!
