### ISSUE TITLE
Python wrapper for Custom transformer

### ISSUE THREAD

**Issue by femibyte** [combust/mleap#552]
I'm trying to write a Python wrapper for a custom transformer that I have built in Scala based on 
this article:

https://github.com/combust/mleap-docs/blob/master/mleap-runtime/custom-transformer.md

Thus my Spark transformer looks like this

```
class MyTransformer(override val uid: String,
                val model: MyTransformerModel) extends Transformer
       def this(model: MyTransformerModel) = this(uid = 
              Identifiable.randomUID("mytrans"), model = model)
```

I am now trying to write a Python wrapper so I can use it in and serialize it to mleap in Pyspark.

I've taken a look at the Pyspark wrappers for standard Spark transformers and they all look like this in `python/pyspark/ml/feature.py`:

```
def __init__(self, threshold=0.0, inputCol=None, outputCol=None):
        """
        __init__(self, threshold=0.0, inputCol=None, outputCol=None)
        """
        super(Binarizer, self).__init__()
        self._java_obj = self._new_java_obj("org.apache.spark.ml.feature.Binarizer", self.uid)
```

However the implementation of Binarizer for example, doesn't take the model as an argument in the way the mleap example StringMap does:

mllib/src/main/scala/org/apache/spark/ml/feature/Binarizer.scala

```
final class Binarizer @Since("1.4.0") (@Since("1.4.0") override val uid: String)
  extends Transformer with HasInputCol with HasOutputCol with DefaultParamsWritable {

  @Since("1.4.0")
  def this() = this(Identifiable.randomUID("binarizer"))
  ...
```
My question is how I handle the model in the wrapper class. There is no example code anywhere in the mleap docs that shows how to handle that.

I've tried the following:

```

class MyTransformer(JavaTransformer, HasInputCols, HasOutputCols, 
	                                    JavaMLReadable, JavaMLWritable):

    @keyword_only
    def __init__(self, inputCols=None, outputCols=None):
        super(MyTransformer, self).__init__()
        fully_qual_class = "com.mydomain.MyTransformer"
        self._java_obj = self._new_java_obj(fully_qual_class, self.uid, self.model)
        kwargs = self._input_kwargs
        self.setParams(**kwargs)
```

but I get this error:

`AttributeError: 'MyTransformer' object has no attribute 'model'`

Should I write a wrapper for MyTransformerModel as well, or are there better ways to do this?
An example would be most welcome.

**Comment by femibyte** [comment]
@ancasarb

**Comment by mtsol** [comment]
I also need help regarding this, because there is not much documentation available for pyspark

**Comment by juhoautio** [comment]
I created this pyspark wrapper for mleap's StringMap transformer:

https://github.com/juhoautio/NotebookTest/blob/89ca52048297f09cfdff8008f20465d9d01ddad5/mleap_stringmap_python_wrapper.ipynb

Sorry that the code is not cleaned up, but maybe you'll find what you need there.
