### ISSUE TITLE
StringMap to handle missing keys instead of throwing an exception

### ISSUE THREAD

**Issue by juhoautio** [combust/mleap#555]
`StringIndexerModel` has the property `handleInvalid` with possible values:
- error
- skip
- keep

https://github.com/combust/mleap/blob/feff7105f88abe7ec9954bd834919491b26c170e/mleap-core/src/main/scala/ml/combust/mleap/core/feature/StringIndexerModel.scala#L38-L40

`StringMap` doesn't currently have such property. It always throws an exception if the key is missing in `StringMapModel.labels`, so it's currently "always handleInvalid=error".

Would you be ok with adding the same property to `StringMap`? If you like, I can make a pull request.

In `StringMap`'s case I think there should be an additional parameter to specify the default value.

**Comment by ancasarb** [comment]
Hi @juhoautio, sounds like a good plan! Just want to make sure that we keep the default as "error" as to have backwards compatibility and also that the default value is optional during serialization/deserialization.

**Comment by juhoautio** [comment]
Great! Can I unit test the backward compatibility with plain code or should I create a zip file with the current version and store it in git?

**Comment by ancasarb** [comment]
Code should be fine, you can add to StringMapSpec or to StringMapParitySpec (you can create two string map transformer, one with a handle invalid and the default and keep also the existing, without either).

**Comment by juhoautio** [comment]
@ancasarb @hollinwilkins I don't really know what https://github.com/combust/bundle-protobuf is about, but I don't see anything about handleInvalid/handle_invalid in it, even though it has a StringIndexerOp. Should it be added?

I also noticed that StringMapOp doesn't exist at all in bundle-protobuf. Otherwise I would have expected need to modify it as well, as I'm adding new parameters to StringMap.

**Comment by ancasarb** [comment]
@juhoautio we don't hardcode the attributes for each of the transformers, they're all part of the Attributes map, you can take a look
https://github.com/combust/bundle-protobuf/blob/master/bundle/bundle.proto#L135
and
https://github.com/combust/bundle-protobuf/blob/master/bundle/bundle.proto#L112

**Comment by ancasarb** [comment]
PR has been merged, closing issue.
