### ISSUE TITLE
mleap-xgboost-runtime do not support Scala 2.12

### ISSUE THREAD

**Issue by CatTail** [combust/mleap#576]
I'm using Scala 2.12, from maven I can see that mleap-runtime publish 0.14.0 version which support Scala 2.12 but mleap-xgboost-runtime do not publish 0.14.0. Can someone help to publish 0.14.0 version of mleap-xgboost-runtime to support Scala 2.12? Thanks.

**Comment by CatTail** [comment]
Hi @ancasarb, can you help to publish a new version of mleap-xgboost-runtime that support Scala 2.12?

**Comment by ancasarb** [comment]
Actually, it's the underlying xgboost dependencies that only support 2.11, so that's why we haven't published the two mleap xgboost libraries for 2.12.

**Comment by ancasarb** [comment]
Closing this for now, will do the upgrade once the underlying dependency supports scala 2.12.
