### ISSUE TITLE
Using Mleap Spring Boot to score using Custom Transformer

### ISSUE THREAD

**Issue by femibyte** [combust/mleap#583]
Hi, I'm getting the following error when I try to score data using mleap-spring-boot for a custom transformer that I've written :
```
ml.combust.mleap.executor.error.ExecutorException: key not found: labels
	at ml.combust.mleap.executor.service.LocalTransformService.ml$combust$mleap$executor$service$LocalTransformService$$wrapExceptions(L]
	at ml.combust.mleap.executor.service.LocalTransformService$$anonfun$ml$combust$mleap$executor$service$LocalTransformService$$wrapExc]
	at ml.combust.mleap.executor.service.LocalTransformService$$anonfun$ml$combust$mleap$executor$service$LocalTransformService$$wrapExc]
	at scala.concurrent.Future$$anonfun$transform$1$$anonfun$apply$2.apply(Future.scala:224) ~[org.scala-lang.scala-library-2.11.8.jar:n]
	at scala.concurrent.Future$$anonfun$transform$1$$anonfun$apply$2.apply(Future.scala:224) ~[org.scala-lang.scala-library-2.11.8.jar:n]
	at scala.util.Try$.apply(Try.scala:192) ~[org.scala-lang.scala-library-2.11.8.jar:na]
	at scala.concurrent.Future$$anonfun$transform$1.apply(Future.scala:224) ~[org.scala-lang.scala-library-2.11.8.jar:na]
	at scala.concurrent.Future$$anonfun$transform$1.apply(Future.scala:222) ~[org.scala-lang.scala-library-2.11.8.jar:na]
```

As far as I can see, this is possibly to be a jar incompatibility issue. Can someone provide any pointers?

The call looks like this to the running docker container:

```curl --header "Content-Type: application/json"   --request POST   --data "$REQ_DATA" http://localhost:8080/models/myModel/transform```

@ancasarb

**Comment by femibyte** [comment]
Is there any way to obtain the Dockerfile used to create the Spring boot image so I can try building it with a more recent version of Scala 11 ? It's building it with `org.scala-lang.scala-library-2.11.8.jar` in the /opt/docker/lib directory.

**Comment by femibyte** [comment]
Has anyone gotten this to work other than the provided Airbnb example ? The error seems to indicate some inconsistencies in the jar files. If the Dockerfile can be provided, I can work my way through the issues I'm having.
@hollinwilkins @ancasarb

**Comment by ancasarb** [comment]
@femibyte we use the DockerPlugin to generate the docker files, if you want a different version of scala, you can update it here https://github.com/combust/mleap/blob/master/project/Common.scala and re-build the image.

**Comment by femibyte** [comment]
I solved this issue. The error had to do with the op specified in my model.
This was because my Op file MyModelOp.scala had this setting:

`override def opName: String = Bundle.BuiltinOps.feature.string_map`

I was specifying `stringmap` from the example which was mapped to `StringMapModel.scala` which ended up looking for the `labels` key. 
The fix was to change the file and retrain the model.
