### ISSUE TITLE
How to save PiplineModel to hdfs?

### ISSUE THREAD

**Issue by Alucardmini** [combust/mleap#584]
Here is my code :
` val formula = new RFormula()
      .setFormula("labelFlag ~ partTime + workTime + downLoadCnt + age_Index + sex_Index + sexOrient_Index + cityLevel_Index + house_Index + car_Index " +
        "+ occupation_Index + education_Index + life_Index + incomeLevel_Index + industry_Index + consumeLevel_Index")
      .setFeaturesCol("features")
      .setLabelCol("label")

    stages.append(formula)

    val layers = Array[Int](15, 128, 128, 2)
    val trainer = new MultilayerPerceptronClassifier()
      .setLayers(layers)
      .setBlockSize(128)
      .setSeed(1234L)
      .setMaxIter(1000)

    stages.append(trainer)

    val pipeline = new Pipeline().setStages(stages.toArray)
    val pipelineModel = pipeline.fit(train)

    implicit val sbc: SparkBundleContext = SparkBundleContext.
      defaultContext.withDataset(pipelineModel.transform(train),
      registerHdfs = true)
    pipelineModel.writeBundle.save(new URI(modelPath))`

modelPath is a hdfs address

After submit to spark, the modelPath is empty, and I did not get any warning or error message. How could I save PiplineModel to Hdfs?
Thanks a million.
@aufrank @bneijt @mslipper @mutyonok

**Comment by CarreauClement** [comment]
Did you get an exception ? Maybe it was silent, try this :

- pipelineModel.writeBundle.save(new URI(modelPath)).get

It will return the result of the Try, thus will throw an exception in case something failed.

**Comment by ancasarb** [comment]
I've tried this small complete example that worked without issues. 

```
import org.apache.spark.ml.{Pipeline, Transformer, PipelineModel}
import org.apache.spark.sql.{Row, DataFrame}
import org.apache.spark.sql.types.{StringType, DoubleType, StructType}

val names = Seq("Hello, MLeap!", "Another row", "test")
val numbers = Seq(56.7d, 23.4d)
val rows = spark.sparkContext.parallelize(Seq.tabulate(3) { i => Row(names(i)) })
val schema = new StructType().add("name", StringType, nullable = false)

val dataset: DataFrame = spark.sqlContext.createDataFrame(rows, schema)

import ml.combust.bundle.BundleFile
import ml.combust.bundle.serializer.SerializationFormat
import org.apache.spark.ml.feature.StringIndexer
import org.apache.spark.ml.mleap.SparkUtil
import ml.combust.mleap.spark.SparkSupport._
import resource._
import org.apache.spark.ml.bundle.SparkBundleContext

val stringIndexer = new StringIndexer().
  setInputCol("name").
  setOutputCol("index")

val pipelineEstimator = new Pipeline().setStages(Array(stringIndexer)).fit(dataset)

import java.net.URI
implicit val sbc = SparkBundleContext().withDataset(pipelineEstimator.transform(dataset))
pipelineEstimator.writeBundle.save(new URI("hdfs:///tmp/simple-spark-pipeline-hdfs-test.zip"))

val loadedPipeline = new URI("hdfs:///tmp/simple-spark-pipeline-hdfs-test.zip").loadMleapBundle().get.root

loadedPipeline.asInstanceOf[PipelineModel].stages

```

Closing this for now, in preparation of release 0.16.0, please reopen if you are still seeing an issue with this. Thank you!
