### ISSUE TITLE
spring boot serving compile failed

### ISSUE THREAD

**Issue by qspeng** [combust/mleap#586]
Hello, I've done the spring boot serving code and try to start it local. But I found the compile error like these:
`Model.toJavaProto(model)`
```
Model.ScalaPB(model)
BundleMeta.toJavaProto(meta)
TransformFrameResponse.toJavaProto(response)
ErrorTransformResponse.toJavaProto(handleTransformFailure(ex)
```

I get this is generated by ScalaPB, but there is no proto files to generated, can you guys offering these completed files?

**Comment by ancasarb** [comment]
hey @qspeng, the proto files are under https://github.com/combust/bundle-protobuf, see the info here https://github.com/combust/mleap-docs/blob/master/getting-started/building.md about building from source, you need to do the submodule init commands. hope this helps!

**Comment by ancasarb** [comment]
Closing this, please re-open if you are still seeing issues. The proto files are linked to above.
