### ISSUE TITLE
MathBinary has some bug

### ISSUE THREAD

**Issue by psc0606** [combust/mleap#602]
I use mleap to save to bundle zip file, but when I get input schema,  I miss the `MathBinary ` tranformer's input StructFeild, anyone can help?

**Comment by ancasarb** [comment]
Could you please post an example of how you're using MathBinary transformer? We have https://github.com/combust/mleap/blob/372cfa59991527c1a43efa75d8915cca7c3f1b23/mleap-spark-extension/src/test/scala/org/apache/spark/ml/mleap/parity/feature/MathBinaryParitySpec.scala that shows a working example, for reference.

**Comment by ancasarb** [comment]
Closing this, please feel free to re-open if you still have an issue. Thank you!
