### ISSUE TITLE
The requested resource could not be found. when use the same model by "uri" and "path"

### ISSUE THREAD

**Issue by topxxuki** [combust/mleap#608]
i start a image like this:
`docker run -p 65327:65327  -v /tmp:/models combustml/mleap-serving:0.9.0-SNAPSHOT
`
files under /tmp are:
![image](https://user-images.githubusercontent.com/18697846/69689263-6bd64500-1103-11ea-9eba-71a42fc7fae5.png)

here is my question:
i can put a model like this:
```
curl -XPUT -H "content-type: application/json" \
-d '{"path":"/models/lr-pipeline.zip"}' http://localhost:65327/model
```
it returns :
{}%

but when i try to put a model like:
```
curl --header "Content-Type: application/json" \
  --request POST \
  --data '{"modelName":"lr","path":"/models/lr-pipeline.zip","config":{"memoryTimeout":900000,"diskTimeout":900000},"force":false}' http://localhost:65327/models
```
it returns :
The requested resource could not be found.%

if i put a model like {"path":"/models/lr-pipeline.zip","modelName":"lr"},still cannot get a model from  http://localhost:65327/models/lr

**Comment by ancasarb** [comment]
We did an overhaul with the serving layer in version 0.13.0 and the endpoints you are trying to use are from that version, if you try the same with version 0.13.0 then you should see them working. Another thing is that you need to make sure that curl uses HTTP2, or else you will get an error that resembles "Unexpected HTTP/1.x request: POST /models" for example.

**Comment by ancasarb** [comment]
I've also created https://github.com/combust/mleap/pull/629 to fix the default ports, as the http port had changed from 65327 to 8080, but should be back to 65327 in 0.16.0-SNAPSHOT.

**Comment by ancasarb** [comment]
Closing this as PR was merged, please let me reopen if you find any issues. Thank you!
