### ISSUE TITLE
LDA Transformer

### ISSUE THREAD

**Issue by hollinwilkins** [combust/mleap#61]
Support LDA clustering algorithm

**Comment by hollinwilkins** [comment]
@mageswaran1989 Thank you for putting in a PR for this, linking here: https://github.com/combust/mleap/pull/144

**Comment by Mageswaran1989** [comment]
Could you help with loading the entire project in IntelliJ and writing unit test cases?

**Comment by hollinwilkins** [comment]
@Mageswaran1989 To load into intellij go to File -> New -> Project from Existing Sources and navigate to the root level MLeap repo. This should work fine, but if it isn't please let me know. A problem you may encounter is that IntelliJ does not automatically pickup generated source code for the protobuf files. You have to manually configure the Module Settings for bundle-ml to include generated source directory.

**Comment by Mageswaran1989** [comment]
I tried that but for some reason IDE is not loading all the depencies and indexing is breaking.
Most of the time SBT loading only  fails.
