### ISSUE TITLE
Error deserializing mleap bundle

### ISSUE THREAD

**Issue by femibyte** [combust/mleap#613]
I'm trying to de-serialize the airbnb sample model file and getting an error:

```
scala> val bundlePath5="jar:file:/tmp/models/airbnb.model.lr.zip"
bundlePath5: String = jar:file:/tmp/models/airbnb.model.lr.zip

scala> val zipBundle5 = (for(bundle <- managed(BundleFile(bundlePath5))) yield {
     |   bundle.loadMleapBundle().get
     |     }).opt.get
java.util.NoSuchElementException: None.get
  at scala.None$.get(Option.scala:529)
  at scala.None$.get(Option.scala:527)
  ... 38 elided```

Any pointers ?

**Comment by ancasarb** [comment]
@femibyte could you please do ```val bundle = (for(bundle <- managed(BundleFile(bundlePath5))) yield {
      bundle.loadMleapBundle().get
    }).tried.get``` to expose an error? 

Could you provide a bit more details, for example, which version of mleap are you using?

**Comment by ancasarb** [comment]
@femibyte I believe this may no longer be an issue, please re-open if you are still facing problems. Thanks!
