### ISSUE TITLE
mleap only supports java 8, why?

### ISSUE THREAD

**Issue by mtsol** [combust/mleap#619]
Hi, Java 13 is released and mleap still supports Java 8, not even Java 9. When you guys are going to upgrade this thing or will you always be stuck at Java 8? Or If I want to use mleap for Java 9 or 10 then what can I do to upgrade it. In short, when will mleap upgrade itself?

**Comment by ancasarb** [comment]
Hi @mtsol, it's because Spark 2.4.x supports Java 8 and mleap jars need to be loaded on Spark so that the serialization can be done. Nonetheless, I think you can use the mleap jars that use Java 8 from higher Java versions (9,10,11), have you given it a try?

**Comment by mtsol** [comment]
Hello, @ancasarb I have tried with java 9 and it didn't work.

**Comment by ancasarb** [comment]
I see, then we probably will need to wait until after Spark 3, so that we can upgrade to java 11. there's already this ticket https://github.com/combust/mleap/issues/475 to track that work, is it ok to close this one?

**Comment by mtsol** [comment]
yeah, it's perfectly fine to close this one.
