### ISSUE TITLE
Support for mleap issues - can we pay for it ?

### ISSUE THREAD

**Issue by femibyte** [combust/mleap#621]
Anyone else frustrated like me at the lack of mleap support ? I'm desperate enough that I'm willing to pay the creators to help get my issues resolved.

**Comment by ancasarb** [comment]
Apologies for the delay in answering some of the issues, could I please ask which ones you'd need help with? Apologies again!

**Comment by mtsol** [comment]
Hi @femibyte what kind of issues you are facing? We've serialized and deserialized spark models with mleap, and we have written custom transformers. What kind of issues you are having?

**Comment by femibyte** [comment]
> Hi @femibyte what kind of issues you are facing? We've serialized and deserialized spark models with mleap, and we have written custom transformers. What kind of issues you are having?
This is an issue that has been dogging me...

https://github.com/combust/mleap/issues/632

**Comment by ancasarb** [comment]
Closing this, Femi and I worked through the issues in #632, thank you!
