### ISSUE TITLE
mleap model predict probability  is not same between spark predict and local load model with same data

### ISSUE THREAD

**Issue by marvinxu-free** [combust/mleap#622]
i write two test cases, first is a spark test case which generate a mleap zip model to local; second test case is a java test case, which load the zip model and predict on sampe data from test1's dataframe, but the probability is not same, here is my code:

test1:

`package com.zenmen.wkread.pmmlModel.ctrModel

import com.zenmen.wkread.SparkFunSuite
import org.apache.spark.ml.classification.{LogisticRegression, LogisticRegressionModel}
import org.apache.spark.ml.feature._
import org.apache.spark.ml.linalg.Vector
import org.apache.spark.ml.{Pipeline, PipelineStage}
import org.apache.spark.sql.functions
import org.scalatest.FunSuite

import scala.collection.mutable.ArrayBuffer
import scala.util.Try

class ChapterLrManModelTest extends FunSuite with SparkFunSuite {

  private val getKeys: Map[String, Double] => Seq[String] = { input: Map[String, Double] => input.keySet.toSeq }

  private val getProb1 = functions.udf((v: Vector) => v.toArray(1))

  val keyUdf = functions.udf(getKeys)

  test("testTrainModel") {
    val data0 = spark.createDataFrame(Seq(
      (Array("1"), 1.0, Map("a" -> 0.1, "b" -> 0.2, "c" -> 0.3), 1),
      (Array("2"), 10.0, Map("d" -> 0.1, "e" -> 0.2, "c" -> 0.3), 0),
      (Array("3"), 20.0, Map("x" -> 0.1, "a" -> 0.2, "b" -> 0.3), 0),
      (Array("4"), 15.0, Map("c" -> 0.1, "b" -> 0.2, "w" -> 0.3), 0),
      (Array("5"), 18.0, Map("c" -> 0.1, "b" -> 0.2, "w" -> 0.3), 0),
      (Array("6"), 25.0, Map("c" -> 0.1, "b" -> 0.2, "w" -> 0.3), 1),
      (Array("6"), 5.0, Map("a" -> 0.1, "b" -> 0.2, "d" -> 0.3), 0),
      (Array("7"), 30.0, Map("c" -> 0.1, "b" -> 0.2, "w" -> 0.3), 0))
    )
      .toDF("book_id", "pv", "myInputCol0", "label")

    val data = data0.withColumn("myInputCol", keyUdf(functions.col("myInputCol0")))
      .drop("myInputCol0")

    data.show(10)
    data.printSchema()

    val pipelineStage = new ArrayBuffer[PipelineStage]()

    val bookFiter = new CountVectorizer()
      .setInputCol("book_id")
      .setOutputCol("book_id_vec")
      .setMinDF(1)
      .setMinTF(1)
      .setBinary(true)
    pipelineStage += bookFiter

    val doubleDiscretizer = new QuantileDiscretizer()
      .setInputCol("pv")
      .setOutputCol("pv_bucket")
      .setNumBuckets(3)
    pipelineStage += doubleDiscretizer

    val myFiter = new CountVectorizer()
      .setInputCol("myInputCol")
      .setOutputCol("myInputCol1_vec")
      .setMinDF(1)
      .setMinTF(1)
      .setBinary(true)
    pipelineStage += myFiter

    val vectorAsCols = Array("pv_bucket", "book_id_vec", "myInputCol1_vec")

    val vectorAssembler = new VectorAssembler().setInputCols(vectorAsCols).setOutputCol("vectorFeature")
    pipelineStage += vectorAssembler

    val scaler = new MinMaxScaler().setInputCol("vectorFeature").setOutputCol("scaledFeatures")
    pipelineStage += scaler

    val lr: LogisticRegression = new LogisticRegression()
      .setFitIntercept(true)
      .setMaxIter(1) //max iteration
      .setFeaturesCol("scaledFeatures")
      .setLabelCol("label")

    pipelineStage += lr

    //    val featurePipeline = new Pipeline().setStages(Array(myFiter, labelQuant, vectorAssembler, scaler))
    val featurePipeline = new Pipeline().setStages(pipelineStage.toArray)

    val fitor = featurePipeline.fit(data)
    val data1 = fitor.transform(data)

    val lrm = fitor.stages.last.asInstanceOf[LogisticRegressionModel]

    val vecModels = fitor
      .stages
      .map(x => Try(x.asInstanceOf[CountVectorizerModel]))
      .filter(x => x.isSuccess)

    //    val quantModels = fitor
    //      .stages
    //      .map(x => Try(x.asInstanceOf[Bucketizer]))
    //      .filter(x => x.isSuccess)

    val featureIndex = data1.schema.fieldIndex("vectorFeature")
    val vecMap = data1.schema.fields(featureIndex).metadata.getMetadata("ml_attr").getMetadata("attrs")
    val featureMapping = Array(
      Try(vecMap.getMetadataArray("numeric")),
      Try(vecMap.getMetadataArray("binary")),
      Try(vecMap.getMetadataArray("nominal"))
    )
      .filter(x => x.isSuccess)
      .flatMap(x => x.get)
      .map(x => (x.getLong("idx"), x.getString("name")))
    val featureCof = featureMapping
      .map(x => (x._2, x._1))
      .map(x => (x._1, lrm.coefficients(x._2.toInt)))
      .toList
      .sortBy(x => x._2)
      .reverse
      .map(x => {
        if (x._1.contains("_vec")) {
          val featureOrgIndex = x._1.lastIndexOf("_").toInt
          val vecModelOutCol = x._1.substring(0, featureOrgIndex)
          val vecIndex = x._1.substring(featureOrgIndex + 1).toInt
          val vecModels = fitor
            .stages
            .map(x => Try(x.asInstanceOf[CountVectorizerModel]))
            .filter(x => x.isSuccess && x.get.getOutputCol == vecModelOutCol)
            .map(x => x.get)
          val feature = vecModels.head.vocabulary(vecIndex)
          (s"${vecModelOutCol}_${feature}", x._2)
        } else {
          (x._1, x._2)
        }
      })
      .map(x => s"${x._1}\t${x._2}")
      .mkString("\n")
    val dataFinal = data1.select(
      Seq(functions.concat_ws(",", functions.col("book_id")),
        functions.col("pv"),
        functions.concat_ws(",", functions.col("myInputCol")),
        getProb1(functions.col("probability")).alias("prob1")): _*)
    dataFinal.show()
    println(dataFinal.schema)
    dataFinal
      .write
      .mode("overwrite")
      .csv(s"${dataOutPath}/lr_base/csv")

    val mleapModel = new com.zenmen.wkread.pmmlModel.serving.mleap.serialization.ModelSerializer()
    mleapModel.serializeModel(fitor, s"jar:file:${dataOutPath}/lr_base/model/lr.model.mleap.zip", data1)
  }

}

---------------------------------------------------------split line----------------------------------
`
test2:
`package com.zenmen.wkread.pmmlModel.serving.mleap.load;

import com.google.common.collect.Lists;
import ml.combust.mleap.core.types.StructField;
import ml.combust.mleap.core.types.StructType;
import ml.combust.mleap.runtime.frame.Row;
import ml.combust.mleap.runtime.javadsl.LeapFrameBuilder;
import org.junit.Test;

import java.io.File;
import java.util.ArrayList;
import java.util.List;

/**
 * @program: wk-rec
 * @description: 测试mleap java serving
 * @author: Xu.Chao
 * @create: 2020-01-07 17:04
 **/

public class JavaModelServerTest1 {

    String testResourcePath = String.format("%s/src/test/resource", new File(".").getAbsolutePath());
    String testDataInPath = String.format("%s/src/test/dataIn", new File(".").getAbsolutePath());
    String testDataOutPath = String.format("%s/src/test/dataOut", new File(".").getAbsolutePath());

    @Test
    public void testLoadModel() {
        LeapFrameBuilder builder = new LeapFrameBuilder();
        List<StructField> fields = new ArrayList();
        fields.add(builder.createField("book_id", builder.createList(builder.createBasicString())));
        fields.add(builder.createField("pv", builder.createDouble()));
        fields.add(builder.createField("myInputCol", builder.createList(builder.createBasicString(), true)));

        StructType schema = builder.createSchema(fields);
        JavaModelServer javaModelServer = new JavaModelServer(String.format("%s/lr_base/model/lr.model.mleap.zip", testDataOutPath), schema);
        javaModelServer.loadModel();

        List<List<String>> books = Lists.newArrayList();
        books.add(Lists.newArrayList("1"));
        books.add(Lists.newArrayList("2"));
        books.add(Lists.newArrayList("3"));
        books.add(Lists.newArrayList("4"));
        books.add(Lists.newArrayList("5"));
        books.add(Lists.newArrayList("6"));
        books.add(Lists.newArrayList("6"));
        books.add(Lists.newArrayList("7"));

        List<Double> pv = Lists.newArrayList();
        pv.add(1.0);
        pv.add(10.0);
        pv.add(20.0);
        pv.add(15.0);
        pv.add(18.0);
        pv.add(25.0);
        pv.add(5.0);
        pv.add(30.0);

        List<List<String>> myInputCol = Lists.newArrayList();
        myInputCol.add(Lists.newArrayList("a", "b", "c"));
        myInputCol.add(Lists.newArrayList("d", "e", "c"));
        myInputCol.add(Lists.newArrayList("x", "a", "b"));
        myInputCol.add(Lists.newArrayList("c", "b", "w"));
        myInputCol.add(Lists.newArrayList("c", "b", "w"));
        myInputCol.add(Lists.newArrayList("c", "b", "w"));
        myInputCol.add(Lists.newArrayList("a", "b", "d"));
        myInputCol.add(Lists.newArrayList("c", "b", "w"));

        List<Row> rows = Lists.newArrayList();
        // 第一个值是对的，其余都是错的, 序不对了
        for(int i =0; i< pv.size(); i++){
            List<Object> rowValues = Lists.newArrayList();
            rowValues.add(books.get(i));
            rowValues.add(pv.get(i));
            rowValues.add(myInputCol.get(i));
            Row features = builder.createRowFromIterable(rowValues);
            ArrayList<Object> result = javaModelServer.forecast(features);
            System.out.println(String.format("预测概率为: %f", (double) (result.get(1))));
        }
    }
}`

test1's predict is:

`+---------------------+----+------------------------+-------------------+
|concat_ws(,, book_id)|  pv|concat_ws(,, myInputCol)|              prob1|
+---------------------+----+------------------------+-------------------+
|                    1| 1.0|                   a,b,c| 0.8919558331701626|
|                    2|10.0|                   d,e,c|0.08783704512194512|
|                    3|20.0|                   x,a,b|0.16700716790954087|
|                    4|15.0|                   c,b,w| 0.3690755404084818|
|                    5|18.0|                   c,b,w| 0.3690755404084818|
|                    6|25.0|                   c,b,w| 0.6447347800200935|
|                    6| 5.0|                   a,b,d|  0.434624976135266|
|                    7|30.0|                   c,b,w|0.34559828223992617|
+---------------------+----+------------------------+-------------------+`

test2's predict probability is :
`预测概率为: 0.891956
预测概率为: 0.096383
预测概率为: 0.197425
预测概率为: 0.393189
预测概率为: 0.393189
预测概率为: 0.690080
预测概率为: 0.355408
预测概率为: 0.393189`

the first row probability is same, others are different, and order changed.

**Comment by mtsol** [comment]
I also have the same issue, about 20% of my input data had different predicted values from mleap as compared to spark

**Comment by ancasarb** [comment]
@mtsol @marvinxu-free trying to reproduce this, I'll keep you posted.

**Comment by ancasarb** [comment]
@mtsol is your pipeline using a minmax scaler? it seems there's an issue with that, I will raise a PR for the fix tomorrow.
