### ISSUE TITLE
MinMaxScalerNodel bug not fixed for 0.11 version?

### ISSUE THREAD

**Issue by marvinxu-free** [combust/mleap#623]
it seems that this bug not fixed for 0.11 version with this case: #489

**Comment by ancasarb** [comment]
I believe you need to use mleap 0.14 or 0.15 to get the fix, could you please give it a try? we've not introduced any backwards compatibility issues in the latest mleap versions so you should be able to use the newer versions without issues. Let me know if you need further help.

**Comment by marvinxu-free** [comment]
> I believe you need to use mleap 0.14 or 0.15 to get the fix, could you please give it a try? we've not introduced any backwards compatibility issues in the latest mleap versions so you should be able to use the newer versions without issues. Let me know if you need further help.

`
<dependency>
    <groupId>ml.combust.mleap</groupId>
    <artifactId>mleap-runtime_2.12</artifactId>
    <version>0.15.0</version>
</dependency>`

i used mleap-runtime this version, model is dumpeds from 0.11 spark, which meet our spark version.

**Comment by ancasarb** [comment]
you can try to load a model serialized with 0.11.0 and score it with 0.15.0, we didn't introduce any compatibility issues that would break this.

**Comment by marvinxu-free** [comment]
> you can try to load a model serialized with 0.11.0 and score it with 0.15.0, I don't think we introduced any compatibility issues that would break this.

i choose not to use minmax, and resolve all problem
