### ISSUE TITLE
Loading OneHotEncoder does not seem to be working (Spark 2.1 / MLeap 0.11.0)

### ISSUE THREAD

**Issue by CarreauClement** [combust/mleap#626]
Hi,

As stated in the README, I'm using MLeap 0.11.0 because I run Spark 2.1

My pipeline is as follows (code simplified) :

```
val str = new StringIndexer()
val ohe = new OneHotEncoder()
val vecAssembler = new VectorAssembler()
val rf = new RandomForestClassifier()
new Pipeline().setStages(Array(str, ohe, vecAssembler, rf))
```

The saving works fine :
```
val filePrefix = "jar:file:"
val filePath = "/tmp/model.zip"

val sbc = SparkBundleContext().withDataset(model.transform(data))
for (bf <- managed(BundleFile(s"$filePrefix$filePath"))) {
  model.writeBundle.format(SerializationFormat.Json).save(bf)(sbc).get
}
```

I checked the model I saved, here is what OneHotEncoder looks like :

```
{
  "op": "one_hot_encoder",
  "attributes": {
    "size": {
      "long": 3
    },
    "drop_last": {
      "boolean": true
    }
  }
```

The problem happens when I'm trying to load the pipeline to use it.
When I do :

```
import ml.combust.mleap.runtime.MleapSupport._
import java.net.URI

val bundleUri = new URI("jar:file:/tmp/model.zip")
val model = bundleUri.loadMleapBundle().get.root
```

I get the following error **java.util.NoSuchElementException: key not found: category_sizes**

This attribute comes from the new OneHotEncoder estimator from Spark 2.3, but I'm running Spark 2.1

When retrieving the list of ops from the reference.conf file of mleap-runtime, we get two keys for the OneHotEncoder, here they are :

  "ml.combust.mleap.bundle.ops.feature.NormalizerOp",
  **"ml.combust.mleap.bundle.ops.feature.OneHotEncoderOp",
  "ml.combust.mleap.bundle.ops.feature.OneHotEncoderOpV23",**
  "ml.combust.mleap.bundle.ops.feature.PcaOp",

And then, in BundleRegistry class line 40, we loop through the ops name, instantiate them, and put them in a Map with their name as the key.

The thing is, OneHotEncoderOp and OneHotEncoderOpV23 have the same key and thus, OneHotEncoderOpV23 overrides OneHotEncoderOp in the Map (you can clearly see that during debug).

Afterwards, when trying to load my Spark 2.1 model, MLeap sees the OneHotEncoderOpV23 has the correct transformer to load and looks for an attribute (category_sizes) that does not exist in the model I saved.

Is something wrong on my end ? Maybe I'm missing some conf or something.

Thanks for your help !

**Comment by CarreauClement** [comment]
Got it working by :

- creating my own reference.conf file by copying mleap-runtime's reference.conf file and removing the "ml.combust.mleap.bundle.ops.feature.OneHotEncoderOpV23" line
- changing my build.sbt as follows to only keep my reference.conf file :
```
assemblyMergeStrategy in assembly := {
  case PathList("META-INF", _*) => MergeStrategy.discard
  case n if n.startsWith("reference.conf") => MergeStrategy.first
  case _ => MergeStrategy.first
}
```

**Comment by ancasarb** [comment]
There were unfortunately breaking changes for version 0.11.0 and 0.12.0 of mleap for the one hot encoder / one hot encoder estimators. One thing you could do is try to either use 0.10.3 version, or any version 0.13.0 or greater. Apologies for this!

**Comment by CarreauClement** [comment]
Thanks for the reply.

Don't you think it should be on the README if something is not working properly ?

I mean, I lost hours trying to figure it out.

**Comment by ancasarb** [comment]
Sure, that is a good idea. I will make sure to add this in, apologies again.

**Comment by ancasarb** [comment]
Added a note about the breaking changes of 0.11.0 and 0.12.0 here https://github.com/combust/mleap/issues/626. apologies again for the confusion!
