### ISSUE TITLE
XGBoost Performance Issues

### ISSUE THREAD

**Issue by voganrc** [combust/mleap#631]
Hello,

I ran some JMH benchmarks that show MLeap to be significantly slower than other libraries for evaluating XGBoost models.

![image](https://user-images.githubusercontent.com/5606641/72943477-04b3c600-3d2b-11ea-9e40-a90e079defdf.png)

Here you can see throughput (ops / sec) as a function of library and batch size, where:

xgboost4j = https://github.com/dmlc/xgboost/tree/master/jvm-packages
xgboost-predictor-java = https://github.com/komiya-atsushi/xgboost-predictor-java
yelp-xgboost = https://github.com/Yelp/xgboost-predictor-java
mleap = https://github.com/combust/mleap

Given that Mleap makes use of `xgboost4j-spark` does anyone know why it would have half the throughput of `xgboost4j`? Also, is there a reason why `mleap` does not observe constant throughput scaling like `xgboost4j` does?

Thanks!
-Ryan

**Comment by lucagiovagnoli** [comment]
Hi Anca! So, we've run some tests above and noticed that **xgboost4j is much slower than xgboost-predictor-java** :( 
Historically we've use a fork of xgboost-predictor at Yelp ([yelp-xgboost](https://github.com/Yelp/xgboost-predictor-java)) so we're hitting a performance issue when running MLeap cause xgboost4j seems thousands of times slower :/

- **I was thinking to make a PR** to allow deserializing the model binary as either an *xgboost-predictor* OR *xgboost4j* (based users' preference). Fortunately it seems that xgboost-predictor supports loading from xgboost4j binaries, see the [ModelReader](https://github.com/h2oai/xgboost-predictor/blob/master/xgboost-predictor/src/main/java/biz/k11i/xgboost/util/ModelReader.java). *I just wanted to check what you think before we get to it.*

**PS**: I also noticed that @hollinwilkins was interested in xgboost-predictor in the past, he commented on the xgboost-predictor project about deploying it to Maven Central  (their comment [here](https://github.com/komiya-atsushi/xgboost-predictor-java/issues/22))

@ancasarb

**Comment by ancasarb** [comment]
Hey @lucagiovagnoli this seems fine to me, do you know if xgboost-predictor-java is available in maven already? Or is that ticket still pending?

**Comment by lucagiovagnoli** [comment]
I've just noticed they are! It's mentioned on their [README](https://github.com/komiya-atsushi/xgboost-predictor-java)

and i found them on [bintray](https://bintray.com/komiya-atsushi/maven/xgboost-predictor/view) :)

**Comment by ancasarb** [comment]
ok, cool :) It would be nice to see the difference in performance between the two :)

**Comment by lucagiovagnoli** [comment]
Hi @ancasarb, 
I just found out that mleap was actually using xgboost-predictor in 2017/2018! That sounds great. I wonder if you know why it was removed in this PR https://github.com/combust/mleap/pull/401. Any any lesson learnt or big blockers in using it? (wondering if it was just to switch back to the "official" implementation)

It seems some others like @ytjia are suffering from performance degradation. We also fixed all  known bugs in our fork https://github.com/Yelp/xgboost-predictor-java and we plan to contribute these back upstream

**Comment by ancasarb** [comment]
I'd probably say that it was due to the Maven availability and being able to run on travis etc., but it was Hollin who did the integration.

What performance degradation are you referring to from @ytjia? Is there an issue for that, or?

**Comment by lucagiovagnoli** [comment]
My bad, I misused "degradation", I meant that xgboost4j is so slow for us that it's impractical to use at scale for online inference. I found this [comment](https://github.com/combust/mleap/pull/401#issuecomment-546222818) from @ytjia on pr #401 mentioning they are having the same problem.

I really liked @hollinwilkins work integrating `xgboost-predictor` in PR #259, if there's no real blocker I have a PR (almost ready) to include both `xgboost4j` (status quo) and `xgboost-predictor` (high performance) in MLeap so developers can de-serialize xgboost models using the library they prefer :)

**Comment by ancasarb** [comment]
That sounds like a good plan @lucagiovagnoli.

**Comment by changhiskhan** [comment]
I can add some color on the performance issues mentioned by @ytjia. I believe `xgboost4j` uses a static synchronized JNI entry point to communicate with the underlying xgboost code (which is not thread-safe). This isn't a problem in single-threaded applications, but in many real-time prediction applications, it's behind a multi-threaded service handling concurrent requests. We ended up using `xgboost-predictor-java` as a workaround.

**Comment by indranilr** [comment]
Very useful analysis by @voganrc , we are looking at a [spark xgboost4j model](https://github.com/dmlc/xgboost/tree/master/jvm-packages/xgboost4j-spark) for online inference but after reading this thread it appears `xgboost-predictor-java` is better choice for such scenarios. Would be quite useful if  MLeap can be configured to use `xgboost-predictor-java` .

@lucagiovagnoli would this PR support the 0.9 release of xgboost4j_spark ? Hopefully, this enhancement will be part of next Mleap release.

**Comment by indranilr** [comment]
> 
> 
> I can add some color on the performance issues mentioned by @ytjia. I believe `xgboost4j` uses a static synchronized JNI entry point to communicate with the underlying xgboost code (which is not thread-safe). This isn't a problem in single-threaded applications, but in many real-time prediction applications, it's behind a multi-threaded service handling concurrent requests. We ended up using `xgboost-predictor-java` as a workaround.

To clarify my understanding a little, can a spark model exported from `XGBoost4j-Spark` (**Example**: `xgbClassificationModel.write.overwrite().save(xgbClassificationModelPath)` be used to predict using `xgboost-predictor-java` ? Would I need to export the `XGBoost4j-Spark` model to native binding first (**Example** : `xgbClassificationModel.nativeBooster.saveModel(nativeModelPath)` and then use `xgboost-predictor-java`  to load and serve the model ?

**Comment by lucagiovagnoli** [comment]
@indranilr @changhiskhan feel free to review https://github.com/combust/mleap/pull/645 which should solve this. There's some instructions on how to use the Predictor in the PR
