### ISSUE TITLE
Python tests are not run on all versions py27, py36, py37

### ISSUE THREAD

**Issue by lucagiovagnoli** [combust/mleap#642]
It seems that our python tests are not running using all tox virtualenvs for py27, py36 and py37. 
I think somehow the $TRAVIS_PYTHON_VERSION is unset, so we end up creating `.tox/py`. It's unclear to me which python version we are running tests with.

This is taken from  the output of a master  branch build (https://travis-ci.org/combust/mleap/builds/643702883):
```
$ tox -c python/tox.ini -e $(echo py$TRAVIS_PYTHON_VERSION | tr -d .) -v
using tox.ini: /home/travis/build/combust/[secure]/python/tox.ini (pid 20189)
using tox-3.14.3 from /home/travis/.local/lib/python2.7/site-packages/tox/__init__.pyc (pid 20189)
GLOB sdist-make: /home/travis/build/combust/[secure]/python/setup.py
[20199] /home/travis/build/combust/[secure]/python$ /usr/bin/python setup.py sdist --formats=zip --dist-dir /home/travis/build/combust/[secure]/python/.tox/dist >.tox/log/GLOB-0.log
package .tmp/package/1/[secure]-0.16.0-SNAPSHOT.zip links to dist/[secure]-0.16.0-SNAPSHOT.zip (/home/travis/build/combust/[secure]/python/.tox)
py cannot reuse: no previous config /home/travis/build/combust/[secure]/python/.tox/py/.tox-config1
py create: /home/travis/build/combust/[secure]/python/.tox/py
```

**Comment by lucagiovagnoli** [comment]
It seems that python tests are not being run on 3.7 because they would incur in this error on Travis:
https://travis-ci.community/t/unable-to-download-python-3-7-archive-on-travis-ci/639/2

**Comment by ancasarb** [comment]
Closing this as the PR has been merged, please let me know if that's not right.
