### ISSUE TITLE
Do you serialize handleInvalid param of VectorIndexer into mleap model? 

### ISSUE THREAD

**Issue by mtsol** [combust/mleap#648]
I don't see that this is being serialized, and an exception occurs on mleap side when unseen data happens in leapframe.

**Comment by mtsol** [comment]
I changed the model class and it is working fine, do you want to add support for other classes as well?
`package ml.combust.mleap.core.feature

import ml.combust.mleap.core.Model
import ml.combust.mleap.core.annotation.SparkCode
import ml.combust.mleap.core.types.{StructType, TensorType}
import org.apache.spark.ml.linalg.{DenseVector, SparseVector, Vector}

/**
  * Created by mtsol on 02/20/2020.
  */
@SparkCode(uri = "https://github.com/apache/spark/blob/v2.4.0/mllib/src/main/scala/org/apache/spark/ml/feature/VectorIndexer.scala")
case class VectorIndexerModel(numFeatures: Int,
                              categoryMaps: Map[Int, Map[Double, Int]]) extends Model {
  
	val sortedCatFeatureIndices = categoryMaps.keys.toArray.sorted
    val localVectorMap = categoryMaps
    val localNumFeatures = numFeatures
    val localHandleInvalid = "keep"
  def apply(features: Vector): Vector = predict(features)
  def predict(v: Vector): Vector = {
    assert(v.size == localNumFeatures, "VectorIndexerModel expected vector of length" +
        s" $numFeatures but found length ${v.size}")
      v match {
        case dv: DenseVector =>
          var hasInvalid = false
          val tmpv = dv.copy
          localVectorMap.foreach { case (featureIndex: Int, categoryMap: Map[Double, Int]) =>
            try {
              tmpv.values(featureIndex) = categoryMap(tmpv(featureIndex))
            } catch {
              case _: NoSuchElementException =>
                localHandleInvalid match {
                  case "keep" =>
                    tmpv.values(featureIndex) = categoryMap.size
                  case "skip" =>
                    hasInvalid = true
                }
            }
          }
          if (hasInvalid) null else tmpv
        case sv: SparseVector =>
          // We use the fact that categorical value 0 is always mapped to index 0.
          var hasInvalid = false
          val tmpv = sv.copy
          var catFeatureIdx = 0 // index into sortedCatFeatureIndices
          var k = 0 // index into non-zero elements of sparse vector
          while (catFeatureIdx < sortedCatFeatureIndices.length && k < tmpv.indices.length) {
            val featureIndex = sortedCatFeatureIndices(catFeatureIdx)
            if (featureIndex < tmpv.indices(k)) {
              catFeatureIdx += 1
            } else if (featureIndex > tmpv.indices(k)) {
              k += 1
            } else {
              try {
                tmpv.values(k) = localVectorMap(featureIndex)(tmpv.values(k))
              } catch {
                case _: NoSuchElementException =>
                  localHandleInvalid match {
                    case "keep" =>
                      tmpv.values(k) = localVectorMap(featureIndex).size
                    case "skip" =>
                      hasInvalid = true
                  }
              }
              catFeatureIdx += 1
              k += 1
            }
          }
          if (hasInvalid) null else tmpv
      }
  }

  override def inputSchema: StructType = StructType("input" -> TensorType.Double(localNumFeatures)).get

  override def outputSchema: StructType = StructType("output" -> TensorType.Double(localNumFeatures)).get

}
`

**Comment by ancasarb** [comment]
@mtsol Thank you for your finding, you are right, at the moment, it's not being serialized, so it's using the default, which is to error on unseen data. Could you please raise a PR with the changes? Happy to take a look!

**Comment by mtsol** [comment]
of course, why not?

**Comment by mtsol** [comment]
How to raise a PR?

**Comment by lucagiovagnoli** [comment]
Hi @mtsol,
thanks for contributing!
Github has some resources on the logistics of it: https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request

After fixing, make sure your change is covered by tests (write a new one if necessary) and make sure the tests pass (github will run them automatically but you can also do so locally).

**Comment by ancasarb** [comment]
Closing this, PR with the fix merged into latest mleap master branch.
