### ISSUE TITLE
Can we add a custom MLeap transformer JAR in classpath

### ISSUE THREAD

**Issue by ZhenyiLin** [combust/mleap#649]
I developed a custom mleap transformer (3 files, xxxModel, xxx, xxxOp) and compiled it into a JAR file. I did so because I'd like to avoid make any change to the original MLeap JARs, and I only need to manage the new custom codes. 

I prepared model files so that I don't need to worry about the Spark part.

However, I met the first issue about "java.util.NoSuchElementException: key not found". I realized it is because the reference.conf is not loaded properly from my custom JAR file. therefore I used option "-Dconfig.file=/path_to_file/reference.conf to force load it.

However, the issue then became "Factory method 'provideMleapContext' threw exception; nested exception is java.lang.ClassNotFoundException", it seems Java cannot find the Class in the custom JAR file, and I couldn't figure out why Java can't find it in the classpath.

On the other hand, if I compile my custom transformer with mleap into a single JAR file, I could run it without any problem.

**Comment by lucagiovagnoli** [comment]
Hi @ZhenyiLin, thanks for bringing this up. We recently also implemented a custom transformer (internally). I think we encountered similar issues, but could you please provide some skeleton code to look at?

We've been thinking to contribute our Transformer back upstream for ease of maintenance and re-usability by the community. Regardless, I think it'd be great for MLeap to support custom transformers somehow.

**Comment by ancasarb** [comment]
@ZhenyiLin This is definitely doable, could you please share the skeleton of your project to try to investigate what the issue could be? It can be a dummy transformer, don't need a specific one.

**Comment by ancasarb** [comment]
Closing for now, please re-open if there's still an outstanding question.
