### ISSUE TITLE
mleap runtime depends on mleap core which depends on spark

### ISSUE THREAD

**Issue by ganeshkrishnan1** [combust/mleap#650]
Mleap runtime is supposed to be lightweight dependency but it seems to be dragging in core and apache spark + mlib in full. This is causing issues when we have spark runtime which is different from what mleap seems to be pulling (2.4.0)

Is there a real light weight version of mleap runtime without spark dependencies just for predictions?

**Comment by ancasarb** [comment]
@ganeshkrishnan1 mleap-runtime is the dependency you need for scoring/predictions, it doesn't have a dependency on spark. 

The only spark-related dependency in the mleap runtime project is on spark-mllib-local, but that's a small library, which doesn't bring in the spark itself. 

What issues are you seeing/facing?

**Comment by ganeshkrishnan1** [comment]
mleap-runtime is pulling in mleap-core which pulls mleap spark. At runtime I can see spark 2.4.0 being loaded up via mleap in my application.

**Comment by ancasarb** [comment]
@ganeshkrishnan1 here's an example of what mleap-runtime brings in with the Maven command 

```
 mvn dependency:tree 
```

 Using similar commands in Gradle or SBT results in the same. 
```
[INFO] +- ml.combust.mleap:mleap-runtime_2.11:jar:0.16.0-SNAPSHOT:compile
[INFO] |  +- org.scala-lang:scala-library:jar:2.11.12:compile
[INFO] |  +- ml.combust.mleap:mleap-core_2.11:jar:0.16.0-SNAPSHOT:compile
[INFO] |  |  +- ml.combust.mleap:mleap-base_2.11:jar:0.16.0-SNAPSHOT:compile
[INFO] |  |  +- ml.combust.mleap:mleap-tensor_2.11:jar:0.16.0-SNAPSHOT:compile
**[INFO] |  |  +- org.apache.spark:spark-mllib-local_2.11:jar:2.4.5:compile**
[INFO] |  |  |  +- org.scalanlp:breeze_2.11:jar:0.13.2:compile
[INFO] |  |  |  |  +- org.scalanlp:breeze-macros_2.11:jar:0.13.2:compile
[INFO] |  |  |  |  +- com.github.fommil.netlib:core:jar:1.1.2:compile
[INFO] |  |  |  |  +- net.sourceforge.f2j:arpack_combined_all:jar:0.1:compile
[INFO] |  |  |  |  +- net.sf.opencsv:opencsv:jar:2.3:compile
[INFO] |  |  |  |  +- org.spire-math:spire_2.11:jar:0.13.0:compile
[INFO] |  |  |  |  |  +- org.spire-math:spire-macros_2.11:jar:0.13.0:compile
[INFO] |  |  |  |  |  \- org.typelevel:machinist_2.11:jar:0.6.1:compile
[INFO] |  |  |  |  \- com.chuusai:shapeless_2.11:jar:2.3.2:compile
[INFO] |  |  |  |     \- org.typelevel:macro-compat_2.11:jar:1.1.1:compile
[INFO] |  |  |  +- org.apache.commons:commons-math3:jar:3.4.1:compile
**[INFO] |  |  |  +- org.apache.spark:spark-tags_2.11:jar:2.4.5:compile
[INFO] |  |  |  \- org.spark-project.spark:unused:jar:1.0.0:compile**
[INFO] |  |  \- com.github.rwl:jtransforms:jar:2.4.0:compile
```

The only spark-related dependencies in the mleap runtime project is on spark-mllib-local, but that's a small library, which doesn't bring in the spark itself. Same for spark-tags_2.11 or spark:unused jar. 

Hope this helps! If you want to send me your setup, I'd be happy to help, to try to identify where spark is being brought in.

**Comment by ancasarb** [comment]
Closing this, in preparation of 0.16.0 release, hopefully the clarification above makes sense, if not, please re-open the issue. Thank you!
