### ISSUE TITLE
How can we change datatype of column in mleap dataframe?

### ISSUE THREAD

**Issue by mtsol** [combust/mleap#651]

**Comment by ancasarb** [comment]
There are a few operations in FrameBuilder that you can use to do this. 

Suppose you have this leapframe

```
  val fields = Seq(StructField("test_string", ScalarType.String),
    StructField("test_double", ScalarType.Double))
  val schema: StructType = StructType(fields).get
  val dataset = Seq(
    Row("hello", 42.13),
    Row("there", 13.42)
  )
  val frame = DefaultLeapFrame(schema, dataset)
```

To change the field type of test_double from Double to String (as an example), you can do 

```
val updatedFrame = frame.withColumn("double_string", "test_double") {
          (r: Double) => r.toString
        }.get
          .drop("test_double").get
updatedFrame.printSchema()
```

Just to make you aware, mleap can do quite a bit of casting, if that's what you're after

https://github.com/combust/mleap/blob/master/mleap-core/src/main/scala/ml/combust/mleap/core/types/Casting.scala

https://github.com/combust/mleap/blob/master/mleap-core/src/test/scala/ml/combust/mleap/core/types/CastingSpec.scala

Hope this helps!

**Comment by ancasarb** [comment]
@mtsol I believe the solution above will achieve what you were looking for, to change the datatype of a column, please re-open the issue if it's not the case. Thank you!
