### ISSUE TITLE
Include a __version__ in python mleap module

### ISSUE THREAD

**Issue by Ben-Epstein** [combust/mleap#659]
For governance purposes and following https://www.python.org/dev/peps/pep-0396/

can you include a __version__ for your module? It would make things much easier to track, thanks!

**Comment by ancasarb** [comment]
We have this here https://github.com/combust/mleap/blob/master/python/mleap/version.py, does this need updating or something?

**Comment by Ben-Epstein** [comment]
@ancasarb Sorry for the late reply. This is why I've brought up the issue.
![Screen Shot 2020-05-19 at 9 42 34 AM](https://user-images.githubusercontent.com/22605641/82333737-1cd3e300-99b5-11ea-81b3-80546e1654e0.png)

I see the version in the code, but something about its format isn't correct as I cannot access it.

**Comment by ancasarb** [comment]
Yeah, at the moment, it seems you need to do 
```
from mleap.version import __version__ as mleap_version
print(mleap_version)
```

I'll see if we can improve this.

**Comment by ancasarb** [comment]
Merged PR to master, will include in next release. Closing this.
