### ISSUE TITLE
mleap-xgboost - runtime and Spark - do not support Scala 2.12

### ISSUE THREAD

**Issue by marccina** [combust/mleap#688]
First, thanks a lot for this nice job !

This issue is an update of [576](https://github.com/combust/mleap/issues/576)

We are using Scala 2.12 and MLeap for XGBoost models.

XGBoost now supports scala 2.12 since [1.0.0 version](https://mvnrepository.com/artifact/ml.dmlc/xgboost-jvm_2.12/1.0.0)

Please, can you help to publish a new version of mleap-xgboost-runtime and mleap-xgboost-spark that support Scala 2.12?

**Comment by mengxr** [comment]
See https://github.com/combust/mleap/pull/686. You can build it from spark-3.0.0 branch. There is no plan yet to support Scala 2.12 with Spark 2.4.

**Comment by marccina** [comment]
Thanks, I understand.
But it's a bad news for us, we are using Spark 2.4 (and like a lot of existing projects, it's not in our roadmap to change for spark 3.0).

**Comment by lucagiovagnoli** [comment]
I'm working on supporting 2.12 on master with spark 2.4 here: https://github.com/combust/mleap/issues/697

@ancasarb to link to our past conversation, it seems useful to have a 0.17.0 version on scala2.12 w/ spark 2.4  for all companies still on spark 2.4
