### ISSUE TITLE
Prediction Probability from mleap model deployed on sagemaker

### ISSUE THREAD

**Issue by janvekarnaveed** [combust/mleap#693]
After deploying mleap model artifact on sagemaker endpoint, during the inferencing stage, how can I get probabilities of prediction rather than binary outcome? I tried changing output column from prediction to probability, but I get the following error:
sagemaker: ml.combust.mleap.tensor.DenseTensor cannot be cast to java.lang.Double

Any suggestions?

**Comment by ancasarb** [comment]
Looks like this is answered under https://github.com/aws/sagemaker-sparkml-serving-container/issues/13#issuecomment-639947118, closing for now, please re-open if you have further questions.
