### ISSUE TITLE
Bug: endpoints are automatically deleted after few hours inactivty 

### ISSUE THREAD

**Issue by eng56** [combust/mleap#707]
Hi, when I load a model on my container the model is working fine but after few hours of inactvity the Endpoint is deleted.
So I need to re-upload my model at least 2 times per day. 
My error message is explicit: 

`"STATUS_ERROR","error":"NotFoundException: no model with name model_1,"backtrace":"ml.combust.mleap.executor.error.NotFoundException: no model with name model_1`

I'm using combustml/mleap-spring-boot:0.16.0-SNAPSHOT

Thank you,

**Comment by ancasarb** [comment]
how long to wait after no more transform request before unloading model from memory is configurable, you can take a look at the `memoryConfig` parameter in the below two links.

https://github.com/combust/mleap/tree/master/mleap-spring-boot

https://github.com/combust/bundle-protobuf/blob/master/mleap/mleap.proto#L112

please let me know if you have further questions, closing the issue for now, but please re-open it if needed.
