### ISSUE TITLE
Referencing a scala/java PipelineStage from pyspark - constructor issues with HasInputCol

### ISSUE THREAD

**Issue by aviadkfbx** [combust/mleap#710]

**Comment by ancasarb** [comment]
@aviadkfbx thanks for raising the issue, could i please ask you if you have a small example that reproduces this issue? it'll enable us to debug the issue easier. also, which mleap version have you encountered this issue with? thanks again!

**Comment by aviadkfbx** [comment]
Hello @ancasarb, not sure how this ticket opened here, but here's an [example I posted on stackoverflow](https://stackoverflow.com/questions/63439162/referencing-a-scala-java-pipelinestage-from-pyspark-constructor-issues-with-ha)

**Comment by talalryz** [comment]
don't think this is related to mleap? @aviadkfbx could you confirm

**Comment by aviadkfbx** [comment]
Yeah, totally agree. Feel free to close.

**Comment by ancasarb** [comment]
Thanks for confirming, closing now!
