### ISSUE TITLE
Query on Mleap 0.16 - Spark and XGboost4j version support

### ISSUE THREAD

**Issue by indranilr** [combust/mleap#712]
Hi,

We are using XGboost4j Spark 0.9 + Spark 2.4.4 for training model and Mleap 0.15 for writing prediction wrapper (deployed on Seldon 1.x). 

Q1. The release note suggests Spark version support for 2.4.5. Does this mean the models built on 2.4.4 will be incompatible to Mleap 0.16 or should I expect as is behavior after upgrade to 0.16 ?

Q2. Is there any known incompatibility with models trained using XGboost 1.1.0 (XGboost4j Spark) and Mleap 0.16 /0.15 ?

**NOTE :** I am interested in using the new xgboost-predictor feature which promises to improve online prediction performance of xgboost models.

**Comment by ancasarb** [comment]
@indranilr thanks for the question. models serialized with Spark versions 2.4.x should work fine with mleap 0.16.

regarding the xgboost version, i believe the version we support currently is 1.0.0. perhaps @voganrc @talalryz have some additional thoughts regarding using xgboost 1.1.0?

**Comment by indranilr** [comment]
Circling back on this issue, we have been using Models trained on Spark 2.4.4, Xgboost 1.0.0 and Mleap 0.16 successfully so far. I do see Xgboost 1.0.0 continues to be used as dependency. 

With Spark being bumped up to 3.0.2 I am not sure if we still would be able to use Xgboost 1.0.0 , Upgrading to Xgboost 1.2.0 could solve the compatibility issue (as it supports Spark 3.0 and scala 2.12)

**Comment by jsleight** [comment]
> With Spark being bumped up to 3.0.2 I am not sure if we still would be able to use Xgboost 1.0.0 , Upgrading to Xgboost 1.2.0 could solve the compatibility issue (as it supports Spark 3.0 and scala 2.12)

Xgboost 1.0.0 was cross compiled for multiple scala versions so it is compatible with Spark v3 and scala 2.12 as well as spark 2.4.x and scala 2.11.  In xgboost 1.2.0 they wanted to add gpu support for their spark module, which required spark 3 (and thus scala 2.12).  So in xgboost 1.2.0 they dropped support for spark 2.4.x and scala 2.11 to only support spark 3 and scala 2.12.

So tl;dr you can keep using xgboost 1.0.0 with spark 3.

That all being said, if you have bandwidth to submit a PR to bump mleap's xgboost version (to current v1.4.2 master version even!), then I'm happy to help review and merge it :)

**Comment by indranilr** [comment]
@jsleight thanks for your response. I will wait for 0.18 release to verify Spark 3 compatibility and will definitely consider a PR for Xgboost upgrade if time permits :). Thanks much !
