### ISSUE TITLE
MLeap runtime performance docs

### ISSUE THREAD

**Issue by Ben-Epstein** [combust/mleap#714]
In your documentation [here](https://mleap-docs.combust.ml/mleap-runtime/row-transformer.html) you mention that you can speed up inference even more with the "row-based transformer" 

Is there an example of this? 

Thanks!

I see [here](https://github.com/combust/mleap/blob/536b18decc12b3ff4b7d40a4f51ba1a11890e57c/mleap-executor/README.md#creating-a-row-stream) there's an example in Scala. Is there a Java one by chance?

**Comment by mtsol** [comment]
the correct way of using row transformer is this:
//initialize once
val rowTransformer = mleapPipeline.transform(RowTransformer(inputSchema)).get

//use everytime
val transformedRow = rowTransformer.transform(dataRow)

Scala can be called from java through a wrapper, so there is no difference in running java and scala

**Comment by ancasarb** [comment]
hey @Ben-Epstein, sorry for the delayed response, we have a unit test for the java dsl, there's an example how to use the row transformer from Java in there, please see https://github.com/combust/mleap/blob/master/mleap-runtime/src/test/scala/ml/combust/mleap/runtime/javadsl/JavaDSLSpec.java#L97.

**Comment by ancasarb** [comment]
closing for now, please re-open the issue if you have any further questions, thank you!

**Comment by Ben-Epstein** [comment]
Great, thanks @ancasarb
