### ISSUE TITLE
Deserialization of RandomForestRegression model into a spark stage is incorrect if the number of trees is set to a value other than the default

### ISSUE THREAD

**Issue by leahmcguire** [combust/mleap#721]
For the spark RandomForestRegressor model the deserialized spark model will always have the default number of trees (20) resulting in incorrect scores on deserialization as a spark stage. (It produces the correct scores when deserialized as an mleap stage)

**Comment by ancasarb** [comment]
thanks for raising this bug @leahmcguire , i've created a PR to fix this and it'll be included in the next release. thanks again!
