### ISSUE TITLE
MLeap model gives very different prediction from Spark model for XGBoost regression

### ISSUE THREAD

**Issue by maycuiyan** [combust/mleap#728]
Below is the code I used in my testing. I created a dummy data frame in the code so you may directly run this code to reproduce my result. 

What I found is that the deserialized Mleap model gives very different prediction from the Spark model prediction when XGBoost regression model is used. What is interesting though, is that if I replace the XGBoost regression model with a linear regression model or random forest model, then the Mleap and Spark predictions are consistent. 

Could you please take a look and see what's causing the issue?

```
import ml.combust.mleap.spark.SparkSupport._
import org.apache.spark.ml.bundle.SparkBundleContext
import org.apache.spark.sql._
import ml.combust.bundle.BundleFile
import ml.combust.mleap.runtime.MleapSupport._
import resource._
import ml.dmlc.xgboost4j.scala.spark.XGBoostRegressor
import org.apache.spark.ml.Pipeline
import org.apache.spark.ml.feature.{OneHotEncoderEstimator, StringIndexer, VectorAssembler}
import ml.combust.bundle.serializer.SerializationFormat
import scala.util.Random
import java.io.File

val spark = SparkSession.builder().
  enableHiveSupport().
  appName("bid_response_feedback").
  getOrCreate()
spark.sparkContext.setLogLevel("WARN")

import spark.implicits._

// -------------------create dummy data-------------------
val N = 1000
val X = Seq.fill(N)((Random.nextDouble, Random.nextDouble, Random.nextInt%100, Random.nextDouble))
val data = X.toDF("num1", "num2", "cat", "y")

// -------------------create pipeline-------------------
val stringIndexer = new StringIndexer().setInputCol("cat").setOutputCol("indexed_cat").setHandleInvalid("keep")
val encoder = new OneHotEncoderEstimator().
  setInputCols(Array("indexed_cat")).
  setOutputCols(Array("encoded_cat")).
  setDropLast(false)
val vectorAssembler = new VectorAssembler().setInputCols(Array("num1","num2", "encoded_cat")).setOutputCol("assembled_features")
val regressor = new XGBoostRegressor().
  setFeaturesCol("assembled_features").
  setLabelCol("y").
  setMissing(0.0f).
  setNumRound(300).
  setEta(0.1).
  setLambda(0.1).
  setObjective("reg:squarederror")
val stages = Array(stringIndexer, encoder, vectorAssembler, regressor)
val pipeline = new Pipeline().setStages(stages)

// -------------------train model-------------------
val model = pipeline.fit(data)
val sparkPred = model.transform(data)

// -------------------serialize model-------------------
val savePath = "/tmp/model.zip"
new File(savePath).delete()
val sbc = SparkBundleContext().withDataset(sparkPred)
for(bf <- managed(BundleFile(s"jar:file:$savePath"))) {
  model.writeBundle.format(SerializationFormat.Json).save(bf)(sbc).get
}

// -------------------deserialize model-------------------
val bundle = (for(bundleFile <- managed(BundleFile(s"jar:file:$savePath"))) yield {
  bundleFile.loadMleapBundle().get
}).opt.get
val mleapPipeline = bundle.root

// -------------------compare spark prediction with mleap prediction-------------------
mleapPipeline.sparkTransform(
  sparkPred.select("num1", "num2", "cat", "prediction").
  withColumnRenamed("prediction", "prediction_spark")
).withColumnRenamed("prediction", "prediction_mleap").
  select("prediction_spark", "prediction_mleap").show(20, false)
```

And below is result of the comparison:
+-------------------+--------------------+
|prediction_spark   |prediction_mleap    |
+-------------------+--------------------+
|0.25716912746429443|0.6468673348426819  |
|0.37263065576553345|0.09767213463783264 |
|0.5152825117111206 |0.4851878881454468  |
|0.3583545386791229 |0.7318365573883057  |
|0.36735931038856506|0.4338415265083313  |
|0.5590494871139526 |0.8566745519638062  |
|0.19842255115509033|0.7155959010124207  |
|0.505892276763916  |0.1759815216064453  |
|0.5023373961448669 |0.625703752040863   |
|0.4556388854980469 |1.0078493356704712  |
|0.49337154626846313|0.6475313901901245  |
|0.47036445140838623|0.8019598722457886  |
|0.46043094992637634|-0.07858127355575562|
|0.5120362639427185 |0.6594986915588379  |
|0.5190843343734741 |0.8715968132019043  |
|0.7019040584564209 |0.8972176313400269  |
|0.5937442183494568 |0.3763286769390106  |
|0.5282356142997742 |0.02316725254058838 |
|0.6432276964187622 |0.47867345809936523 |
|0.5145360827445984 |0.6871364116668701  |
+-------------------+--------------------+

**Comment by ancasarb** [comment]
@maycuiyan thanks for raising the issue! can i please ask you which version of mleap/spark/xgboost you are using?

@talalryz @voganrc could you please take a look once at this? thank you!

**Comment by talalryz** [comment]
we'd made some changes before releasing 0.16.0 which fixed such issues

which version of mleap are you using? What does your pipeline look like?

**Comment by maycuiyan** [comment]
@ancasarb @talalryz Thanks for following this up. This is because of the older version of MLeap and I can see that in newer version the issue is fixed. I am closing this issue.
