### ISSUE TITLE
Example leap frames

### ISSUE THREAD

**Issue by BlackTrade** [combust/mleap#731]
Hello! I can't download example leap frames from link https://s3-us-west-2.amazonaws.com/mleap-demo/frame.airbnb.json
in yours https://mleap-docs.combust.ml/mleap-serving/#unload-model

**Comment by ancasarb** [comment]
hey @BlackTrade thanks for raising the issue. apologies for this, you can also download the example frames from https://github.com/combust/mleap/tree/master/mleap-benchmark/src/main/resources/leap_frame. I'll make sure to update the documentation. 

closing this, please re-open if you have any further questions.
