### ISSUE TITLE
Spark 3.X support

### ISSUE THREAD

**Issue by vvavepacket** [combust/mleap#739]
Hello,

Do we have any timelines on when mleap be compatible with Spark 3.0 generated models? I see there is a branch opened but its been half a year since there are no activities. Do we have any other PRs or remaining features for that branch to be merged to master and be usable?

**Comment by ancasarb** [comment]
hello, we should be able to try to get the Spark 3.0 branch merged in in the next couple of weeks, i will close this ticket and just keep https://github.com/combust/mleap/issues/727 for reference. thank you!
