### ISSUE TITLE
MLeap documentation link appears to redirect to a scam website

### ISSUE THREAD

**Issue by goyetc** [combust/mleap#744]
The link listed in "About" section of this git repo does not direct to the link that exists within the README.

About section: "mleap-docs.combust.ml/" redirects to unexpected URLs and asks to install a Chrome extension

README: https://combust.github.io/mleap-docs/ directs to actual documentation page.

**Comment by ancasarb** [comment]
hey @goyetc thanks for letting us know, i've updated the about section as well. thanks again!
