### ISSUE TITLE
ScalaPB too old version

### ISSUE THREAD

**Issue by AlexisBRENON** [combust/mleap#786]
Hi,

I use a newer version (0.10.11) of scalapb than the one used by MLeap (0.7.1).
I attempted an update of this dependency, starting from MLeap v0.17.0 (because I don't use Spark3 for the moment).
I opened a [PR on my fork](https://github.com/Adyoulike/mleap/pull/1), but cannot open one in the upstream because there is no `release/v0.17.1` branch.
Can I hope that it will merged in the upstream?
I think I'll have to port this PR to v0.18.x too.

**Comment by emitc2h** [comment]
Hey @jsleight @AlexisBRENON @ancasarb, I prepared a PR to fix this issue: https://github.com/combust/mleap/pull/818. I was mostly feeling my way in the dark since I'm no sbt expert, but we actually really need this upgrade as well so I thought I'd take a crack at it.

**Comment by AlexisBRENON** [comment]
@emitc2h I did a PR to upgrade ScalaPB as well as sbt: Adyoulike/mleap#1.
However, I encounter some difficulties to make it retro-compatible.
ScalaPB upgrade brings a new field to all Protobuf based classes (the `UnknownFieldSet` field). This new field:
- need to be serialized correctly when saving a model (this is not the hard part)
- need to be filled in when deserializing an model saved with an older version (this is where I struggle)

From what I see, your PR is mainly SBT related and I don't see much code about handling this new protobuf field.

**Comment by jsleight** [comment]
Think this should be resolved now.  Thanks @emitc2h and @AlexisBRENON for the PR!

**Comment by CatTail** [comment]
@jsleight can you help to publish a new version of mleap using the new scalapb version?
