### ISSUE TITLE
When will mleap 0.19.0 release be available

### ISSUE THREAD

**Issue by icarusin** [combust/mleap#790]
Hello all,

 Would like to know when mleap version 0.19.0 will be available? There are fixes on that version that we would like to use. We have used the snapshot version for now but would be great to know when the release will be available.

Much appreciate all the help.

**Comment by jsleight** [comment]
I'm hoping to get my map type support PR into the next release #789 , not sure if @voganrc has other PRs in mind for the next release.  Maybe v0.19.0 sometime in mid December?

**Comment by icarusin** [comment]
Thank you for sharing the release date @jsleight

**Comment by satyakisen** [comment]
Hello @jsleight 
Is there any plan on supporting JDK 11 in the release for Mleap v0.19.0?

**Comment by jsleight** [comment]
JDK 11 is not included in the v0.19.0 release (which hopefully should come out this week).

Of course you can load the mleap jars into a newer JRE, but since you're asking about JDK, then I'm not sure how compatible things are.

**Comment by satyakisen** [comment]
Thank you @jsleight

**Comment by icarusin** [comment]
I had another question on the mleap 0.19.0 release. I see the documentation mentions 0.19.0, however I don't see a new tag created for the release. Are there more changes to be merged to 0.19.0 release? Thank you

```


MLeap Version | Spark Version
-- | --
0.19.0 | 3.0.2
```

**Comment by jsleight** [comment]
No good reason.  We simply didn't quite the release done before folks went away for end of year holidays haha. @voganrc is working on getting the release out though.

Since we had a delay, we'll also the spring upgrade (#797 is already merged) in there which fixes any chance of the log4j vulnerabilities from spring.

**Comment by cappaberra** [comment]
@jsleight, I just added a comment to #797, but thought I'd X-post it here, too.

https://github.com/combust/mleap/pull/797#issuecomment-1005845044

Thanks so much!

**Comment by icarusin** [comment]
Since the version is now available - 

```
0.19.0 | 3.0.2
-- | --
```

This issue could perhaps be closed? Thank you all.

**Comment by jsleight** [comment]
indeed.  Please let us know (via new issues) if folks encounter issues :)
