### ISSUE TITLE
Is JDK 11+ now supported?

### ISSUE THREAD

**Issue by karllessard** [combust/mleap#804]
In [this documentation](https://github.com/combust/mleap#requirements) (and maybe elsewhere?), it says that only Java8 is actually supported by MLeap but is it still the case after the upgrade to Scala 3? 

I'm asking because in TensorFlow Java, we are planning to abandon the support of Java8 and build our next releases under JDK 11, so I just want to validate if some actions would be required in this project to use the new artifacts, thanks!

**Comment by jsleight** [comment]
>  If you want, I suggest that we keep this issue open and I can let you know when we have available snapshots for you to try.

Sounds good to me 😄

**Comment by jsleight** [comment]
Happy to announce that I just merged #818 which upgraded mleap to java 11.  If folks want to try it out then you should be able to use the snapshot release starting tomorrow
