### ISSUE TITLE
Will mleap support spark 3.1.2 ?

### ISSUE THREAD

**Issue by inardini** [combust/mleap#805]
Based on project page, mleap supports spark 3.0.2. Any plan to support spark 3.1.2?

Thanks

**Comment by indranilr** [comment]
Upcoming release will support Spark 3.2 .Refer to [https://github.com/combust/mleap/pull/799](url)

**Comment by jsleight** [comment]
Closing since mleap 0.20 is now released and supports spark 3.2.0
