### ISSUE TITLE
mleap enhancments

### ISSUE THREAD

**Issue by mtsol** [combust/mleap#814]
- [x] Add support for Keras
- [ ] Add support for PyTorch
- [ ] Add support for DL
- [ ] Add support for LSTM

**Comment by mullerhai** [comment]
when support pytorch model  save and load ？

**Comment by jsleight** [comment]
Supporting pytorch is difficult because pytorch does not have any java bindings (to my knowledge at least).  The best option for supporting pytorch is probably to support something like ONNX and then have folks convert their pytorch models into ONNX before serializing.

**Comment by mullerhai** [comment]
> Supporting pytorch is difficult because pytorch does not have any java bindings (to my knowledge at least). The best option for supporting pytorch is probably to support something like ONNX and then have folks convert their pytorch models into ONNX before serializing.

ok, if pytorch has  java bindings,do you know how to save pytorch save and load, maybe I could do it ,just tell me the method is ok

**Comment by jsleight** [comment]
There currently isn't any pytorch support in mleap.  You'd need to create:
- a new mleap transformer
- a new mleap op
- a new spark transformer
- a new spark op

Basically look at everything which exists for tensorflow and need a new variant of that for pytorch.

**Comment by mullerhai** [comment]
> There currently isn't any pytorch support in mleap. You'd need to create:
> 
> * a new mleap transformer
> * a new mleap op
> * a new spark transformer
> * a new spark op
> 
> Basically look at everything which exists for tensorflow and need a new variant of that for pytorch.

thanks, If I success ,please  pick up me code
