### ISSUE TITLE
Exception in thread "Thread-4" java.lang.NoClassDefFoundError: ml/combust/bundle/HasBundleRegistry

### ISSUE THREAD

**Issue by drei34** [combust/mleap#845]
I'm not sure if this issue has a resolution. Why would this error happen and how can you fix it?

I'm on Java 8, mleap 0.20.0, Scala 2.12 and pyspark 3.1.3.

https://github.com/combust/mleap/issues/442

**Comment by jsleight** [comment]
Might be related to the issue in #842

**Comment by drei34** [comment]
Ha right it is related to #842 I guess but more related to #442. #442 was closed, but I am unsure why because the answer is not there. So I figure I can directly address that here ...

**Comment by drei34** [comment]
This was resolved after we installed Java 11 and used the malest mleap. We used `mleap-databricks-runtime-fat-assembly-0.22.0`. You also need to change JAVA_HOME inside of spark. The command below might work.

`
# We need this new Java since the new Mleap uses Java 11.
sudo apt-get -y install openjdk-11-jdk
export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
# If you don't do this, Spark will complain about Python 3.7 and 3.8.
export PYSPARK_PYTHON=/opt/conda/miniconda3/bin/python
export PYSPARK_DRIVER_PYTHON=/opt/conda/miniconda3/bin/python
pip install mleap
# Copy the jar to the right location
cp mleap-databricks-runtime-fat-assembly-0.22.0.jar $SPARL_HOME/jars
echo "export JAVA_HOME=\"/usr/lib/jvm/java-11-openjdk-amd64\"" >> $SPARK_HOME/conf/spark-env.sh
`
