### ISSUE TITLE
Need help installing MLeap and XGBoost on databricks

### ISSUE THREAD

**Issue by venkatacrc1** [combust/mleap#848]
Hello,
Can someone elaborate the instructions on this README page.
https://github.com/combust/mleap/blob/master/mleap-databricks-runtime-fat/README.md

I have created local M2 repository in debian linux:
mkdir -p ~/.m2
copied the XGBoost JAR files xgboost4j-spark_2.12-1.7.3.jar  xgboost4j_2.12-1.7.3.jar before compiling the 
mleap-databricks-runtime-fat/target/scala-2.12/mleap-databricks-runtime-fat-assembly-0.22.0.jar file using the  sbt command.
`sbt mleap-databricks-runtime-fat/assembly`

I see the following warnings during the compilation:
[warn] there's a key that's not used by any other settings/tasks:
[warn]  
[warn] * mleap-xgboost-spark / test / javaOptions
[warn]   +- /root/mleap/mleap-xgboost-spark/build.sbt:3
[warn]  
[warn] note: a setting might still be used by a command; to exclude a key from this `lintUnused` check
[warn] either append it to `Global / excludeLintKeys` or call .withRank(KeyRanks.Invisible) on the key

I am seeing the following Py4J error while running the MLeap serializeToBundle command. `model.serializeToBundle(local_path, predictions)` 
Py4JJavaError: An error occurred while calling o219.serializeToBundle.
: java.lang.NoClassDefFoundError: ml/dmlc/xgboost4j/scala/spark/XGBoostClassificationModel

sparkVersion: 3.1.3
Scala Version: 2.12.1
Python: 3.8.15

**Comment by jsleight** [comment]
@WeichenXu123 do you have thoughts on this one?

**Comment by venkatacrc1** [comment]
Thank you @jsleight ! @WeichenXu123 : Do we need to add the following dependency in of the build.sbt files?
```
libraryDependencies ++= Seq(
  "ml.dmlc" %% "xgboost4j" % "latest_version_num",
  "ml.dmlc" %% "xgboost4j-spark" % "latest_version_num"
)
```

**Comment by WeichenXu123** [comment]
@venkatacrc1 Mleap and xgboost are preinstalled in databricks ML runtime, you can directly use it.

**Comment by venkatacrc1** [comment]
@WeichenXu123 Do you have any example notebook/code snippet that you can share? I do not have any luck finding them.

**Comment by WeichenXu123** [comment]
@venkatacrc1 

First, you should use databricks ML runtime: https://docs.databricks.com/runtime/mlruntime.html

then, you can check our doc: https://docs.databricks.com/machine-learning/model-export/mleap-model-export.html#

**Comment by venkatacrc1** [comment]
@jsleight, @WeichenXu123:

Thank you for helping. This issue is resolved on my end with the following steps. 
`
mkdir -p ~/.m2/repository/ml/dmlc/xgboost4j-spark_2.12/1.7.3/
cd ~/.m2/repository/ml/dmlc/xgboost4j-spark_2.12/1.7.3/
wget https://repo1.maven.org/maven2/ml/dmlc/xgboost4j-spark_2.12/1.7.3/xgboost4j-spark_2.12-1.7.3.jar
cd
sudo cp ~/.m2/repository/ml/dmlc/xgboost4j-spark_2.12/1.7.3/xgboost4j-spark_2.12-1.7.3.jar /usr/lib/spark/jars/
`
