### ISSUE TITLE
Please release version 0.22.0 and 0.23.0 of mleap-spring-boot on dockerhub

### ISSUE THREAD

**Issue by ronandoolan2** [combust/mleap#857]
Hi,

Only up to version 0.21.0 is released on dockerhub, could you please release the latest version?

Alternatively could you add a dockerfile for building mleap, or better instructions?
I have 
sbt : 1.4.9
java: 11
scala: 2.12.13

Yet still get an error when trying to build mleap.

Thanks, 
Ronan

**Comment by jsleight** [comment]
I'll look into the dockerhub at some point (we changed who does the releases and I was not aware we even had a dockerhub artifact).

For your specific error I think you need to initialize the submodules of the mleap repo which contain the bundle logic.

**Comment by ronandoolan2** [comment]
Thanks that's great,

Could you please add the steps for initializing the submodules of the repo to the readme

**Comment by ronandoolan2** [comment]
This seems to the release process for updating dockerhub
https://github.com/combust/mleap/blob/master/travis/release.sh

**Comment by cappaberra** [comment]
Bumping this again. ☝️ 

I ran into the need for the latest (`v0.23.1` as of this writing) docker image.  Assuming the [necessary versions](https://github.com/combust/mleap?tab=readme-ov-file#dependency-compatibility-matrix) of Scala, sbt, Java, Docker, etc. are installed already, I used the following commands from the root of the MLeap repo:

```
git clone https://github.com/combust/mleap.git; cd mleap
git checkout v0.23.1
sbt mleap-serving/docker:stage
cd mleap-serving/target/docker/stage
docker build -t mleap-image:v0.23.1 .
```

In order for us to build this directly from DockerHub, @jsleight, can you please work on getting the latest (and ideally all missing tagged versions) into there?

Thank you in advance!!

**Comment by austinzh** [comment]
@ronandoolan2 For the build issue, I believe it's because you forget to `git submodule update --init --recursive`. The protobuf is submodule here. After that you should build without problem.

**Comment by austinzh** [comment]
@cappaberra I just push 

combustml/mleap-serving:0.23.1
combustml/mleap-serving:0.23.3
combustml/mleap-spring-boot:0.23.1
combustml/mleap-spring-boot:0.23.3

version lower than 0.23.0 can not be build now. So I can not build it back.
The release script in travis break for a while now. We are trying to fix it.
